CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.VALE`
(
  IDVALE STRING,
  IDEXPEDIENTE STRING,
  CODPROVEEDOR STRING,
  MONTO FLOAT64,
  FOLIO STRING,
  FECHAEXPEDICION DATETIME,
  FECHAACTUALIZACION DATETIME,
  IDVALEESTATUS STRING,
  VALE BYTES,
  LEIDOORDEN BIGNUMERIC,
  LEIDOVALE BIGNUMERIC,
  PIEZASRECIBIDAS BIGNUMERIC,
  AUTORIZADOR STRING,
  COTIZADOR BIGNUMERIC,
  TOTALDESRESCATEPT FLOAT64,
  ESTATUSVALESISE STRING,
  MONTOPAGADOSISE STRING,
  FECHAPAGOSISE DATETIME,
  PENDIENTELIBERAR BIGNUMERIC NOT NULL,
  DEVUELTO STRING NOT NULL,
  ESTATUSACTUALSISE STRING
);
