CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  Z_ID STRING NOT NULL,
  OFICINA STRING,
  DIRECCION STRING,
  COLONIA STRING,
  POBLACION STRING,
  EDOPOB STRING,
  CP STRING,
  ZONA STRING
);
