CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  ZID STRING,
  NOMBRE STRING,
  GIRO STRING,
  NACIONALIDAD STRING,
  FOLIO STRING,
  APODERADO STRING,
  NAC_APODERADO STRING,
  RFC STRING,
  ART_140 STRING,
  FEC_NACE DATETIME,
  FEC_ALTA DATETIME,
  TIP_ASEG STRING,
  CORREO STRING,
  CURP STRING,
  OFICINA STRING,
  NOM_OFICINA STRING
);
