CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.REGISTRO`
(
  SINIESTRO STRING,
  ID_OF STRING,
  DESC_OF STRING,
  USUARIO STRING,
  NOMBRE STRING,
  CORREO STRING,
  MOTIVO STRING,
  OBSERVACIONES STRING,
  DOC_ADICIONAL STRING,
  SIN_SNA STRING,
  ID_ANALISTA STRING,
  FECHA_ASIG DATETIME,
  AREA STRING,
  PUESTO STRING,
  ID_MOTIVO STRING,
  MARCA STRING,
  MONTO_ESTIMADO NUMERIC,
  BATCHDATE DATETIME,
  SYSUSERID STRING
);
