CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  RECIBO STRING,
  FEC_VTO STRING,
  POLIZA STRING,
  ENDOSO STRING,
  IMPORTE STRING,
  REMESA STRING,
  MARCA_IMP STRING,
  MARCA_ANUL STRING,
  PRIMA_NETA STRING,
  DER_POL STRING,
  REC_FIN STRING,
  IVA STRING,
  BONIFICACION STRING,
  BONIF_RF STRING,
  BONIF_TEC STRING,
  PRIMA_TOTAL STRING,
  USU_APLICA STRING,
  FEC_APLICACION STRING,
  HORA_APLICA STRING,
  IMPRESION STRING,
  RFC_FACT STRING,
  USUARIO_EMITE STRING,
  FECHA_PROCESO STRING,
  FECHA_CARGA DATETIME
)
PARTITION BY DATE(_PARTITIONTIME);
