CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.CERCO`
(
  IDCERCO STRING,
  NOMBRE STRING,
  FECHAREGISTRO DATETIME,
  FECHAACTUALIZACION DATETIME,
  IDENTIDAD STRING,
  SUSPAUT STRING,
  IDCATEGORIACERCO STRING,
  IDSEGMENTACION STRING
);