CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  ANALISTA STRING,
  ID_ANALISTA STRING,
  NOMBRE STRING,
  CORREO STRING,
  ESTATUS STRING,
  ESTATUS_DT DATETIME,
  ASIG_DT DATETIME,
  CARRUSEL NUMERIC,
  BATCHDATE DATETIME,
  SYSUSERID STRING,
  ID_USER_94 STRING
)
PARTITION BY DATE(_PARTITIONTIME);
