CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  Z_ID STRING,
  EDOPOB STRING,
  ESTATUS STRING,
  CVEMPIO_INEGI STRING,
  REGION STRING,
  RADIOPERFIL STRING,
  EDO_ESTANDAR STRING,
  EDOPOB2 STRING
);
