CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  Z_ID STRING,
  CAUSA STRING,
  CAUSA_HOMOLOGADA STRING,
  BATCHDATE DATETIME,
  SYSUSERID STRING
)
PARTITION BY DATE(_PARTITIONTIME);
