CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ENVIOHISTORICO`
(
  IDENVIOHISTORICO STRING,
  IDEXPEDIENTE STRING,
  FECHAENVIOTALLER DATETIME,
  FECHAASIGNACIONVALUADOR DATETIME,
  FECHAAUTORIZACIONVALUADOR DATETIME,
  DATO STRING,
  IDCAUSAASIGNARCOMPLEMENTO STRING,
  AUTORIZADOAUTOMATICO BIGNUMERIC,
  CODVALUADORCOMPLEMENTO STRING
);