CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.TESTADO_BSC`
(
  Z_ID STRING,
  EDOPOB STRING,
  ESTATUS STRING,
  CVEMPIO_INEGI STRING,
  REGION STRING,
  RADIOPERFIL STRING,
  EDO_ESTANDAR STRING,
  EDOPOB2 STRING
);
