CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.CAUSACAMBIOVALE`
(
  IDCAUSACAMBIOVALE STRING NOT NULL,
  DESCRIPCION STRING NOT NULL,
  FECHAREGISTRO DATETIME NOT NULL,
  FECHAACTUALIZACION DATETIME NOT NULL,
  USUARIO STRING NOT NULL
);