CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.REFACCION`
(
  IDREFACCION STRING NOT NULL,
  DESCRIPCION STRING,
  ALTA DATETIME,
  ACTUALIZACION DATETIME,
  USUARIOACTUALIZA STRING,
  AUTOS STRING,
  EP STRING
)
