CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.TSUC_BSC`
(
  Z_ID STRING NOT NULL,
  OFICINA STRING,
  DIRECCION STRING,
  COLONIA STRING,
  POBLACION STRING,
  EDOPOB STRING,
  CP STRING,
  ZONA STRING
);
