CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ETIQUETA_SINIESTRO`
(
  REPORTE STRING,
  SINIESTRO STRING,
  COD_STATUS STRING,
  FEC_INV DATETIME,
  TEXT_INVEST STRING,
  USUARIO_INV STRING,
  TEXT_LOC STRING,
  FEC_LOC DATETIME,
  FEC_CARGA DATETIME,
  HORA_PROCESO DATETIME,
  BATCHDATE DATETIME,
  SYSUSERID STRING,
  Z_ID STRING
);
