CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.CAT_CAUSA`
(
  Z_ID STRING,
  CAUSA STRING,
  CAUSA_HOMOLOGADA STRING,
  BATCHDATE DATETIME,
  SYSUSERID STRING
)
PARTITION BY DATE(_PARTITIONTIME);
