CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ESTATUSEXPEDIENTES`
(
  IDESTATUSEXPEDIENTE STRING NOT NULL,
  DESCRIPCION STRING,
  ALTA DATETIME,
  ACTUALIZACION DATETIME,
  USUARIOACTUALIZA STRING
);
