CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  SINIESTRO STRING,
  ID_OF STRING,
  DESC_OF STRING,
  USUARIO STRING,
  NOMBRE STRING,
  CORREO STRING,
  MOTIVO STRING,
  OBSERVACIONES STRING,
  DOC_ADICIONAL STRING,
  SIN_SNA STRING,
  ID_ANALISTA STRING,
  FECHA_ASIG DATETIME,
  AREA STRING,
  PUESTO STRING,
  ID_MOTIVO STRING,
  MARCA STRING,
  MONTO_ESTIMADO NUMERIC,
  BATCHDATE DATETIME,
  SYSUSERID STRING
);
