CREATE OR REPLACE VIEW `qlts-dev-mx-au-pla-verificacio.qlts_bro_op_prevencion_fraudes_dev.USUARIO_UNICO_H` AS
SELECT DISTINCT  
  PV.COD_ASEG AS ASEGURADO_GR
  ,PV.COD_ASEG AS ASEGURADO
  ,SAFE_CAST(NULL AS STRING) AS RFC_ASEG
  ,MA.NOMBRE AS ASEG
  ,SAFE_CAST(NULL AS STRING) AS CP
  ,SAFE_CAST(NULL AS STRING) AS FEC_NACIMIENTO
  ,CAST(CONCAT(SUBSTRING(PV.FEC_EMI,7,4),'-',SUBSTRING(PV.FEC_EMI,4,2),'-',SUBSTRING(PV.FEC_EMI,1,2)) AS DATETIME) AS FEC_EMI
  ,SAFE_CAST(NULL AS STRING) AS TIPO_PERSONA
  ,SAFE_CAST(NULL AS STRING) AS NOMBRE
  ,SAFE_CAST(NULL AS STRING) AS AP_PATERNO
  ,SAFE_CAST(NULL AS STRING) AS AP_MATERNO
  ,SAFE_CAST(NULL AS STRING) AS RFC_CONTRATANTE
  ,SAFE_CAST(NULL AS STRING) AS CORREO
  ,SAFE_CAST(NULL AS STRING) AS CORRERO_STND
  ,SAFE_CAST(NULL AS STRING) AS TELEFONO
  ,SAFE_CAST(NULL AS STRING) AS TELEFONO_STND
  ,CURRENT_DATETIME('UTC-6') AS LAST_UPDATE_TIME
FROM `qlts-dev-mx-au-bro-verificacio.BACKUPS.FRAUD_PV_copy` PV
INNER JOIN `qlts-dev-mx-au-bro-verificacio.qlts_bro_op_verificaciones_dev.MASEG_BSC` MA ON PV.COD_ASEG = MA.ZID 