SELECT
  Z_ID
  ,REPORTE
  ,SINIESTRO
  ,COD_STATUS
  ,FEC_INV
  ,TEXT_INVEST
  ,USUARIO_INV
  ,TEXT_LOC
  ,FEC_LOC
  ,FEC_CARGA
  ,HORA_PROCESO
  ,BATCHDATE
  ,SYSUSERID
  ,CONSECUTIVO
  ,REVERSO_CONSECUTIVO
FROM `STG_FRAUDES.STG_ETIQUETA_SINIESTRO_3`
