CREATE OR REPLACE TABLE `STG_FRAUDES.STG_ETIQUETA_SINIESTRO_3` AS
SELECT
  Z_ID
  ,REPORTE
  ,SINIESTRO
  ,COD_STATUS
  ,FEC_INV
  ,TEXT_INVEST
  ,USUARIO_INV
  ,TEXT_LOC
  ,FEC_LOC
  ,FEC_CARGA
  ,HORA_PROCESO
  ,BATCHDATE
  ,SYSUSERID
  ,CONSECUTIVO
  ,ROW_NUMBER() OVER(PARTITION BY SINIESTRO ORDER BY CONSECUTIVO DESC) AS REVERSO_CONSECUTIVO
FROM `STG_FRAUDES.STG_ETIQUETA_SINIESTRO_2`
