CREATE OR REPLACE TABLE `STG_FRAUDES.STG_ETIQUETA_SINIESTRO_2` AS 
(WITH E AS
(SELECT
  Z_ID
  ,REPORTE
  ,SINIESTRO
  ,COD_STATUS
  ,FEC_INV
  ,TEXT_INVEST
  ,USUARIO_INV
  ,TEXT_LOC
  ,FEC_LOC
  ,FEC_CARGA
  ,HORA_PROCESO
  ,BATCHDATE
  ,SYSUSERID
  ,ROW_NUMBER() OVER(PARTITION BY Z_ID ORDER BY HORA_PROCESO DESC) AS REPETIDO
FROM `STG_FRAUDES.STG_ETIQUETA_SINIESTRO_1`
)
SELECT
  Z_ID
  ,REPORTE
  ,SINIESTRO
  ,COD_STATUS
  ,FEC_INV
  ,TEXT_INVEST
  ,USUARIO_INV
  ,TEXT_LOC
  ,FEC_LOC
  ,FEC_CARGA
  ,HORA_PROCESO
  ,BATCHDATE
  ,SYSUSERID
  ,REPETIDO
FROM E
WHERE REPETIDO = 1)