

-- ================================================================================
-- FASE 8: CLASIFICACIÓN DE ASIGNACIONES Y COLUMNAS CALCULADAS
-- ================================================================================

CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.QUERY_FOR_TLP` AS
SELECT *,
    -- PIEZAENTREGADA
    CASE WHEN fecentregarefaccionaria IS NOT NULL THEN 1 ELSE 0 END AS PIEZAENTREGADA,
    
    -- MESEXPEDICION
    EXTRACT(MONTH FROM FECHAEXPEDICION) AS MESEXPEDICION,
    
    -- ANIO_EXPEDICION
    EXTRACT(YEAR FROM FECHAEXPEDICION) AS ANIO_EXPEDICION,
    
    -- LLAVEPIEZA
    CONCAT(CAST(idexpediente AS STRING), TRIM(IFNULL(referencia,'')), TRIM(IFNULL(numparte,'')), TRIM(IFNULL(descripcionrefaccion,''))) AS LLAVEPIEZA,
    
    -- TIPOASIGNACION1
    CASE
        WHEN USUARIO = 'AUT' THEN 'AUTOMATICO'
        WHEN USUARIO LIKE '%AUT /%' THEN 'MANUAL CON ALERTA'
        WHEN UPPER(USUARIO) LIKE '%ADMINREFC%' 
             OR USUARIO LIKE '%KAGONZALEZ%' 
             OR USUARIO LIKE '%PERUIZ%' 
             OR USUARIO LIKE '%PRUIZ%' 
             OR USUARIO LIKE '%KGONZALEZ%' 
             OR UPPER(USUARIO) LIKE 'ASR_COMP%' 
             OR UPPER(USUARIO) LIKE '%EDSANCHEZ%' 
             OR UPPER(USUARIO) LIKE '%JOVAZQUEZ%' 
             OR UPPER(USUARIO) IN ('CORCOMSEG1','CORCOMSEG10','CORCOMSEG11','CORCOMSEG13','CORCOMSEG15','CORCOMSEG30','CORCOMSEG31','CORCOMSEG32','CORCOMSEG33','CORCOMSEG34','CORCOMSEG42','CORCOMSEG45','CORCOMSEG160','CORCOMSEG2','CORCOMSEG3','CORCOMSEG4','CORCOMSEG5','CORCOMSEG6','CORCOMSEG7','CORCOMSEG8','CORCOMSEG9','CORCOMSEG12','CORCOMSEG14','CORCOMSEG16','CORCOMSEG17','CORCOMSEG18','CORCOMSEG19','CORCOMSEG20','CORCOMSEG21','CORCOMSEG22','CORCOMSEG23','CORCOMSEG24','CORCOMSEG25','CORCOMSEG26','CORCOMSEG27','CORCOMSEG28','CORCOMSEG29','CORCOMSEG35','CORCOMSEG36','CORCOMSEG37','CORCOMSEG38','CORCOMSEG39','CORCOMSEG40','CORCOMSEG114','CORCOMSEG43','CORCOMSEG150','CORCOMSEG151','EDSANCHEZ','CORCOMSEG46')
             THEN 'MANUAL COMPRAS'
        WHEN UPPER(USUARIO) LIKE 'ASR%' 
             OR UPPER(USUARIO) LIKE '%SUPSEG%' 
             OR UPPER(USUARIO) LIKE 'SV_____%' 
             OR UPPER(USUARIO) LIKE '%OTOLEDO%' 
             OR (UPPER(USUARIO) LIKE 'CORCOMSEG%' AND UPPER(USUARIO) NOT IN ('CORCOMSEG10','CORCOMSEG11','CORCOMSEG13','CORCOMSEG15','CORCOMSEG30','CORCOMSEG31','CORCOMSEG32','CORCOMSEG33','CORCOMSEG34','CORCOMSEG42','CORCOMSEG45','CORCOMSEG160','CORCOMSEG2','CORCOMSEG3','CORCOMSEG4','CORCOMSEG5','CORCOMSEG6','CORCOMSEG7','CORCOMSEG8','CORCOMSEG9','CORCOMSEG12','CORCOMSEG14','CORCOMSEG16','CORCOMSEG17','CORCOMSEG18','CORCOMSEG19','CORCOMSEG20','CORCOMSEG21','CORCOMSEG22','CORCOMSEG23','CORCOMSEG24','CORCOMSEG25','CORCOMSEG26','CORCOMSEG27','CORCOMSEG28','CORCOMSEG29','CORCOMSEG35','CORCOMSEG36','CORCOMSEG37','CORCOMSEG38','CORCOMSEG39','CORCOMSEG40','CORCOMSEG114','CORCOMSEG43','CORCOMSEG150','CORCOMSEG151','EDSANCHEZ','CORCOMSEG46'))
             THEN 'MANUAL SEGUIMIENTO'
        WHEN REGEXP_CONTAINS(TRIM(USUARIO), r'^\d{5}') THEN 'DIRECTA'
        WHEN USUARIO LIKE '%Valuador%' OR USUARIO IS NULL THEN
            CASE WHEN CODPROVEEDOR = '81111' THEN 'DIRECTA 81111' ELSE 'DIRECTA' END
        ELSE 'SIN ASIGNACION'
    END AS TIPOASIGNACION1,
    
    -- AREAASIGNACION
    CASE 
        WHEN USUARIO = 'AUT' THEN 'COTIZADOR'
        WHEN UPPER(USUARIO) LIKE '%ADMINREFC%' 
             OR USUARIO LIKE '%KAGONZALEZ%' 
             OR USUARIO LIKE '%PERUIZ%' 
             OR USUARIO LIKE '%PRUIZ%' 
             OR USUARIO LIKE '%KGONZALEZ%' 
             OR UPPER(USUARIO) LIKE 'ASR_COMP%' 
             OR UPPER(USUARIO) LIKE '%EDSANCHEZ%' 
             OR UPPER(USUARIO) LIKE '%JOVAZQUEZ%' 
             OR UPPER(USUARIO) IN ('CORCOMSEG1','CORCOMSEG10','CORCOMSEG11','CORCOMSEG13','CORCOMSEG15','CORCOMSEG30','CORCOMSEG31','CORCOMSEG32','CORCOMSEG33','CORCOMSEG34','CORCOMSEG42','CORCOMSEG45','CORCOMSEG160','CORCOMSEG2','CORCOMSEG3','CORCOMSEG4','CORCOMSEG5','CORCOMSEG6','CORCOMSEG7','CORCOMSEG8','CORCOMSEG9','CORCOMSEG12','CORCOMSEG14','CORCOMSEG16','CORCOMSEG17','CORCOMSEG18','CORCOMSEG19','CORCOMSEG20','CORCOMSEG21','CORCOMSEG22','CORCOMSEG23','CORCOMSEG24','CORCOMSEG25','CORCOMSEG26','CORCOMSEG27','CORCOMSEG28','CORCOMSEG29','CORCOMSEG35','CORCOMSEG36','CORCOMSEG37','CORCOMSEG38','CORCOMSEG39','CORCOMSEG40','CORCOMSEG114','CORCOMSEG43','CORCOMSEG150','CORCOMSEG151','EDSANCHEZ','CORCOMSEG46') 
             THEN 'COMPRAS'
        WHEN UPPER(USUARIO) LIKE 'ASR%' 
             OR UPPER(USUARIO) LIKE '%SUPSEG%' 
             OR UPPER(USUARIO) LIKE 'SV_____%' 
             OR UPPER(USUARIO) LIKE '%OTOLEDO%' 
             OR (UPPER(USUARIO) LIKE 'CORCOMSEG%' AND UPPER(USUARIO) NOT IN ('CORCOMSEG10','CORCOMSEG11','CORCOMSEG13','CORCOMSEG15','CORCOMSEG30','CORCOMSEG31','CORCOMSEG32','CORCOMSEG33','CORCOMSEG34','CORCOMSEG42','CORCOMSEG45','CORCOMSEG160','CORCOMSEG2','CORCOMSEG3','CORCOMSEG4','CORCOMSEG5','CORCOMSEG6','CORCOMSEG7','CORCOMSEG8','CORCOMSEG9','CORCOMSEG12','CORCOMSEG14','CORCOMSEG16','CORCOMSEG17','CORCOMSEG18','CORCOMSEG19','CORCOMSEG20','CORCOMSEG21','CORCOMSEG22','CORCOMSEG23','CORCOMSEG24','CORCOMSEG25','CORCOMSEG26','CORCOMSEG27','CORCOMSEG28','CORCOMSEG29','CORCOMSEG35','CORCOMSEG36','CORCOMSEG37','CORCOMSEG38','CORCOMSEG39','CORCOMSEG40','CORCOMSEG114','CORCOMSEG43','CORCOMSEG150','CORCOMSEG151','EDSANCHEZ','CORCOMSEG46'))
             THEN 'SEGUIMIENTO'
        WHEN USUARIO LIKE '%Valuador%' OR REGEXP_CONTAINS(TRIM(USUARIO), r'^\d{5}') OR USUARIO IS NULL THEN 'VALUACIÓN'
        ELSE ''
    END AS AREAASIGNACION,
    
    -- AUTOMATICO
    CASE WHEN USUARIO = 'AUT' THEN 1 ELSE 0 END AS AUTOMATICO,
    
    -- MANUAL_CON_ALERTA
    CASE WHEN USUARIO LIKE '%AUT /%' THEN 1 ELSE 0 END AS MANUAL_CON_ALERTA,
    
    -- MANUAL_COMPRAS
    CASE WHEN UPPER(USUARIO) LIKE '%ADMINREFC%' 
              OR USUARIO LIKE '%KAGONZALEZ%' 
              OR USUARIO LIKE '%PERUIZ%' 
              OR USUARIO LIKE '%PRUIZ%' 
              OR USUARIO LIKE '%KGONZALEZ%' 
              OR UPPER(USUARIO) LIKE 'ASR_COMP%' 
              OR UPPER(USUARIO) IN ('CORCOMSEG1','CORCOMSEG10','CORCOMSEG11','CORCOMSEG13','CORCOMSEG15','CORCOMSEG30','CORCOMSEG31','CORCOMSEG32','CORCOMSEG33','CORCOMSEG34','CORCOMSEG42','CORCOMSEG45','CORCOMSEG160','CORCOMSEG2','CORCOMSEG3','CORCOMSEG4','CORCOMSEG5','CORCOMSEG6','CORCOMSEG7','CORCOMSEG8','CORCOMSEG9','CORCOMSEG12','CORCOMSEG14','CORCOMSEG16','CORCOMSEG17','CORCOMSEG18','CORCOMSEG19','CORCOMSEG20','CORCOMSEG21','CORCOMSEG22','CORCOMSEG23','CORCOMSEG24','CORCOMSEG25','CORCOMSEG26','CORCOMSEG27','CORCOMSEG28','CORCOMSEG29','CORCOMSEG35','CORCOMSEG36','CORCOMSEG37','CORCOMSEG38','CORCOMSEG39','CORCOMSEG40','CORCOMSEG114','CORCOMSEG43','CORCOMSEG150','CORCOMSEG151','EDSANCHEZ','CORCOMSEG46')
         THEN 1 ELSE 0 END AS MANUAL_COMPRAS,
    
    -- MANUAL_SEGUIMIENTO
    CASE WHEN (UPPER(USUARIO) LIKE 'ASR%' AND NOT UPPER(USUARIO) LIKE 'ASR_COMP%') 
              OR UPPER(USUARIO) LIKE '%SUPSEG%' 
              OR UPPER(USUARIO) LIKE 'SV_____%' 
              OR UPPER(USUARIO) LIKE '%OTOLEDO%' 
              OR (UPPER(USUARIO) LIKE 'CORCOMSEG%' AND UPPER(USUARIO) NOT IN ('CORCOMSEG10','CORCOMSEG11','CORCOMSEG13','CORCOMSEG15','CORCOMSEG30','CORCOMSEG31','CORCOMSEG32','CORCOMSEG33','CORCOMSEG34','CORCOMSEG42','CORCOMSEG45','CORCOMSEG160','CORCOMSEG2','CORCOMSEG3','CORCOMSEG4','CORCOMSEG5','CORCOMSEG6','CORCOMSEG7','CORCOMSEG8','CORCOMSEG9','CORCOMSEG12','CORCOMSEG14','CORCOMSEG16','CORCOMSEG17','CORCOMSEG18','CORCOMSEG19','CORCOMSEG20','CORCOMSEG21','CORCOMSEG22','CORCOMSEG23','CORCOMSEG24','CORCOMSEG25','CORCOMSEG26','CORCOMSEG27','CORCOMSEG28','CORCOMSEG29','CORCOMSEG35','CORCOMSEG36','CORCOMSEG37','CORCOMSEG38','CORCOMSEG39','CORCOMSEG40','CORCOMSEG114','CORCOMSEG43','CORCOMSEG150','CORCOMSEG151','EDSANCHEZ','CORCOMSEG46'))
         THEN 1 ELSE 0 END AS MANUAL_SEGUIMIENTO,
    
    -- DIRECTA
    CASE WHEN UPPER(USUARIO) LIKE '%VALUADOR%' 
              OR USUARIO IS NULL 
              OR REGEXP_CONTAINS(TRIM(USUARIO), r'^\d{5}')
         THEN 1 ELSE 0 END AS DIRECTA,
    
    -- PIEZAAUTOSURTIDO
    CASE WHEN CODPROVEEDOR = CLAVETALLER THEN 1 ELSE 0 END AS PIEZAAUTOSURTIDO

FROM `STG_PREVENCION_FRAUDES.UNION_01`;



