

-- ================================================================================
-- FASE 5: PRIMER CONCENTRADO
-- ================================================================================

-- Concentrado inicial - OPTIMIZADO: Dividido en pasos más pequeños
-- Paso 1: Base con expedientes y datos generales
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CONCENTRADO_1_PASO1` AS
SELECT 
    t1.IDEXPEDIENTE,
    t1.MIN_of_FECHAAUTORIZACIONVALUADOR,
    t3.EJERCICIO,
    t3.NUMREPORTE,
    t3.NUMSINIESTRO,
    t3.CLAVETALLER,
    t3.CODVALUADOR,
    t3.IDVALUACION
FROM `STG_PREVENCION_FRAUDES.QUERY_FOR_ENVIOHISTORICO` t1
LEFT JOIN `STG_PREVENCION_FRAUDES.DE_DATOSGENERALES` t3 ON t1.IDEXPEDIENTE = t3.IDEXPEDIENTE;

-- Paso 2: Agregar información de expediente
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CONCENTRADO_1_PASO2` AS
SELECT 
    t1.*,
    SUBSTR(t2.NUMEXPEDIENTE, 1, 14) AS NUMVALUACION
FROM `STG_PREVENCION_FRAUDES.CONCENTRADO_1_PASO1` t1
LEFT JOIN `LAN_VERIFICACIONES.EXPEDIENTE` t2 ON CAST(t1.IDEXPEDIENTE AS NUMERIC) = t2.IDEXPEDIENTE;

-- Paso 3: Agregar información de valuación
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CONCENTRADO_1_PASO3` AS
SELECT 
    t1.*,
    REGEXP_REPLACE(t4.DESCRIPCION, r'[^a-zA-Z0-9\s]', '') AS ESTATUSVALUACION
FROM `STG_PREVENCION_FRAUDES.CONCENTRADO_1_PASO2` t1
LEFT JOIN `STG_PREVENCION_FRAUDES.DE_VALUACION` t4 ON t1.IDVALUACION = t4.IDVALUACION;

-- Paso 4: Agregar información de talleres
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CONCENTRADO_1_PASO4` AS
SELECT 
    t1.*,
    SUBSTR(t5.NOMBRECOMERCIAL, 7) AS NOMBRECDR,
    t5.TIPOCDR_PORTAL,
    t5.CDRCOTIZADOR,
    t5.CDRAUTOSURTIDO,
    t5.CERCO_ANTERIOR,
    t5.IDTALLER,
    t5.IDENTIDAD,
    t5.IDOFICINA,
    t5.IDESTADO
FROM `STG_PREVENCION_FRAUDES.CONCENTRADO_1_PASO3` t1
LEFT JOIN `STG_PREVENCION_FRAUDES.TAB_TALLERES` t5 ON t1.CLAVETALLER = t5.CLAVETALLER;

-- Paso 5: Agregar fechas - CONCENTRADO_1 FINAL
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CONCENTRADO_1` AS
SELECT 
    t1.*,
    t6.FECVALUACION,
    t6.FECTERMINADO,
    t6.FECENTREGADO
FROM `STG_PREVENCION_FRAUDES.CONCENTRADO_1_PASO4` t1
LEFT JOIN `STG_PREVENCION_FRAUDES.DE_FECHAS` t6 ON t1.IDEXPEDIENTE = t6.IDEXPEDIENTE;

-- Concentrado con estatus del expediente - OPTIMIZADO: Dividido en pasos
-- Paso 1: Base del concentrado
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CON_STATUS_EXP_PASO1` AS
SELECT 
    t1.IDEXPEDIENTE,
    t1.NUMVALUACION,
    t1.MIN_of_FECHAAUTORIZACIONVALUADOR,
    t1.EJERCICIO,
    t1.NUMREPORTE,
    t1.NUMSINIESTRO,
    t1.ESTATUSVALUACION,
    t1.CLAVETALLER,
    t1.NOMBRECDR,
    t1.TIPOCDR_PORTAL,
    t1.CERCO_ANTERIOR,
    t1.CODVALUADOR,
    t1.FECVALUACION,
    t1.FECTERMINADO,
    t1.FECENTREGADO,
    t1.IDVALUACION,
    t1.CDRCOTIZADOR,
    t1.CDRAUTOSURTIDO,
    t1.IDESTADO,
    t1.IDENTIDAD
FROM `STG_PREVENCION_FRAUDES.CONCENTRADO_1` t1;

-- Paso 2: Agregar estatus del expediente
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CON_STATUS_EXP_PASO2` AS
SELECT 
    t1.*,
    t2.ESTATUSEXPEDIENTE
FROM `STG_PREVENCION_FRAUDES.CON_STATUS_EXP_PASO1` t1
LEFT JOIN `STG_PREVENCION_FRAUDES.ESTATUS_DEL_EXPEDIENTE` t2 ON t1.IDEXPEDIENTE = t2.IDEXPEDIENTE;

-- Paso 3: Agregar información del cerco
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CON_STATUS_EXP_PASO3` AS
SELECT 
    t1.*,
    t3.NOMBRE AS CERCO
FROM `STG_PREVENCION_FRAUDES.CON_STATUS_EXP_PASO2` t1
LEFT JOIN `STG_PREVENCION_FRAUDES.DE_CERCO` t3 ON t1.IDENTIDAD = t3.IDENTIDAD;

-- Paso 4: Agregar datos del vehículo
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CON_STATUS_EXP_PASO4` AS
SELECT 
    t1.*,
    t4.MARCAVEHICULO,
    t4.TIPOVEHICULO,
    t4.MODELO,
    t4.SERIE
FROM `STG_PREVENCION_FRAUDES.CON_STATUS_EXP_PASO3` t1
LEFT JOIN `STG_PREVENCION_FRAUDES.DATOS_DEL_VEH_CON_MARCA` t4 ON t1.IDEXPEDIENTE = t4.IDEXPEDIENTE;

-- Paso 5: Agregar categoría valuador - CON_STATUS_EXP_CONCENTRADO_1 FINAL
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CON_STATUS_EXP_CONCENTRADO_1` AS
SELECT 
    t1.*,
    t5.TIPOVALUADOR,
    t5.CATEGORIAVALUADOR
FROM `STG_PREVENCION_FRAUDES.CON_STATUS_EXP_PASO4` t1
LEFT JOIN `STG_PREVENCION_FRAUDES.CATEGORIA_VALUADOR` t5 ON t1.CODVALUADOR = t5.CODVALUADOR;

-- Concentrado final con gerencias - OPTIMIZADO: Dividido en pasos pequeños
-- Paso 1: Base del concentrado con información básica
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CONCENTRADO_PASO1` AS
SELECT 
    t1.IDEXPEDIENTE,
    t1.NUMVALUACION,
    t1.MIN_of_FECHAAUTORIZACIONVALUADOR,
    t1.EJERCICIO,
    t1.NUMREPORTE,
    t1.NUMSINIESTRO,
    t1.ESTATUSEXPEDIENTE,
    t1.ESTATUSVALUACION,
    t1.MARCAVEHICULO,
    t1.TIPOVEHICULO,
    t1.MODELO,
    t1.SERIE,
    t1.CLAVETALLER,
    t1.NOMBRECDR,
    t1.TIPOCDR_PORTAL,
    t1.CERCO,
    t1.CERCO_ANTERIOR,
    t1.CODVALUADOR,
    t1.FECVALUACION,
    t1.FECTERMINADO,
    t1.FECENTREGADO,
    t1.TIPOVALUADOR,
    t1.CATEGORIAVALUADOR,
    t1.IDVALUACION,
    t1.CDRCOTIZADOR,
    t1.CDRAUTOSURTIDO,
    t1.IDESTADO
FROM `STG_PREVENCION_FRAUDES.CON_STATUS_EXP_CONCENTRADO_1` t1;

-- Paso 2: Agregar información de región geográfica
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CONCENTRADO_PASO2` AS
SELECT 
    t1.*,
    t2.IDREGIONGEOGRAFICA
FROM `STG_PREVENCION_FRAUDES.CONCENTRADO_PASO1` t1
LEFT JOIN `STG_PREVENCION_FRAUDES.DE_ESTADO` t2 ON t1.IDESTADO = t2.IDESTADO;

-- Paso 3: Calcular gerencia de valuación
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CONCENTRADO_PASO3` AS
SELECT 
    t1.*,
    CASE
        WHEN CAST(t1.IDREGIONGEOGRAFICA AS INT64) IN (1,2,9,11) THEN 'NORTE'
        WHEN CAST(t1.IDREGIONGEOGRAFICA AS INT64) IN (4,5,7,10) THEN 'CENTRO'
        WHEN CAST(t1.IDREGIONGEOGRAFICA AS INT64) IN (3,6,8,12) THEN 'OCCIDENTE'
        ELSE 'SIN GERENCIA'
    END AS GERENCIAVALUACION,
    CASE WHEN t1.FECTERMINADO IS NOT NULL THEN 1 ELSE 0 END AS VEHICULOTERMINADO
FROM `STG_PREVENCION_FRAUDES.CONCENTRADO_PASO2` t1;

-- Paso 4: Agregar información de prestadores - CONCENTRADO FINAL
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.CONCENTRADO` AS
SELECT 
    t1.IDEXPEDIENTE,
    t1.NUMVALUACION,
    t1.MIN_of_FECHAAUTORIZACIONVALUADOR,
    t1.EJERCICIO,
    t1.NUMREPORTE,
    t1.NUMSINIESTRO,
    t1.ESTATUSEXPEDIENTE,
    t1.ESTATUSVALUACION,
    t1.MARCAVEHICULO,
    t1.TIPOVEHICULO,
    t1.MODELO,
    t1.SERIE,
    t1.CLAVETALLER,
    t1.NOMBRECDR,
    t3.tipo_proveedor AS TIPOCDR_SISE,
    t3.Marca AS MARCACDR_SISE,
    t1.TIPOCDR_PORTAL,
    t3.Pob_Comer AS POBCOMERCDR,
    t1.IDREGIONGEOGRAFICA,
    t1.CDRCOTIZADOR,
    t1.CDRAUTOSURTIDO,
    t1.GERENCIAVALUACION,
    t1.CERCO,
    t1.CERCO_ANTERIOR,
    t1.CODVALUADOR,
    t1.FECVALUACION,
    t1.FECTERMINADO,
    t1.FECENTREGADO,
    t1.VEHICULOTERMINADO,
    t1.TIPOVALUADOR,
    t1.CATEGORIAVALUADOR
FROM `STG_PREVENCION_FRAUDES.CONCENTRADO_PASO3` t1
LEFT JOIN `STG_PREVENCION_FRAUDES.PRESTADORES_POB_COMER_TIPO` t3 ON t1.CLAVETALLER = t3.Id;

-- Concentrado con analista CDR
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.ENVIOHISTORICO_CN_ANALISTACDR` AS
SELECT 
    t1.IDEXPEDIENTE,
    t1.NUMVALUACION,
    t1.MIN_of_FECHAAUTORIZACIONVALUADOR,
    t1.EJERCICIO,
    t1.NUMREPORTE,
    t1.NUMSINIESTRO,
    t1.ESTATUSEXPEDIENTE,
    t1.ESTATUSVALUACION,
    t1.MARCAVEHICULO,
    t1.TIPOVEHICULO,
    t1.MODELO,
    t1.SERIE,
    t1.CLAVETALLER,
    t1.NOMBRECDR,
    t1.TIPOCDR_SISE,
    t1.MARCACDR_SISE,
    t1.TIPOCDR_PORTAL,
    t1.POBCOMERCDR,
    t1.IDREGIONGEOGRAFICA,
    t1.CDRCOTIZADOR,
    t1.CDRAUTOSURTIDO,
    t1.GERENCIAVALUACION,
    t1.CERCO,
    t1.CERCO_ANTERIOR,
    t1.CODVALUADOR,
    t1.FECVALUACION,
    t1.FECTERMINADO,
    t1.FECENTREGADO,
    t1.VEHICULOTERMINADO,
    t1.TIPOVALUADOR,
    t1.CATEGORIAVALUADOR,
    t2.ANALISTACDR
FROM `STG_PREVENCION_FRAUDES.CONCENTRADO` t1
LEFT JOIN `STG_PREVENCION_FRAUDES.ANALISTA_CDR` t2 ON t1.CLAVETALLER = t2.CLAVETALLER;
