
-- ================================================================================
-- FASE 6: PROCESAMIENTO DE VALES Y PIEZAS
-- ================================================================================

-- Cruce de vales con proveedores
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.QUERY_FOR_ENVIOHISTORICO_0001` AS
SELECT 
    t2.IDEXPEDIENTE,
    t2.IDVALE,
    t2.CODPROVEEDOR,
    t4.NOMBREPROVEEDOR,
    t4.TIPOPROVEEDOR_PORTAL,
    t4.TIPOTOT,
    t4.POBCOMERCIALPROVEEDOR,
    t4.TIPOPROVEEDOR_SISE,
    t4.MARCAPROVEEDOR_SISE,
    t2.FOLIO,
    t2.FECHAEXPEDICION,
    t2.FECHAACTUALIZACION,
    t3.DESCRIPCION AS ESTATUSVALE,
    t2.AUTORIZADOR
FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.QUERY_FOR_ENVIOHISTORICO` t1
INNER JOIN `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.DE_VISTA_VALE` t2 ON t1.IDEXPEDIENTE = t2.IDEXPEDIENTE
LEFT JOIN `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.DE_VALEESTATUS` t3 ON t2.IDVALEESTATUS = t3.IDVALEESTATUS
LEFT JOIN `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.QUERY_FOR_PROVEEDOR` t4 ON t2.CODPROVEEDOR = t4.CODPROVEEDOR;

-- Cruce con histórico de vales
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.QUERY_FOR_ENVIOHISTORICO1` AS
SELECT 
    t1.IDEXPEDIENTE,
    t2.IDVALEHISTORICO,
    t1.IDVALE,
    t1.CODPROVEEDOR,
    t1.NOMBREPROVEEDOR,
    t1.TIPOPROVEEDOR_PORTAL,
    t1.TIPOTOT,
    t1.POBCOMERCIALPROVEEDOR,
    t1.TIPOPROVEEDOR_SISE,
    t1.MARCAPROVEEDOR_SISE,
    t1.FOLIO,
    t2.NUMPARTE,
    t2.REFERENCIA,
    t2.DESCRIPCION AS DESCRIPCIONREFACCION,
    t2.MONTO,
    t2.IDCOSTO,
    t2.TIPO,
    t1.FECHAEXPEDICION,
    t2.FECENVIO,
    t2.FECENTREGAREFACCIONARIA,
    t2.FECRECEPCION,
    t2.FECSURTIDO AS FECPROMESAENTREGA,
    t1.FECHAACTUALIZACION,
    t2.USUARIO,
    t1.AUTORIZADOR,
    t1.ESTATUSVALE,
    t2.IDCAUSACAMBIOVALE,
    CASE
        WHEN t2.IDREFACCION = '01' THEN 'ORIGINAL'
        WHEN t2.IDREFACCION = '02' THEN 'ORIG. USADO'
        WHEN t2.IDREFACCION = '03' THEN 'ALTERNATIVO'
        WHEN t2.IDREFACCION = '04' THEN 'TOT'
        WHEN t2.IDREFACCION = '05' THEN 'NACIONAL'
        WHEN t2.IDREFACCION = '06' THEN 'DESMONTADO'
        WHEN t2.IDREFACCION = '07' THEN 'REMANUFACTURADO'
        WHEN t2.IDREFACCION IS NULL THEN 'SIN ORIGEN'
    END AS ORIGEN,
    t2.LLAVEPIEZA
FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.QUERY_FOR_ENVIOHISTORICO_0001` t1
LEFT JOIN `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.DE_VALEHISTORICO` t2 ON t1.IDVALE = t2.IDVALE
WHERE t2.IDCOSTO IS NOT NULL AND t1.FECHAEXPEDICION >= '2023-01-01 00:00:00';

CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.VALE_CAUSA_CAMBIO` AS
SELECT 
    t1.IDEXPEDIENTE,
    t1.IDVALEHISTORICO,
    t1.IDVALE,
    t1.CODPROVEEDOR,
    t1.NOMBREPROVEEDOR,
    t1.TIPOPROVEEDOR_PORTAL,
    t1.TIPOTOT,
    t1.POBCOMERCIALPROVEEDOR,
    t1.TIPOPROVEEDOR_SISE,
    t1.MARCAPROVEEDOR_SISE,
    t1.FOLIO,
    t1.NUMPARTE,
    t1.REFERENCIA,
    t1.DESCRIPCIONREFACCION,
    t1.MONTO,
    t1.IDCOSTO,
    t1.TIPO,
    t1.FECHAEXPEDICION,
    t1.FECENVIO,
    t1.FECENTREGAREFACCIONARIA,
    t1.FECRECEPCION,
    t1.FECPROMESAENTREGA,
    t1.FECHAACTUALIZACION,
    t1.USUARIO,
    t1.AUTORIZADOR,
    t1.ESTATUSVALE,
    t1.ORIGEN,
    t2.DESCRIPCION AS CAUSACAMBIOVALE
FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.QUERY_FOR_ENVIOHISTORICO1` t1
LEFT JOIN `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.DE_CAUSACAMBIOVALE` t2 ON t1.IDCAUSACAMBIOVALE = t2.IDCAUSACAMBIOVALE;

-- Cruce con tabla COSTO para tipo 'COSTO'
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.QUERY_FOR_ENVIOHISTORICO1_0003` AS
SELECT 
    t1.IDEXPEDIENTE,
    t1.IDVALEHISTORICO,
    t1.IDVALE,
    t1.CODPROVEEDOR,
    t1.NOMBREPROVEEDOR,
    t1.TIPOPROVEEDOR_PORTAL,
    t1.TIPOTOT,
    t1.POBCOMERCIALPROVEEDOR,
    t1.TIPOPROVEEDOR_SISE,
    t1.MARCAPROVEEDOR_SISE,
    t1.FOLIO,
    t1.NUMPARTE,
    t1.REFERENCIA,
    t1.DESCRIPCIONREFACCION,
    t1.MONTO,
    t1.IDCOSTO,
    t1.TIPO,
    t1.FECHAEXPEDICION,
    t1.FECENVIO,
    t1.FECENTREGAREFACCIONARIA,
    t1.FECRECEPCION,
    t1.FECPROMESAENTREGA,
    t1.FECHAACTUALIZACION,
    t1.USUARIO,
    t1.AUTORIZADOR,
    t1.ESTATUSVALE,
    t1.ORIGEN,
    t1.CAUSACAMBIOVALE,
    t2.LISTA,
    t2.BLINDAJE,
    t2.CLAVENAGS,
    t2.MONTOCONVENIO
FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.VALE_CAUSA_CAMBIO` t1
INNER JOIN `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.DE_COSTO` t2 ON t1.IDCOSTO = t2.IDCOSTO AND t1.TIPO = 'COSTO';

-- Cruce con tabla COMPLEMENTO para tipo 'COMPLEMENTO'
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.QUERY_FOR_ENVIOHISTORICO1_0004` AS
SELECT 
    t1.IDEXPEDIENTE,
    t1.IDVALEHISTORICO,
    t1.IDVALE,
    t1.CODPROVEEDOR,
    t1.NOMBREPROVEEDOR,
    t1.TIPOPROVEEDOR_PORTAL,
    t1.TIPOTOT,
    t1.POBCOMERCIALPROVEEDOR,
    t1.TIPOPROVEEDOR_SISE,
    t1.MARCAPROVEEDOR_SISE,
    t1.FOLIO,
    t1.NUMPARTE,
    t1.REFERENCIA,
    t1.DESCRIPCIONREFACCION,
    t1.MONTO,
    t1.IDCOSTO,
    t1.TIPO,
    t1.FECHAEXPEDICION,
    t1.FECENVIO,
    t1.FECENTREGAREFACCIONARIA,
    t1.FECRECEPCION,
    t1.FECPROMESAENTREGA,
    t1.FECHAACTUALIZACION,
    t1.USUARIO,
    t1.AUTORIZADOR,
    t1.ESTATUSVALE,
    t1.ORIGEN,
    t1.CAUSACAMBIOVALE,
    t2.LISTA,
    t2.BLINDAJE,
    t2.CLAVENAGS,
    t2.MONTOCONVENIO
FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.VALE_CAUSA_CAMBIO` t1
INNER JOIN `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.DE_COMPLEMENTO` t2 ON t1.IDCOSTO = t2.IDCOMPLEMENTO AND t1.TIPO = 'COMPLEMENTO';

-- Unión de COSTO y COMPLEMENTO
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.APPEND_TABLE` AS
SELECT * FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.QUERY_FOR_ENVIOHISTORICO1_0003`
UNION ALL
SELECT * FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.QUERY_FOR_ENVIOHISTORICO1_0004`;

