-- ================================================================================
-- TRADUCCIÓN DE SAS SQL A BIGQUERY SQL - TODAS LAS PIEZAS
-- Dataset origen: LAN_VERIFICACIONES
-- Dataset staging: STG_PREVENCION_FRAUDES  
-- Dataset final: DM_PREVENCION_FRAUDES
-- ================================================================================

-- ================================================================================
-- FASE 1: EXTRACCIÓN DE CATÁLOGOS
-- ================================================================================

-- Extracción de CAUSACAMBIOVALE
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_CAUSACAMBIOVALE` AS
SELECT 
    IDCAUSACAMBIOVALE,
    DESCRIPCION
FROM `LAN_VERIFICACIONES.CAUSACAMBIOVALE`;

-- Extracción de COSTO con el concepto igual a 'REF'
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_COSTO` AS
SELECT 
    CAST(IDCOSTO AS STRING) AS IDCOSTO,
    LISTA,
    BLINDAJE,
    CLAVENAGS,
    MONTOCONVENIO
FROM `LAN_VERIFICACIONES.COSTO`
WHERE CONCEPTO = 'REF';

-- Extracción de COMPLEMENTO con el concepto igual a 'REF'
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_COMPLEMENTO` AS
SELECT 
    IDCOMPLEMENTO,
    LISTA,
    BLINDAJE,
    CLAVENAGS,
    MONTOCONVENIO
FROM `LAN_VERIFICACIONES.COMPLEMENTO`
WHERE CONCEPTO = 'REF';

-- Extracción de VISTA_VALE
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_VISTA_VALE` AS
SELECT 
    CAST(IDEXPEDIENTE AS STRING) AS IDEXPEDIENTE,
    CAST(IDVALE AS STRING) AS IDVALE,
    CODPROVEEDOR,
    FOLIO,
    FECHAEXPEDICION,
    FECHAACTUALIZACION,
    AUTORIZADOR,
    IDVALEESTATUS
FROM `LAN_VERIFICACIONES.VISTA_VALE`;

-- Extracción de VALEESTATUS
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_VALEESTATUS` AS
SELECT 
    IDVALEESTATUS,
    DESCRIPCION
FROM `LAN_VERIFICACIONES.VALEESTATUS`;

-- Extracción de VALEHISTORICO y creación de LLAVEPIEZA
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_VALEHISTORICO` AS
SELECT 
    IDVALEHISTORICO,
    NUMPARTE,
    REFERENCIA,
    DESCRIPCION,
    MONTO,
    IDCOSTO,
    TIPO,
    FECENVIO,
    FECENTREGAREFACCIONARIA,
    FECRECEPCION,
    FECSURTIDO,
    USUARIO,
    IDREFACCION,
    IDCAUSACAMBIOVALE,
    IDVALE,
    -- LLAVEPIEZA
    CONCAT(IFNULL(NUMPARTE,''), IFNULL(REFERENCIA,''), IFNULL(DESCRIPCION,'')) AS LLAVEPIEZA
FROM `LAN_VERIFICACIONES.VALEHISTORICO`;

-- Extracción de RELACIONCDR_SICDR
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_RELACIONCDR_SICDR` AS
SELECT 
    CLAVETALLER,
    IDSICDR
FROM `LAN_VERIFICACIONES.RELACIONCDR_SICDR`;

-- Extracción de SUPERVISORINTEGRAL
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_SUPERVISORINTEGRAL` AS
SELECT 
    CLAVESUPERVISOR,
    NOMBRESUPERVISOR,
    IDREGIONGEOGRAFICA,
    IDSUPERVISORINTEGRAL
FROM `LAN_VERIFICACIONES.SUPERVISORINTEGRAL`;

-- Extracción de DATOSGENERALES
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_DATOSGENERALES` AS
SELECT 
    CAST(IDEXPEDIENTE AS STRING) AS IDEXPEDIENTE,
    EJERCICIO,
    NUMREPORTE,
    NUMSINIESTRO,
    CLAVETALLER,
    CODVALUADOR,
    IDVALUACION
FROM `LAN_VERIFICACIONES.DATOSGENERALES`;

-- Extracción de FECHAS
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_FECHAS` AS
SELECT 
    CAST(IDEXPEDIENTE AS STRING) AS IDEXPEDIENTE,
    FECVALUACION,
    FECTERMINADO,
    FECENTREGADO
FROM `LAN_VERIFICACIONES.FECHAS`;

-- Extracción de VALUACION
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_VALUACION` AS
SELECT 
    IDVALUACION,
    DESCRIPCION
FROM `LAN_VERIFICACIONES.VALUACION`;

-- Extracción de CERCO
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_CERCO` AS
SELECT 
    IDENTIDAD,
    NOMBRE
FROM `LAN_VERIFICACIONES.CERCO`
ORDER BY NOMBRE;

-- Extracción de ESTADO
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_ESTADO` AS
SELECT 
    CAST(IDREGIONGEOGRAFICA AS STRING) AS IDREGIONGEOGRAFICA,
    IDESTADO
FROM `LAN_VERIFICACIONES.ESTADO`;

-- Extracción de VALUADOR
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_VALUADOR` AS
SELECT 
    CODVALUADOR,
    IDCATEGORIA,
    EQUIPOPESADO
FROM `LAN_VERIFICACIONES.VALUADOR`;

-- Extracción de CATEGORIA
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_CATEGORIA` AS
SELECT 
    NOMBRE,
    IDCATEGORIA
FROM `LAN_VERIFICACIONES.CATEGORIA`;

-- Extracción de DATOSVEHICULO
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_DATOSVEHICULO` AS
SELECT 
    IDEXPEDIENTE,
    TIPO,
    MODELO,
    SERIE,
    IDMARCA
FROM `LAN_VERIFICACIONES.DATOSVEHICULO`;

-- Extracción de MARCA
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_MARCA` AS
SELECT 
    IDMARCA,
    DESCRIPCION
FROM `LAN_VERIFICACIONES.MARCA`;

-- Extracción de ESTATUS
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_ESTATUS` AS
SELECT 
    IDEXPEDIENTE,
    IDESTATUSEXPEDIENTE
FROM `LAN_VERIFICACIONES.ESTATUS`;

-- Extracción de ESTATUSEXPEDIENTES
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_ESTATUSEXPEDIENTES` AS
SELECT 
    IDESTATUSEXPEDIENTE,
    DESCRIPCION
FROM `LAN_VERIFICACIONES.ESTATUSEXPEDIENTES`;

-- Extracción de TALLERES
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_TALLERES` AS
SELECT 
    IDTALLER,
    IDOFICINA,
    CLAVETALLER,
    NOMBRECOMERCIAL,
    IDENTIDAD,
    TIPO AS TIPOCDR_PORTAL,
    COTIZADOR AS CDRCOTIZADOR,
    FRONTERIZO AS CDRAUTOSURTIDO,
    IDESTADO
FROM `LAN_VERIFICACIONES.TALLERES`;

-- Extracción de PROVEEDOR
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_PROVEEDOR` AS
SELECT 
    CODPROVEEDOR,
    NOMBRE AS NOMBREPROVEEDOR,
    TIPO AS TIPOPROVEEDOR_PORTAL,
    IDTIPOTOT
FROM `LAN_VERIFICACIONES.PROVEEDOR`;

-- Extracción de TIPOTOT
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.DE_TIPOTOT` AS
SELECT 
    IDTIPOTOT,
    DESCRIPCION AS TIPOTOT
FROM `LAN_VERIFICACIONES.TIPOTOT`;

-- Extracción de Prestadores (BSC_SINI)
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.ID_PRESTADORES_MARCA` AS
SELECT 
    Id,
    Marca,
    Status,
    Tipo,
    POBCOMER
FROM `LAN_VERIFICACIONES.PRESTADORES`;

-- Extracción de TESTADO_BSC
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.POB_COMER` AS
SELECT 
    Z_ID,
    EDOPOB
FROM `LAN_VERIFICACIONES.TESTADO_BSC`;

-- Extracción de tipoProveedor
CREATE OR REPLACE TABLE `STG_PREVENCION_FRAUDES.ID_TIPOPROVEEDOR` AS
SELECT 
    id,
    tipo_proveedor
FROM `LAN_VERIFICACIONES.TIPOPROVEEDOR`;
