TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`;
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`
SELECT 
  ID, 
  NOMBRE,
  MARCA,
  TIPO,
  OFICINA,
  SUSPENCION,
  STATUS,
  Fbaja,
  CodEstado,
  POBLACION,
  DIRECCION,
  Dir_Comer,
  Col_Comer,
  Pob_Comer,
  Edo_Comer,
  Num_Docto,
  Nom_Comer,
  GRUPO,
  FEC_ALTA,
  CTA_ESP, 
  TIPO_AJUS,
  MARCA_TIPO,
  RFC,
  CORREO_COMERCIAL,
  CORREO_CONTACTO,
  Correo_Comercial2,
  MARCA_MOTOS,
  TEL_SIICA,
  AE, 
  LATITUD,
  LONGITUD,
  RECIBE24,
  ZONAPROV,
  VED, 
  TIPO_PERSONA,
  CEXP, 
  TBODY, 
  NUM_EMPL,
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`
WHERE RN = 1;