CREATE OR REPLACE TABLE `DM_FRAUDES.DM_PAGOS_POLIZAS` AS

(WITH RP AS (
  SELECT RECIBO
, FEC_VTO
, POLIZA
, ENDOSO
, IMPORTE
, REMESA
, MARCA_IMP
, MARCA_ANUL
, PRIMA_NETA
, DER_POL
, REC_FIN
, IVA
, BONIFICACION
, BONIF_RF
, BONIF_TEC
, PRIMA_TOTAL
, USU_APLICA
, FEC_APLICACION
, HORA_APLICA
, IMPRESION
, RFC_FACT
, USUARIO_EMITE
, FECHA_PROCESO
, FECHA_CARGA
, ROW_NUMBER() OVER (PARTITION BY RECIBO ORDER BY FEC_APLICACION DESC) AS RN
FROM qualitasfraude.sample_landing_sise.fraud_rp)

SELECT DISTINCT
  RECIBO AS ID
  ,CAST(CONCAT(SUBSTRING(FEC_VTO,7,4),'-',SUBSTRING(FEC_VTO,4,2),'-',SUBSTRING(FEC_VTO,1,2)) AS DATETIME) AS FECHA_VENCIMIENTO
  ,POLIZA
  ,ENDOSO
  ,CONCAT(POLIZA,ENDOSO) AS POLIZA_ENDOSO
  ,SAFE_CAST(IMPORTE AS NUMERIC) AS IMPORTE
  ,REMESA
  ,CAST(CONCAT(SUBSTRING(MARCA_IMP,7,4),'-',SUBSTRING(MARCA_IMP,4,2),'-',SUBSTRING(MARCA_IMP,1,2)) AS DATETIME) AS MARCA_IMP
  ,CAST(CONCAT(SUBSTRING(MARCA_ANUL,7,4),'-',SUBSTRING(MARCA_ANUL,4,2),'-',SUBSTRING(MARCA_ANUL,1,2)) AS DATETIME) AS MARCA_ANUL
  ,SAFE_CAST(PRIMA_NETA AS NUMERIC) AS PRIMA_NETA
  ,SAFE_CAST(DER_POL AS NUMERIC) AS DERECHO_POLIZA
  ,SAFE_CAST(REC_FIN AS NUMERIC) AS RECIBO_FIN
  ,SAFE_CAST(IVA AS NUMERIC) AS IVA
  ,SAFE_CAST(BONIFICACION AS NUMERIC) AS BONIFICACION
  ,SAFE_CAST(BONIF_RF AS NUMERIC) AS BONIFICACION_RF
  ,SAFE_CAST(BONIF_TEC AS NUMERIC) AS BONIFICACION_TEC
  ,SAFE_CAST(PRIMA_TOTAL AS NUMERIC) AS PRIMA_TOTAL
  ,USU_APLICA AS USUARIO_APLICA
  ,CAST(CONCAT(SUBSTRING(FEC_APLICACION,7,4),'-',SUBSTRING(FEC_APLICACION,4,2),'-',SUBSTRING(FEC_APLICACION,1,2),' ',HORA_APLICA) AS DATETIME) AS FECHA_APLICACION
  ,SUBSTRING(RFC_FACT,0,13) AS RFC_FACTURACION
  ,USUARIO_EMITE
  ,CASE 
    WHEN REMESA IS NULL AND MARCA_ANUL IS NULL THEN 'PENDIENTE'
    WHEN REMESA IS NOT NULL AND MARCA_ANUL IS NULL THEN 'PAGADO'
    WHEN REMESA IS NOT NULL AND MARCA_ANUL IS NOT NULL THEN 'CANCELADO'
    ELSE 'PENDIENTE'
  END AS STATUS
  ,CAST(CURRENT_TIMESTAMP() AS DATETIME) AS FECHA_PROCESO
  ,FECHA_CARGA
FROM RP
WHERE LENGTH(FEC_VTO) = 10
AND RN = 1)