TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`;
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`
SELECT 
  RECIBO
  , FEC_VTO
  , POLIZA
  , ENDOSO
  , IMPORTE
  , REMESA
  , MARCA_IMP
  , MARCA_ANUL
  , PRIMA_NETA
  , DER_POL
  , REC_FIN
  , IVA
  , BONIFICACION
  , BONIF_RF
  , BONIF_TEC
  , PRIMA_TOTAL
  , USU_APLICA
  , FEC_APLICACION
  , HORA_APLICA
  , IMPRESION
  , RFC_FACT
  , USUARIO_EMITE
  , FECHA_PROCESO
  , FECHA_CARGA
  , ROW_NUMBER() OVER (PARTITION BY RECIBO ORDER BY FEC_APLICACION DESC) AS RN
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`
WHERE LENGTH(FEC_VTO) = 10;
