TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`;
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`
SELECT 
  Z_ID AS ID,
  OFICINA,
  DIRECCION,
  COLONIA,
  POBLACION,
  EDOPOB AS CODIGO_POBLACION,
  CP AS CODIGO_POSTAL,
  ZONA
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`
WHERE Z_ID <> '990'
ORDER BY Z_ID;