CREATE OR REPLACE TABLE `DM_FRAUDES.DM_REGISTRO`  AS
SELECT 
SINIESTRO,
ID_OF AS ID_OFICINA,
DESC_OF as DESCRIPCION_OFICINA,
USUARIO,
NOMBRE,
CORREO,
MOTIVO,
OBSERVACIONES,
DOC_ADICIONAL as DOCUMENTO_ADICIONAL,
SIN_SNA AS SINIESTRO_ALERTADO,
ID_ANALISTA,
FECHA_ASIG AS FECHA_ASIGNACION,
AREA,
PUESTO,
ID_MOTIVO,
MARCA,
MONTO_ESTIMADO,
BATCHDATE AS FECHA_LOTE,
SYSUSERID AS ID_USUARIO_SISTEMA
FROM `qualitasfraude.sample_landing_siniestros.registro`