TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`;
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`
SELECT 
  ID_SINIESTRO,
  ID_OFICINA,
  DESCRIPCION_OFICINA,
  USUARIO,
  NOMBRE,
  CORREO,
  MOTIVO,
  OBSERVACIONES,
  DOCUMENTO_ADICIONAL,
  SINIESTRO_ALERTADO,
  ID_ANALISTA,
  FECHA_ASIGNACION,
  AREA,
  PUESTO,
  ID_MOTIVO,
  MARCA,
  MONTO_ESTIMADO,
  FECHA_LOTE,
  ID_USUARIO_SISTEMA
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`
WHERE ROW_NUM = 1;