TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`;
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`
SELECT 
  SINIESTRO AS ID_SINIESTRO,
  ID_OF AS ID_OFICINA,
  DESC_OF as DESCRIPCION_OFICINA,
  USUARIO,
  NOMBRE,
  CORREO,
  MOTIVO,
  OBSERVACIONES,
  DOC_ADICIONAL AS DOCUMENTO_ADICIONAL,
  SIN_SNA AS SINIESTRO_ALERTADO,
  ID_ANALISTA,
  FECHA_ASIG AS FECHA_ASIGNACION,
  AREA,
  PUESTO,
  ID_MOTIVO,
  MARCA,
  MONTO_ESTIMADO,
  BATCHDATE AS FECHA_LOTE,
  SYSUSERID AS ID_USUARIO_SISTEMA,
  ROW_NUMBER() OVER (PARTITION BY SINIESTRO ORDER BY FECHA_ASIG DESC) AS ROW_NUM
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`;