CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.DM_CONTROL_FRAUDES.DM_PRODUCCION2` AS

SELECT 
  -- 1. RAMO
  SAFE_CAST(SAFE_CAST(NULLIF(RAMO, '') AS FLOAT64) AS INT64) AS RAMO,
  
  -- 2. POLIZA
  SAFE_CAST(SAFE_CAST(NULLIF(POLIZA, '') AS FLOAT64) AS INT64) AS POLIZA,
  
  -- 3. ENDOSO
  SAFE_CAST(SAFE_CAST(NULLIF(ENDOSO, '') AS FLOAT64) AS INT64) AS ENDOSO,
  
  -- 4. INC
  SAFE_CAST(SAFE_CAST(NULLIF(INC, '') AS FLOAT64) AS INT64) AS INC,
  
  -- 5. FEC_EMI (fecha Oracle formato ddMMMyyyy:hh:mm:ss)
  CASE 
    WHEN FEC_EMI IS NOT NULL AND FEC_EMI != '' 
    THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', FEC_EMI)
    ELSE NULL 
  END AS FEC_EMI,
  
  -- 6. INI_VIG (fecha Oracle formato ddMMMyyyy:hh:mm:ss)
  CASE 
    WHEN INI_VIG IS NOT NULL AND INI_VIG != '' 
    THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', INI_VIG)
    ELSE NULL 
  END AS INI_VIG,
  
  -- 7. FIN_VIG (fecha Oracle formato ddMMMyyyy:hh:mm:ss)
  CASE 
    WHEN FIN_VIG IS NOT NULL AND FIN_VIG != '' 
    THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', FIN_VIG)
    ELSE NULL 
  END AS FIN_VIG,
  
  -- 8. NO_OFI
  SAFE_CAST(SAFE_CAST(NULLIF(NO_OFI, '') AS FLOAT64) AS INT64) AS NO_OFI,
  
  -- 9. COD_ASEG
  SAFE_CAST(SAFE_CAST(NULLIF(COD_ASEG, '') AS FLOAT64) AS INT64) AS COD_ASEG,
  
  -- 10. NOM_ASEG
  NOM_ASEG,
  
  -- 11. AMIS
  SAFE_CAST(SAFE_CAST(NULLIF(AMIS, '') AS FLOAT64) AS INT64) AS AMIS,
  
  -- 12. MOD
  SAFE_CAST(SAFE_CAST(NULLIF(MOD, '') AS FLOAT64) AS INT64) AS MOD,
  
  -- 13. USO
  SAFE_CAST(SAFE_CAST(NULLIF(USO, '') AS FLOAT64) AS INT64) AS USO,
  
  -- 14. SERV
  SAFE_CAST(SAFE_CAST(NULLIF(SERV, '') AS FLOAT64) AS INT64) AS SERV,
  
  -- 15. CVE_AGTE
  SAFE_CAST(SAFE_CAST(NULLIF(CVE_AGTE, '') AS FLOAT64) AS INT64) AS CVE_AGTE,
  
  -- 16. NOM_AGTE
  NOM_AGTE,
  
  -- 17. EDO
  EDO,
  
  -- 18. COD_COBER
  SAFE_CAST(SAFE_CAST(NULLIF(COD_COBER, '') AS FLOAT64) AS INT64) AS COD_COBER,
  
  -- 19. COBERTURA
  COBERTURA,
  
  -- 20. SUMA_ASEG
  SAFE_CAST(NULLIF(SUMA_ASEG, '') AS FLOAT64) AS SUMA_ASEG,
  
  -- 21. PRIMA_DM
  SAFE_CAST(NULLIF(PRIMA_DM, '') AS FLOAT64) AS PRIMA_DM,
  
  -- 22. PORC_DM
  SAFE_CAST(SAFE_CAST(NULLIF(PORC_DM, '') AS FLOAT64) AS INT64) AS PORC_DM,
  
  -- 23. PRIMA_RT
  SAFE_CAST(NULLIF(PRIMA_RT, '') AS FLOAT64) AS PRIMA_RT,
  
  -- 24. PORC_RT
  SAFE_CAST(SAFE_CAST(NULLIF(PORC_RT, '') AS FLOAT64) AS INT64) AS PORC_RT,
  
  -- 25. PRIMA_SPT
  SAFE_CAST(NULLIF(PRIMA_SPT, '') AS FLOAT64) AS PRIMA_SPT,
  
  -- 26. SA_RC
  SAFE_CAST(SAFE_CAST(NULLIF(SA_RC, '') AS FLOAT64) AS INT64) AS SA_RC,
  
  -- 27. PRIMA_RC
  SAFE_CAST(NULLIF(PRIMA_RC, '') AS FLOAT64) AS PRIMA_RC,
  
  -- 28. PORC_RC
  SAFE_CAST(SAFE_CAST(NULLIF(PORC_RC, '') AS FLOAT64) AS INT64) AS PORC_RC,
  
  -- 29. SA_RCPER
  SAFE_CAST(SAFE_CAST(NULLIF(SA_RCPER, '') AS FLOAT64) AS INT64) AS SA_RCPER,
  
  -- 30. PRIMA_RCPER
  SAFE_CAST(SAFE_CAST(NULLIF(PRIMA_RCPER, '') AS FLOAT64) AS INT64) AS PRIMA_RCPER,
  
  -- 31. DED_RCP
  DED_RCP,
  
  -- 32. SA_RCBIEN
  SAFE_CAST(SAFE_CAST(NULLIF(SA_RCBIEN, '') AS FLOAT64) AS INT64) AS SA_RCBIEN,
  
  -- 33. PRIMA_RCBIEN
  SAFE_CAST(SAFE_CAST(NULLIF(PRIMA_RCBIEN, '') AS FLOAT64) AS INT64) AS PRIMA_RCBIEN,
  
  -- 34. DED_RCB
  DED_RCB,
  
  -- 35. CARGA
  CARGA,
  
  -- 36. SA_GM
  SAFE_CAST(SAFE_CAST(NULLIF(SA_GM, '') AS FLOAT64) AS INT64) AS SA_GM,
  
  -- 37. PRIMA_GM
  SAFE_CAST(NULLIF(PRIMA_GM, '') AS FLOAT64) AS PRIMA_GM,
  
  -- 38. SA_RCPAS
  SAFE_CAST(NULLIF(SA_RCPAS, '') AS FLOAT64) AS SA_RCPAS,
  
  -- 39. PRIMA_RCPAS
  SAFE_CAST(NULLIF(PRIMA_RCPAS, '') AS FLOAT64) AS PRIMA_RCPAS,
  
  -- 40. DED_RCPAS
  DED_RCPAS,
  
  -- 41. SA_ADAP
  SAFE_CAST(SAFE_CAST(NULLIF(SA_ADAP, '') AS FLOAT64) AS INT64) AS SA_ADAP,
  
  -- 42. PRIMA_ADAP_DM
  SAFE_CAST(NULLIF(PRIMA_ADAP_DM, '') AS FLOAT64) AS PRIMA_ADAP_DM,
  
  -- 43. PRIMA_ADAP_RT
  SAFE_CAST(SAFE_CAST(NULLIF(PRIMA_ADAP_RT, '') AS FLOAT64) AS INT64) AS PRIMA_ADAP_RT,
  
  -- 44. SA_EE
  SAFE_CAST(SAFE_CAST(NULLIF(SA_EE, '') AS FLOAT64) AS INT64) AS SA_EE,
  
  -- 45. PRIMA_EE
  SAFE_CAST(SAFE_CAST(NULLIF(PRIMA_EE, '') AS FLOAT64) AS INT64) AS PRIMA_EE,
  
  -- 46. DED_EE
  DED_EE,
  
  -- 47. SA_RPARC
  SAFE_CAST(SAFE_CAST(NULLIF(SA_RPARC, '') AS FLOAT64) AS INT64) AS SA_RPARC,
  
  -- 48. PRIMA_RPARC
  SAFE_CAST(NULLIF(PRIMA_RPARC, '') AS FLOAT64) AS PRIMA_RPARC,
  
  -- 49. DED_RP
  DED_RP,
  
  -- 50. PRIMA_AV
  SAFE_CAST(NULLIF(PRIMA_AV, '') AS FLOAT64) AS PRIMA_AV,
  
  -- 51. PRIMA_GL
  SAFE_CAST(NULLIF(PRIMA_GL, '') AS FLOAT64) AS PRIMA_GL,
  
  -- 52. PRIMA_RCECOL
  SAFE_CAST(SAFE_CAST(NULLIF(PRIMA_RCECOL, '') AS FLOAT64) AS INT64) AS PRIMA_RCECOL,
  
  -- 53. PRIMA_EXDED
  SAFE_CAST(NULLIF(PRIMA_EXDED, '') AS FLOAT64) AS PRIMA_EXDED,
  
  -- 54. PRIMA_AAUT
  SAFE_CAST(SAFE_CAST(NULLIF(PRIMA_AAUT, '') AS FLOAT64) AS INT64) AS PRIMA_AAUT,
  
  -- 55. TARIFA
  SAFE_CAST(SAFE_CAST(NULLIF(TARIFA, '') AS FLOAT64) AS INT64) AS TARIFA,
  
  -- 56. PORC_BT
  SAFE_CAST(NULLIF(PORC_BT, '') AS FLOAT64) AS PORC_BT,
  
  -- 57. PAGO
  PAGO,
  
  -- 58. PORC_RFIN
  SAFE_CAST(NULLIF(PORC_RFIN, '') AS FLOAT64) AS PORC_RFIN,
  
  -- 59. PRIMA_TOTAL
  SAFE_CAST(NULLIF(PRIMA_TOTAL, '') AS FLOAT64) AS PRIMA_TOTAL,
  
  -- 60. MONEDA
  SAFE_CAST(SAFE_CAST(NULLIF(MONEDA, '') AS FLOAT64) AS INT64) AS MONEDA,
  
  -- 61. TCAMBIO
  SAFE_CAST(SAFE_CAST(NULLIF(TCAMBIO, '') AS FLOAT64) AS INT64) AS TCAMBIO,
  
  -- 62. TA
  TA,
  
  -- 63. REMESA
  SAFE_CAST(SAFE_CAST(NULLIF(REMESA, '') AS FLOAT64) AS INT64) AS REMESA,
  
  -- 64. FEC_PAGO (fecha Oracle formato ddMMMyyyy:hh:mm:ss)
  CASE 
    WHEN FEC_PAGO IS NOT NULL AND FEC_PAGO != '' 
    THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', FEC_PAGO)
    ELSE NULL 
  END AS FEC_PAGO,
  
  -- 65. D_AUTO
  SAFE_CAST(SAFE_CAST(NULLIF(D_AUTO, '') AS FLOAT64) AS INT64) AS D_AUTO,
  
  -- 66. D_CAMION
  SAFE_CAST(SAFE_CAST(NULLIF(D_CAMION, '') AS FLOAT64) AS INT64) AS D_CAMION,
  
  -- 67. PRIMA_RCXDAO
  SAFE_CAST(NULLIF(PRIMA_RCXDAO, '') AS FLOAT64) AS PRIMA_RCXDAO,
  
  -- 68. SA_RCXDAO
  SAFE_CAST(SAFE_CAST(NULLIF(SA_RCXDAO, '') AS FLOAT64) AS INT64) AS SA_RCXDAO,
  
  -- 69. PRIMA_EXTRC
  SAFE_CAST(NULLIF(PRIMA_EXTRC, '') AS FLOAT64) AS PRIMA_EXTRC,
  
  -- 70. SA_EXTRC
  SAFE_CAST(SAFE_CAST(NULLIF(SA_EXTRC, '') AS FLOAT64) AS INT64) AS SA_EXTRC,
  
  -- 71. GRABADO
  GRABADO,
  
  -- 72. T1DM
  SAFE_CAST(NULLIF(T1DM, '') AS FLOAT64) AS T1DM,
  
  -- 73. T2DM
  SAFE_CAST(NULLIF(T2DM, '') AS FLOAT64) AS T2DM,
  
  -- 74. T1RT
  SAFE_CAST(NULLIF(T1RT, '') AS FLOAT64) AS T1RT,
  
  -- 75. T2RT
  SAFE_CAST(NULLIF(T2RT, '') AS FLOAT64) AS T2RT,
  
  -- 76. COD_EDO
  SAFE_CAST(SAFE_CAST(NULLIF(COD_EDO, '') AS FLOAT64) AS INT64) AS COD_EDO,
  
  -- 77. ESTADO
  ESTADO,
  
  -- 78. VALOR_NVO
  SAFE_CAST(NULLIF(VALOR_NVO, '') AS FLOAT64) AS VALOR_NVO,
  
  -- 79. PRIMA_GT
  SAFE_CAST(NULLIF(PRIMA_GT, '') AS FLOAT64) AS PRIMA_GT,
  
  -- 80. NO_CATALO
  SAFE_CAST(SAFE_CAST(NULLIF(NO_CATALO, '') AS FLOAT64) AS INT64) AS NO_CATALO,
  
  -- 81. NOM_AGENCIA
  NOM_AGENCIA,
  
  -- 82. NO_AGENCIA
  NO_AGENCIA,
  
  -- 83. PRIMA_MCXAA
  SAFE_CAST(NULLIF(PRIMA_MCXAA, '') AS FLOAT64) AS PRIMA_MCXAA,
  
  -- 84. SUMA_MCXAA
  SAFE_CAST(SAFE_CAST(NULLIF(SUMA_MCXAA, '') AS FLOAT64) AS INT64) AS SUMA_MCXAA,
  
  -- 85. PRIMA_GTPAR
  SAFE_CAST(NULLIF(PRIMA_GTPAR, '') AS FLOAT64) AS PRIMA_GTPAR,
  
  -- 86. SUMA_GTPAR
  SAFE_CAST(SAFE_CAST(NULLIF(SUMA_GTPAR, '') AS FLOAT64) AS INT64) AS SUMA_GTPAR,
  
  -- 87. PRIMA_NEUMAT
  SAFE_CAST(NULLIF(PRIMA_NEUMAT, '') AS FLOAT64) AS PRIMA_NEUMAT,
  
  -- 88. SUMA_NEUMAT
  SAFE_CAST(SAFE_CAST(NULLIF(SUMA_NEUMAT, '') AS FLOAT64) AS INT64) AS SUMA_NEUMAT,
  
  -- 89. PRIMA_RINES
  SAFE_CAST(NULLIF(PRIMA_RINES, '') AS FLOAT64) AS PRIMA_RINES,
  
  -- 90. SUMA_RINES
  SAFE_CAST(SAFE_CAST(NULLIF(SUMA_RINES, '') AS FLOAT64) AS INT64) AS SUMA_RINES,
  
  -- 91. PRIMA_CADE
  SAFE_CAST(NULLIF(PRIMA_CADE, '') AS FLOAT64) AS PRIMA_CADE,
  
  -- 92. CAL_P_C_L
  CAL_P_C_L,
  
  -- 93. ESQ
  SAFE_CAST(SAFE_CAST(NULLIF(ESQ, '') AS FLOAT64) AS INT64) AS ESQ,
  
  -- 94. MARCA
  MARCA,
  
  -- 95. TIPO
  TIPO,
  
  -- 96. CATEG
  SAFE_CAST(SAFE_CAST(NULLIF(CATEG, '') AS FLOAT64) AS INT64) AS CATEG,
  
  -- 97. OF_EMI
  OF_EMI,
  
  -- 98. UDI
  SAFE_CAST(NULLIF(UDI, '') AS FLOAT64) AS UDI,
  
  -- 99. USUARIO
  USUARIO,
  
  -- 100. PRIMATOT_PV
  SAFE_CAST(NULLIF(PRIMATOT_PV, '') AS FLOAT64) AS PRIMATOT_PV,
  
  -- 101. FORMA_PAGO
  FORMA_PAGO,
  
  -- 102. COMIS_AGTE
  SAFE_CAST(NULLIF(COMIS_AGTE, '') AS FLOAT64) AS COMIS_AGTE,
  
  -- 103. SERIE
  SERIE,
  
  -- 104. BATCHDATE
  BATCHDATE,
  
  -- 105. SYSUSERID
  SYSUSERID

FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.PRODUCCION2`;