CREATE OR REPLACE TABLE `DM_FRAUDES.DM_ESTADOS`  AS
SELECT
Z_ID AS ID,
EDOPOB AS ESTADO_POBLACION,
ESTATUS,
CVEMPIO_INEGI AS CLAVE_INEGI,
REGION,
RADIOPERFIL AS RADIO_PERFIL,
EDO_ESTANDAR AS ESTADO_ESTANDAR,
EDOPOB2 AS ESTADO_POBLACION_2
FROM `qualitasfraude.sample_landing_siniestros_bsc.testado_bsc`;