CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.DM_CONTROL_FRAUDES.DM_CONTROL_DE_AGENTES` AS
SELECT 
  -- 1. TIPO_CVE
  TIPO_CVE,
  
  -- 2. FECHA_ALTA (formato dd/MM/yyyy)
  CASE 
    WHEN FECHA_ALTA IS NOT NULL AND FECHA_ALTA != '' AND FECHA_ALTA LIKE '%/%/%'
    THEN SAFE.PARSE_DATE('%d/%m/%Y', FECHA_ALTA)
    ELSE NULL 
  END AS FECHA_ALTA,
  
  -- 3. FECHA_BAJA (formato Excel - número de días desde 1900-01-01)
  CASE 
    WHEN FECHA_BAJA IS NOT NULL AND FECHA_BAJA != '' AND SAFE_CAST(FECHA_BAJA AS FLOAT64) IS NOT NULL
    THEN DATE_ADD(DATE '1900-01-01', INTERVAL CAST(SAFE_CAST(FECHA_BAJA AS FLOAT64) AS INT64) - 2 DAY)
    ELSE NULL 
  END AS FECHA_BAJA,
  
  -- 4. CAUSA_BAJA
  SAFE_CAST(SAFE_CAST(NULLIF(CAUSA_BAJA, '') AS FLOAT64) AS INT64) AS CAUSA_BAJA,
  
  -- 5. POLITICA
  SAFE_CAST(SAFE_CAST(NULLIF(POLITICA, '') AS FLOAT64) AS INT64) AS POLITICA,
  
  -- 6. GRUPO
  SAFE_CAST(SAFE_CAST(NULLIF(GRUPO, '') AS FLOAT64) AS INT64) AS GRUPO,
  
  -- 7. PROMOTOR
  PROMOTOR,
  
  -- 8. PMA_PAG_MES_ANT
  SAFE_CAST(NULLIF(PMA_PAG_MES_ANT, '') AS FLOAT64) AS PMA_PAG_MES_ANT,
  
  -- 9. PMA_PAG_NETA_MES_ANT
  SAFE_CAST(NULLIF(PMA_PAG_NETA_MES_ANT, '') AS FLOAT64) AS PMA_PAG_NETA_MES_ANT,
  
  -- 10. PMA_DEV_ACUM_MES_ANT
  SAFE_CAST(NULLIF(PMA_DEV_ACUM_MES_ANT, '') AS FLOAT64) AS PMA_DEV_ACUM_MES_ANT,
  
  -- 11. SINIESTRALIDAD_MES_ANT
  SAFE_CAST(NULLIF(SINIESTRALIDAD_MES_ANT, '') AS FLOAT64) AS SINIESTRALIDAD_MES_ANT,
  
  -- 12. PORC_SIN_MES_ANT (remover % y convertir a decimal)
  SAFE_CAST(NULLIF(REPLACE(PORC_SIN_MES_ANT, '%', ''), '') AS FLOAT64) AS PORC_SIN_MES_ANT,
  
  -- 13. CVE_AGENTE
  SAFE_CAST(SAFE_CAST(NULLIF(CVE_AGENTE, '') AS FLOAT64) AS INT64) AS CVE_AGENTE,
  
  -- 14. CVE_AGTE
  SAFE_CAST(SAFE_CAST(NULLIF(CVE_AGTE, '') AS FLOAT64) AS INT64) AS CVE_AGTE,
  
  -- 15. AGENTE_AP
  AGENTE_AP,
  
  -- 16. AGENTE_NOM
  AGENTE_NOM,
  
  -- 17. TIPO
  TIPO,
  
  -- 18. PERSONA
  PERSONA,
  
  -- 19. ID_GERENCIA
  SAFE_CAST(SAFE_CAST(NULLIF(ID_GERENCIA, '') AS FLOAT64) AS INT64) AS ID_GERENCIA,
  
  -- 20. GERENTE
  GERENTE,
  
  -- 21. ID_OFICINA
  SAFE_CAST(SAFE_CAST(NULLIF(ID_OFICINA, '') AS FLOAT64) AS INT64) AS ID_OFICINA,
  
  -- 22. OFICINA
  OFICINA,
  
  -- 23. CEDULA
  CEDULA,
  
  -- 24. CED_HASTA
  CED_HASTA,
  
  -- 25. CED_DESDE
  CED_DESDE,
  
  -- 26. TIPO_CEDULA
  TIPO_CEDULA,
  
  -- 27. POLIZA_RC
  POLIZA_RC,
  
  -- 28. RC_DESDE
  RC_DESDE,
  
  -- 29. RC_HASTA
  RC_HASTA,
  
  -- 30. RFC
  RFC,
  
  -- 31. DOM_FISCAL
  DOM_FISCAL,
  
  -- 32. INC_27
  SAFE_CAST(SAFE_CAST(NULLIF(INC_27, '') AS FLOAT64) AS INT64) AS INC_27,
  
  -- 33. NOMBRE_GERENTE_INC27
  NOMBRE_GERENTE_INC27,
  
  -- 34. TEL_PARTICULAR
  TEL_PARTICULAR,
  
  -- 35. TEL_COMERCIAL
  TEL_COMERCIAL,
  
  -- 36. AVISO_COM_GRAL
  AVISO_COM_GRAL,
  
  -- 37. AVISO_CANC_AUT
  AVISO_CANC_AUT,
  
  -- 38. AVISO_PAGO_REF_CRED
  AVISO_PAGO_REF_CRED,
  
  -- 39. AVISO_SINIEST
  AVISO_SINIEST,
  
  -- 40. AVISO_ENCUESTA
  AVISO_ENCUESTA,
  
  -- 41. CURP
  CURP,
  
  -- 42. CVE_ESTADO
  SAFE_CAST(SAFE_CAST(NULLIF(CVE_ESTADO, '') AS FLOAT64) AS INT64) AS CVE_ESTADO,
  
  -- 43. ESTADO
  ESTADO,
  
  -- 44. POLITICA_UDI
  SAFE_CAST(SAFE_CAST(NULLIF(POLITICA_UDI, '') AS FLOAT64) AS INT64) AS POLITICA_UDI,
  
  -- 45. COMIS_NOR_AU
  SAFE_CAST(NULLIF(COMIS_NOR_AU, '') AS FLOAT64) AS COMIS_NOR_AU,
  
  -- 46. COMIS_RF_AU
  SAFE_CAST(NULLIF(COMIS_RF_AU, '') AS FLOAT64) AS COMIS_RF_AU,
  
  -- 47. COMIS_NOR_CA
  SAFE_CAST(NULLIF(COMIS_NOR_CA, '') AS FLOAT64) AS COMIS_NOR_CA,
  
  -- 48. COMIS_RF_CA
  SAFE_CAST(NULLIF(COMIS_RF_CA, '') AS FLOAT64) AS COMIS_RF_CA,
  
  -- 49. COMIS_NOR_MO
  SAFE_CAST(NULLIF(COMIS_NOR_MO, '') AS FLOAT64) AS COMIS_NOR_MO,
  
  -- 50. COMIS_RF_MO
  SAFE_CAST(NULLIF(COMIS_RF_MO, '') AS FLOAT64) AS COMIS_RF_MO,
  
  -- 51. UDI_AU
  SAFE_CAST(NULLIF(UDI_AU, '') AS FLOAT64) AS UDI_AU,
  
  -- 52. UDI_CA
  SAFE_CAST(NULLIF(UDI_CA, '') AS FLOAT64) AS UDI_CA,
  
  -- 53. UDI_MO
  SAFE_CAST(NULLIF(UDI_MO, '') AS FLOAT64) AS UDI_MO,
  
  -- 54. UDI_3
  SAFE_CAST(NULLIF(UDI_3, '') AS FLOAT64) AS UDI_3,
  
  -- 55. COMIS_NOR_3
  SAFE_CAST(SAFE_CAST(NULLIF(COMIS_NOR_3, '') AS FLOAT64) AS INT64) AS COMIS_NOR_3,
  
  -- 56. UDI_04
  SAFE_CAST(NULLIF(UDI_04, '') AS FLOAT64) AS UDI_04,
  
  -- 57. COMIS_NOR_04
  SAFE_CAST(SAFE_CAST(NULLIF(COMIS_NOR_04, '') AS FLOAT64) AS INT64) AS COMIS_NOR_04,
  
  -- 58. UDI_05
  SAFE_CAST(NULLIF(UDI_05, '') AS FLOAT64) AS UDI_05,
  
  -- 59. COMIS_NOR_05
  SAFE_CAST(NULLIF(COMIS_NOR_05, '') AS FLOAT64) AS COMIS_NOR_05,
  
  -- 60. UDI_07
  SAFE_CAST(NULLIF(UDI_07, '') AS FLOAT64) AS UDI_07,
  
  -- 61. COMIS_NOR_07
  SAFE_CAST(SAFE_CAST(NULLIF(COMIS_NOR_07, '') AS FLOAT64) AS INT64) AS COMIS_NOR_07,
  
  -- 62. T_EMISION
  T_EMISION,
  
  -- 63. T_COBRANZA
  T_COBRANZA,
  
  -- 64. T_POLIZA
  T_POLIZA,
  
  -- 65. DESCUENTO
  SAFE_CAST(NULLIF(DESCUENTO, '') AS FLOAT64) AS DESCUENTO,
  
  -- 66. COMENTARIOS
  COMENTARIOS,
  
  -- 67. DATO_ESTADISTICO
  DATO_ESTADISTICO,
  
  -- 68. CONTRATO_CONSOLIDADO
  CONTRATO_CONSOLIDADO,
  
  -- 69. ARTICULO_140
  ARTICULO_140,
  
  -- 70. EMISION_DELEGADA
  EMISION_DELEGADA,
  
  -- 71. CONT_PRIV_CARACTER_10
  CONT_PRIV_CARACTER_10,
  
  -- 72. PRIMERACTA
  PRIMERACTA,
  
  -- 73. SEGUNDAACTA
  SEGUNDAACTA,
  
  -- 74. DIS_PRIM
  DIS_PRIM,
  
  -- 75. AUT_PRIM
  AUT_PRIM,
  
  -- 76. NOM_1
  SAFE_CAST(SAFE_CAST(NULLIF(NOM_1, '') AS FLOAT64) AS INT64) AS NOM_1,
  
  -- 77. NOM_2
  NOM_2,
  
  -- 78. NOM_3
  SAFE_CAST(SAFE_CAST(NULLIF(NOM_3, '') AS FLOAT64) AS INT64) AS NOM_3,
  
  -- 79. CONVENIO_EMI_DELEGADA
  CONVENIO_EMI_DELEGADA,
  
  -- 80. CVE_EMITE_DELEGADAMENTE
  CVE_EMITE_DELEGADAMENTE,
  
  -- 81. FECHA_DIGITALIZADO (formato Excel)
  CASE 
    WHEN FECHA_DIGITALIZADO IS NOT NULL AND FECHA_DIGITALIZADO != '' AND SAFE_CAST(FECHA_DIGITALIZADO AS FLOAT64) IS NOT NULL
    THEN DATE_ADD(DATE '1900-01-01', INTERVAL CAST(SAFE_CAST(FECHA_DIGITALIZADO AS FLOAT64) AS INT64) - 2 DAY)
    ELSE NULL 
  END AS FECHA_DIGITALIZADO,
  
  -- 82. NO_CVES_AGENTE
  SAFE_CAST(SAFE_CAST(NULLIF(NO_CVES_AGENTE, '') AS FLOAT64) AS INT64) AS NO_CVES_AGENTE,
  
  -- 83. NO_RFCS_AGENTE
  SAFE_CAST(SAFE_CAST(NULLIF(NO_RFCS_AGENTE, '') AS FLOAT64) AS INT64) AS NO_RFCS_AGENTE,
  
  -- 84. PMA_PAG_MES_ANIO_ANT
  SAFE_CAST(NULLIF(PMA_PAG_MES_ANIO_ANT, '') AS FLOAT64) AS PMA_PAG_MES_ANIO_ANT,
  
  -- 85. PMA_PAG_NETA_MES_ANIO_ANT
  SAFE_CAST(NULLIF(PMA_PAG_NETA_MES_ANIO_ANT, '') AS FLOAT64) AS PMA_PAG_NETA_MES_ANIO_ANT,
  
  -- 86. PMA_DEV_ACUM_MES_ANIO_ANT
  PMA_DEV_ACUM_MES_ANIO_ANT,
  
  -- 87. SINIESTRALIDAD_MES_ANIO_ANT
  SAFE_CAST(NULLIF(SINIESTRALIDAD_MES_ANIO_ANT, '') AS FLOAT64) AS SINIESTRALIDAD_MES_ANIO_ANT,
  
  -- 88. PORC_SIN_MES_ANIO_ANT (remover % y convertir)
  SAFE_CAST(NULLIF(REPLACE(PORC_SIN_MES_ANIO_ANT, '%', ''), '') AS FLOAT64) AS PORC_SIN_MES_ANIO_ANT,
  
  -- 89. PMA_PAG_A_DIC_ANIO_ANT
  SAFE_CAST(NULLIF(PMA_PAG_A_DIC_ANIO_ANT, '') AS FLOAT64) AS PMA_PAG_A_DIC_ANIO_ANT,
  
  -- 90. PMA_PAG_NETA_A_DIC_ANIO_ANT
  SAFE_CAST(NULLIF(PMA_PAG_NETA_A_DIC_ANIO_ANT, '') AS FLOAT64) AS PMA_PAG_NETA_A_DIC_ANIO_ANT,
  
  -- 91. PMA_DEV_ACUM_A_DIC_ANIO_ANT
  PMA_DEV_ACUM_A_DIC_ANIO_ANT,
  
  -- 92. SINIESTRALIDAD_A_DIC_ANIO_ANT
  SAFE_CAST(NULLIF(SINIESTRALIDAD_A_DIC_ANIO_ANT, '') AS FLOAT64) AS SINIESTRALIDAD_A_DIC_ANIO_ANT,
  
  -- 93. PORC_SIN_A_DIC_ANIO_ANT (remover % y convertir)
  SAFE_CAST(NULLIF(REPLACE(PORC_SIN_A_DIC_ANIO_ANT, '%', ''), '') AS FLOAT64) AS PORC_SIN_A_DIC_ANIO_ANT,
  
  -- 94. PMA_PAG_A_DIC_ANIO_MENOS2
  SAFE_CAST(NULLIF(PMA_PAG_A_DIC_ANIO_MENOS2, '') AS FLOAT64) AS PMA_PAG_A_DIC_ANIO_MENOS2,
  
  -- 95. PMA_PAG_NETA_A_DIC_ANIO_MENOS2
  PMA_PAG_NETA_A_DIC_ANIO_MENOS2,
  
  -- 96. PMA_DEV_ACUM_A_DIC_ANIO_MENOS2
  PMA_DEV_ACUM_A_DIC_ANIO_MENOS2,
  
  -- 97. SINIESTRALIDAD_A_DIC_ANIO_MENOS2
  SAFE_CAST(NULLIF(SINIESTRALIDAD_A_DIC_ANIO_MENOS2, '') AS FLOAT64) AS SINIESTRALIDAD_A_DIC_ANIO_MENOS2,
  
  -- 98. PORC_SIN_A_DIC_ANIO_MENOS2 (remover % y convertir)
  SAFE_CAST(NULLIF(REPLACE(PORC_SIN_A_DIC_ANIO_MENOS2, '%', ''), '') AS FLOAT64) AS PORC_SIN_A_DIC_ANIO_MENOS2,
  
  -- 99. PMA_PAG_A_DIC_ANIO_MENOS3
  SAFE_CAST(NULLIF(PMA_PAG_A_DIC_ANIO_MENOS3, '') AS FLOAT64) AS PMA_PAG_A_DIC_ANIO_MENOS3,
  
  -- 100. PMA_PAG_NETA_A_DIC_ANIO_MENOS3
  SAFE_CAST(NULLIF(PMA_PAG_NETA_A_DIC_ANIO_MENOS3, '') AS FLOAT64) AS PMA_PAG_NETA_A_DIC_ANIO_MENOS3,
  
  -- 101. PMA_DEV_ACUM_A_DIC_ANIO_MENOS3
  SAFE_CAST(NULLIF(PMA_DEV_ACUM_A_DIC_ANIO_MENOS3, '') AS FLOAT64) AS PMA_DEV_ACUM_A_DIC_ANIO_MENOS3,
  
  -- 102. TOTAL_SINIEST_A_DIC_ANIO_MENOS3
  SAFE_CAST(NULLIF(TOTAL_SINIEST_A_DIC_ANIO_MENOS3, '') AS FLOAT64) AS TOTAL_SINIEST_A_DIC_ANIO_MENOS3,
  
  -- 103. PORC_SIN_A_DIC_ANIO_MENOS3 (remover % y convertir)
  SAFE_CAST(NULLIF(REPLACE(PORC_SIN_A_DIC_ANIO_MENOS3, '%', ''), '') AS FLOAT64) AS PORC_SIN_A_DIC_ANIO_MENOS3,
  
  -- 104. EJECUTIVO_AOM_AOF_ODQ
  EJECUTIVO_AOM_AOF_ODQ,
  
  -- 105. ES_AGENTE
  ES_AGENTE,
  
  -- 106. ZONA_ATENCION
  ZONA_ATENCION,
  
  -- 107. DIRECCION
  DIRECCION,
  
  -- 108. DIRECCION_ATENCION
  DIRECCION_ATENCION,
  
  -- 109. SUBDIREC_ATENCION
  SUBDIREC_ATENCION,
  
  -- 110. GERENTE_ATENCION
  SAFE_CAST(SAFE_CAST(NULLIF(GERENTE_ATENCION, '') AS FLOAT64) AS INT64) AS GERENTE_ATENCION,
  
  -- 111. COORD_ATENCION
  COORD_ATENCION,
  
  -- 112. ACUSE_RECIBO
  ACUSE_RECIBO,
  
  -- 113. POLITICAS_CONOCIMIENTO
  POLITICAS_CONOCIMIENTO,
  
  -- 114. CONTRATO_DIC_2013
  CONTRATO_DIC_2013,
  
  -- 115. DOC_COMPLETA
  DOC_COMPLETA,
  
  -- 116. CATALOGO_NEGOCIO
  CATALOGO_NEGOCIO,
  
  -- 117. BLOQUEO_6_MSP
  BLOQUEO_6_MSP,
  
  -- 118. ULTIMA_EMISION
  SAFE_CAST(SAFE_CAST(NULLIF(ULTIMA_EMISION, '') AS FLOAT64) AS INT64) AS ULTIMA_EMISION,
  
  -- 119. SUBDIRECTOR
  SUBDIRECTOR,
  
  -- 120. SUBGRUPO
  SAFE_CAST(SAFE_CAST(NULLIF(SUBGRUPO, '') AS FLOAT64) AS INT64) AS SUBGRUPO,
  
  -- 121. CLASIFICACION_NEGOCIO
  CLASIFICACION_NEGOCIO,
  
  -- 122. CVE_UNICA_AGTE
  CVE_UNICA_AGTE,
  
  -- 123. CLAVE_UNICA_AGENTE
  CLAVE_UNICA_AGENTE,
  
  -- 124. MES_REPORTE
  MES_REPORTE,
  
  -- 125. ANIO_REPORTE
  SAFE_CAST(SAFE_CAST(NULLIF(ANIO_REPORTE, '') AS FLOAT64) AS INT64) AS ANIO_REPORTE,
  
  -- 126. BATCHDATE
  BATCHDATE,
  
  -- 127. SYSUSERID
  SYSUSERID

FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.CONTROL_DE_AGENTES`;