SELECT 
  -- NO_OPERACION: String
  NO_OPERACION,
  
  -- TIPO_TRANSACCION: String -> STRING (mantiene como string)
  TIPO_TRANSACCION,
  
  -- FECHA_PRESENTACION: String -> DATE (valores de fecha)
  SAFE_CAST(SUBSTR(FECHA_PRESENTACION,7,4) || '-' || SUBSTR(FECHA_PRESENTACION,4,2) || '-' || SUBSTR(FECHA_PRESENTACION,1,2) AS DATE) AS FECHA_PRESENTACION,
  
  -- IMPORTE_CONTRACARGO: String -> FLOAT64 (valores numéricos decimales)
  SAFE_CAST(IMPORTE_CONTRACARGO AS FLOAT64) AS IMPORTE_CONTRACARGO

FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.CONTRACARGOS`;