TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`;
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`
SELECT
  IDREFACCION,
  DESCRIPCION,
  ALTA,
  ACTUALIZACION,
  USUARIOACTUALIZA,
  AUTOS,
  EP,
  ROW_NUMBER() OVER (PARTITION BY IDREFACCION ORDER BY ACTUALIZACION DESC) AS RN
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`;
