CREATE OR REPLACE TABLE `STG_VERIFICACIONES.STG_REFACCION_1` AS
SELECT
  IDREFACCION,
  DESCRIPCION,
  ALTA,
  ACTUALIZACION,
  USUARIOACTUALIZA,
  AUTOS,
  EP,
  ROW_NUMBER() OVER (PARTITION BY IDREFACCION ORDER BY ACTUALIZACION DESC) AS RN
FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.REFACCION`;