CREATE OR REPLACE TABLE `STG_VERIFICACIONES.STG_REFACCION_2` AS
SELECT
  IDREFACCION,
  DESCRIPCION,
  ALTA,
  ACTUALIZACION,
  USUARIOACTUALIZA,
  AUTOS,
  EP
FROM `STG_VERIFICACIONES.STG_REFACCION_1`
WHERE RN = 1;