CREATE OR REPLACE TABLE `STG_VERIFICACIONES.STG_REFACCION_2` AS
SELECT
  IDREFACCION,
  DESCRIPCION,
  ALTA,
  ACTUALIZACION,
  USUARIOACTUALIZA,
  AUTOS,
  EP
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`
WHERE RN = 1;