CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ADMINISTRADORREFACCIONES`
(
  IDADMINISTRADORREFACCIONES STRING NOT NULL,
  NOMBRE STRING,
  FECHAREGISTRO DATETIME,
  FECHAACTUALIZACION DATETIME,
  USUARIOACTUALIZA STRING,
  DATO STRING,
  ACTIVO BIGNUMERIC,
  ENTIDAD BIGNUMERIC,
  IDREGION STRING,
  ADMINISTRAALERTAS BIGNUMERIC NOT NULL,
  ACTIVOADMINISTRADOR BIGNUMERIC,
  IDREGIONGEOGRAFICA BIGNUMERIC,
  MODIFICAMONTOTOPE STRING NOT NULL
);

CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ANALISTACDR`
(
  IDANALISTACDR STRING NOT NULL,
  CLAVEANALISTA STRING NOT NULL,
  NOMBRENNALISTA STRING NOT NULL,
  ESTATUS BIGNUMERIC NOT NULL,
  IDREGIONGEOGRAFICA STRING NOT NULL,
  FECHAREGISTROANL DATETIME NOT NULL,
  FECHAACTUALIZACIONANL DATETIME,
  CORREO STRING,
  TELEFONO STRING,
  CONSULTA BIGNUMERIC
);

CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.PRESTADORES`
(
  Id STRING NOT NULL,
  Nombre STRING,
  Marca STRING,
  Tipo STRING,
  Oficina STRING,
  SUSPENCION STRING,
  Status STRING,
  Fbaja DATETIME,
  CodEstado STRING,
  Poblacion STRING,
  Direccion STRING,
  Colonia STRING,
  Telefono STRING,
  Dir_Comer STRING,
  Col_Comer STRING,
  Pob_Comer STRING,
  Edo_Comer STRING,
  Num_Docto STRING,
  Nom_Comer STRING,
  Grupo STRING,
  FEC_ALTA DATETIME,
  CTA_ESP STRING,
  TIPO_AJUS STRING,
  MARCA_TIPO STRING,
  RFC STRING,
  Correo_Comercial STRING,
  Correo_Contacto STRING,
  MARCA_MOTOS STRING,
  TEL_SIICA STRING,
  AE INT64,
  LATITUD STRING,
  LONGITUD STRING,
  EDOCOM STRING,
  POBCOMER STRING,
  RECIBE24 STRING,
  ZONAPROV STRING,
  VED STRING,
  TIPO_PERSONA STRING,
  Correo_Comercial2 STRING,
  CEXP INT64,
  TBODY STRING,
  NUM_EMPL STRING
);

CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.SUPERVISORINTEGRAL`
(
  IDSUPERVISORINTEGRAL STRING NOT NULL,
  CLAVESUPERVISOR STRING NOT NULL,
  NOMBRESUPERVISOR STRING NOT NULL,
  CORREO STRING NOT NULL,
  TELEFONO STRING NOT NULL,
  IDREGIONGEOGRAFICA STRING NOT NULL,
  ESTATUS BIGNUMERIC NOT NULL,
  FECHAREGISTRO DATETIME NOT NULL,
  FECHAACTUALIZACION DATETIME NOT NULL,
  USUARIOREGISTRO STRING NOT NULL
);

CREATE TABLE `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.VALUADOR`
(
  CODVALUADOR STRING NOT NULL,
  IDESTATUSVALUADOR STRING,
  IDREGION STRING,
  NOMBRE STRING,
  SESIONES NUMERIC,
  ENVIOVALES BIGNUMERIC,
  EQUIPOPESADO BIGNUMERIC,
  TIPOEQUIPOPESADO BIGNUMERIC,
  USUARIOHERRAMIENTA STRING,
  ACTIVARAUDACLAIMS BIGNUMERIC,
  OFICINA STRING,
  CENTROVALUACION STRING,
  ACTIVOVALUADOR BIGNUMERIC,
  USERGERENTE BIGNUMERIC,
  ACTIVARMITCHELL BIGNUMERIC,
  IDCATEGORIA STRING,
  IDREGIONGEOGRAFICA BIGNUMERIC,
  IDAUTORIZADOR STRING,
  CORREO STRING,
  TELEFONO STRING,
  USERCOORDINADOR NUMERIC,
  POOLASIGNACIONACG STRING
);