
PROC SQL;
   CREATE TABLE WORK.SUPERVISOR_SEGUIMENTO AS 
   SELECT t1.CLAVESUPERVISOR LABEL="CLAVE" AS CLAVE, 
          t1.NOMBRESUPERVISOR LABEL="USUARIO" AS USUARIO
      FROM VALPROD.SUPERVISORINTEGRAL t1
      WHERE UPCASE(t1.CLAVESUPERVISOR) LIKE '%SUPSEGQ%'
      ORDER BY t1.NOMBRESUPERVISOR;
QUIT;

PROC SQL;
   CREATE TABLE WORK.SUPERVISOR_SERVICIOS AS 
   SELECT t1.CLAVEANALISTA LABEL="CLAVE" AS CLAVE, 
          t1.NOMBRENNALISTA LABEL="USUARIO" AS USUARIO
      FROM VALPROD.ANALISTACDR t1
      WHERE UPCASE(t1.CLAVEANALISTA) LIKE '%SUPQ%'
      ORDER BY t1.CLAVEANALISTA;
QUIT;

PROC SQL;
   CREATE TABLE WORK.SS1 AS 
   SELECT t1.CLAVEANALISTA LABEL="CLAVE" AS CLAVE, 
          t1.NOMBRENNALISTA LABEL="USUARIO" AS USUARIO
      FROM VALPROD.ANALISTACDR t1
      WHERE UPCASE(t1.CLAVEANALISTA) LIKE '%ADMINCDR%';
QUIT;

PROC SQL;
   CREATE TABLE WORK.ASR AS 
   SELECT t1.IDADMINISTRADORREFACCIONES LABEL="CLAVE" AS CLAVE, 
          t1.NOMBRE LABEL="USUARIO" AS USUARIO
      FROM VALPROD.ADMINISTRADORREFACCIONES t1
      WHERE UPCASE(t1.IDADMINISTRADORREFACCIONES) LIKE '%ASR%'
      ORDER BY t1.NOMBRE;
QUIT;

PROC SQL;
   CREATE TABLE WORK.COMP AS 
   SELECT t1.IDADMINISTRADORREFACCIONES LABEL="CLAVE" AS CLAVE, 
          t1.NOMBRE LABEL="USUARIO" AS USUARIO
      FROM VALPROD.ADMINISTRADORREFACCIONES t1
      WHERE UPCASE(t1.IDADMINISTRADORREFACCIONES) LIKE '%ADMINREFC%';
QUIT;

PROC SQL;
   CREATE TABLE WORK.admin AS 
   SELECT t1.IDADMINISTRADORREFACCIONES LABEL="CLAVE" AS CLAVE, 
          t1.NOMBRE LABEL="USUARIO" AS USUARIO
      FROM VALPROD.ADMINISTRADORREFACCIONES t1
      WHERE UPCASE(t1.IDADMINISTRADORREFACCIONES) LIKE '%ADMIN%';
QUIT;

PROC SQL;
   CREATE TABLE WORK.PERSONALIZADO AS 
   SELECT t1.IDADMINISTRADORREFACCIONES LABEL="CLAVE" AS CLAVE, 
          t1.NOMBRE LABEL="USUARIO" AS USUARIO
      FROM VALPROD.ADMINISTRADORREFACCIONES t1
      WHERE t1.IDADMINISTRADORREFACCIONES IN 
           (
           'msalazar',
           'otoledo',
           'KGONZALEZ'
           );
QUIT;

PROC SQL;
   CREATE TABLE WORK.CORCOMSEG AS 
   SELECT t1.IDADMINISTRADORREFACCIONES LABEL='' AS CLAVE, 
          t1.NOMBRE LABEL='' AS USUARIO
      FROM VALPROD.ADMINISTRADORREFACCIONES t1
      WHERE upcase(t1.IDADMINISTRADORREFACCIONES) like '%CORCOMSEG%';
QUIT;

PROC SQL;
   CREATE TABLE WORK.VALUADORES AS 
   SELECT t1.CODVALUADOR LABEL="CLAVE" AS CLAVE, 
          t3.Nombre LABEL="USUARIO" AS USUARIO
      FROM VALPROD.VALUADOR t1
           LEFT JOIN BSC_SINI.Prestadores t3 ON (t1.CODVALUADOR = t3.Id)
      WHERE t3.Tipo = '45';
QUIT;

PROC SQL;
CREATE TABLE WORK.APPEND_TABLE_0005 AS 
SELECT * FROM WORK.SUPERVISOR_SEGUIMENTO
 OUTER UNION CORR 
SELECT * FROM WORK.SUPERVISOR_SERVICIOS
 OUTER UNION CORR 
SELECT * FROM WORK.VALUADORES
 OUTER UNION CORR 
SELECT * FROM WORK.SS1
 OUTER UNION CORR 
SELECT * FROM WORK.COMP
 OUTER UNION CORR 
SELECT * FROM WORK.ADMIN
 OUTER UNION CORR 
SELECT * FROM WORK.ASR
 OUTER UNION CORR 
SELECT * FROM WORK.PERSONALIZADO
 OUTER UNION CORR 
SELECT * FROM WORK.CORCOMSEG
;
Quit;

PROC SQL;
   CREATE TABLE CONVENB.usuariohomologado AS 
   SELECT DISTINCT t1.CLAVE LABEL="UsuarioBase" AS UsuarioBase, 
          t1.USUARIO LABEL="UsuarioHomologado" AS UsuarioHomologado
      FROM WORK.APPEND_TABLE_0005 t1;
QUIT;