SELECT  
NULL AS ASEGURADO_GR
,NULL AS ASEGURADO
,NULL AS RFC_ASEG
,NULL AS ASEG
,NULL AS CP
,NULL AS FEC_NACIMIENTO
,NULL AS FEC_EMI
,NULL AS TIPO_PERSONA
,NULL AS NOMBRE
,NULL AS AP_PATERNO
,NULL AS AP_MATERNO
,NULL AS RFC_CONTRATANTE
,NULL AS CORREO
,NULL AS CORRERO_STND
,NULL AS TELEFONO
,NULL AS TELEFONO_STND
,NULL AS LAST_UPDATE_TIME
--