BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_AGENTES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_AGENTES (
  CODIGO_OFICINA VARCHAR2(16),
  CODIGO_GERENTE VARCHAR2(16),
  CODIGO_AGENTE VARCHAR2(16),
  AGENTE VARCHAR2(256)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_ANALISTA_CDR CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_ANALISTA_CDR
(
    IDANALISTACDR           VARCHAR2(4000) NOT NULL,
    CLAVEANALISTA           VARCHAR2(4000) NOT NULL,
    NOMBRENNALISTA          VARCHAR2(4000) NOT NULL,
    ESTATUS                 NUMBER NOT NULL,
    IDREGIONGEOGRAFICA      VARCHAR2(4000) NOT NULL,
    FECHAREGISTROANL        DATE NOT NULL,
    FECHAACTUALIZACIONANL   DATE,
    CORREO                  VARCHAR2(4000),
    TELEFONO                VARCHAR2(4000),
    CONSULTA                NUMBER
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_APERCAB CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_APERCAB (
    REPORTE VARCHAR2(4000),
    SINIESTRO VARCHAR2(4000),
    CLAVE_AJUSTADOR VARCHAR2(4000),
    FECHA_REPORTE DATE,
    HORA_REPORTE DATE,
    FECHA_PASADO DATE,
    HORA_PASADO DATE,
    TIEMPO_PASADO NUMBER,
    FECHA_LLEGADA DATE,
    HORA_LLEGADA DATE,
    TIEMPO_ARRIBO NUMBER,
    FECHA_TERMINO DATE,
    HORA_TERMINO DATE,
    TIEMPO_AJUSTE NUMBER,
    TIEMPO_ATENCION NUMBER,
    OFICINA_VTA VARCHAR2(4000),
    CAUSA VARCHAR2(4000),
    CABINISTA VARCHAR2(4000),
    SUBR VARCHAR2(4000),
    TR_CARR VARCHAR2(4000),
    CLAVE_AGENTE VARCHAR2(4000),
    REPORTE_OK NUMBER,
    HORARIO VARCHAR2(4000),
    LUGAR_ACCIDENTE VARCHAR2(4000),
    RANGO_ARRIBO VARCHAR2(4000),
    FECHA_REGISTRO DATE,
    CONTROL_SINIESTROS NUMBER,
    FECHA_HORA_REPORTE VARCHAR2(4000),
    FECHA_HORA_ASIGNACION VARCHAR2(4000),
    FECHA_HORA_ARRIBO VARCHAR2(4000),
    FECHA_HORA_TERMINO VARCHAR2(4000),
    ASIGNACION NUMBER,
    ARRIBO NUMBER,
    NUMERO_REPORTE NUMBER,
    POLIZA VARCHAR2(4000),
    CONDUCTOR VARCHAR2(4000),
    CODIGO_ESTADO_ACCIDENTE VARCHAR2(4000),
    REINGENIERIA VARCHAR2(4000),
    GEOLOCALIZACION NUMBER,
    GEOUBICACION NUMBER,
    GEOASIGNACION NUMBER,
    CODIGO_POBLACION_ACCIDENTE VARCHAR2(4000),
    CLAVE_CABINISTA VARCHAR2(4000),
    TIPO_EVENTO NUMBER,
    REIN NUMBER,
    HORA_INICIO_CAPTURA DATE,
    FECHA_INICIO_CAPTURA DATE,
    HORA_INICIO DATE,
    HORA_TERMINO_2 DATE,
    AJU_GA VARCHAR2(4000),
    GEOASIGR VARCHAR2(4000),
    TIPO_ROBO VARCHAR2(4000),
    EVTO_ESP VARCHAR2(4000),
    NOMBRE_ASEGURADO VARCHAR2(4000),
    CLAVE_NAGS VARCHAR2(4000),
    SEGURO_TERCERO NUMBER,
    ASEGURADO VARCHAR2(4000),
    TIP_RESP_ORI VARCHAR2(4000),
    INGRESO NUMBER,
    CRM NUMBER,
    TIPO_VEHICULO VARCHAR2(4000),
    MODELO_VEHICULO VARCHAR2(4000),
    PLACAS_VEHICULO VARCHAR2(4000),
    SERIE_VEHICULO VARCHAR2(4000),
    ORGANISMO VARCHAR2(4000),
    NUMERO_ECO VARCHAR2(4000),
    CALIDAD NUMBER,
    CODIGO_PRES VARCHAR2(4000),
    CODIGO_RESPUESTA VARCHAR2(4000),
    LATITUD NUMBER,
    LONGITUD NUMBER,
    CLAVE_ABOGADO VARCHAR2(4000),
    EXCLUIR NUMBER,
    RESERVA_INICIAL NUMBER,
    TODAY NUMBER,
    COLAS VARCHAR2(4000),
    DIA_SEMANA NUMBER,
    FECHA_OCURRIDO DATE,
    NUMERO_REC NUMBER,
    PROVINCIA_REC VARCHAR2(4000),
    ULTREC NUMBER,
    CORREO VARCHAR2(4000),
    LESIONADOS NUMBER,
    NUMERO_LESIONADOS VARCHAR2(4000),
    CORREO_VALIDO NUMBER,
    MARCA_ASEG VARCHAR2(4000),
    HORA_OCURRIDO DATE,
    GRUA VARCHAR2(4000),
    PASEM VARCHAR2(4000),
    TIPO_POLIZA VARCHAR2(4000),
    TIEMPO_PAGO_PT NUMBER,
    ETA NUMBER,
    EXTEMP VARCHAR2(4000),
    COND_NOMBRE VARCHAR2(4000),
    COND_PATERNO VARCHAR2(4000),
    COND_MATERNO VARCHAR2(4000),
    SINPOL VARCHAR2(4000),
    CATEGORIA VARCHAR2(4000),
    GEOTEL VARCHAR2(4000),
    GEORAD VARCHAR2(4000),
    TOKEN VARCHAR2(4000)
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_ASEGURADOS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_ASEGURADOS (
    ID VARCHAR2(4000),
    NOMBRE VARCHAR2(4000),
    GIRO VARCHAR2(4000),
    NACIONALIDAD VARCHAR2(4000),
    FOLIO VARCHAR2(4000),
    APODERADO VARCHAR2(4000),
    NACIMIENTO_APODERADO VARCHAR2(4000),
    RFC VARCHAR2(4000),
    ART_140 VARCHAR2(4000),
    FECHA_NACIMIENTO DATE,
    FECHA_ALTA DATE,
    TIPO_ASEGURADOS VARCHAR2(4000),
    CORREO VARCHAR2(4000),
    CURP VARCHAR2(4000),
    ID_OFICINA VARCHAR2(4000),
    NOMBRE_OFICINA VARCHAR2(4000)
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_CAUSA_CAMBIO_VALE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE SASPRVFRAP.STG_CAUSA_CAMBIO_VALE
(
    IDCAUSACAMBIOVALE       VARCHAR2(4000) NOT NULL,
    DESCRIPCION             VARCHAR2(4000) NOT NULL,
    FECHAREGISTRO           DATE NOT NULL,
    FECHAACTUALIZACION      DATE NOT NULL,
    USUARIO                 VARCHAR2(4000) NOT NULL
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_CAUSAS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Tabla DM_CAUSAS
CREATE TABLE SASPRVFRAP.STG_CAUSAS (
    ID VARCHAR2(50),
    CAUSA VARCHAR2(255),
    CAUSA_HOMOLOGADA VARCHAR2(255),
    FECHA_LOTE DATE,
    ID_USUARIO_SISTEMA VARCHAR2(50)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_CERCO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_CERCO
(
    IDCERCO                 VARCHAR2(4000),
    NOMBRE                  VARCHAR2(4000),
    FECHAREGISTRO           DATE,
    FECHAACTUALIZACION      DATE,
    IDENTIDAD               VARCHAR2(4000),
    SUSPAUT                 VARCHAR2(4000),
    IDCATEGORIACERCO        VARCHAR2(4000),
    IDSEGMENTACION          VARCHAR2(4000)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_COBERTURAS_MOVIMIENTOS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_COBERTURAS_MOVIMIENTOS (
    ID VARCHAR2(4000),
    RAMO VARCHAR2(4000),
    SUBRAMO VARCHAR2(4000),
    SINIESTRO VARCHAR2(4000),
    TIPO_SINIESTRO VARCHAR2(4000),
    ID_OFICINA_VENTAS VARCHAR2(4000),
    GERENTE VARCHAR2(4000),
    AGENTE VARCHAR2(4000),
    ID_OFICINA_DE_ATENCION VARCHAR2(4000),
    AJUSTADOR VARCHAR2(4000),
    FECHA_REGISTRO DATE,
    FECHA_MOVIMIENTO DATE,
    TIPO_MOVIMIENTO VARCHAR2(4000),
    GASTO VARCHAR2(4000),
    TIPO_MONEDA VARCHAR2(4000),
    COBERTURA VARCHAR2(4000),
    IMPORTE NUMBER,
    CAPUFE NUMBER,
    CODIGO_COBERTURA VARCHAR2(4000),
    CODIGO_TEXTO VARCHAR2(4000),
    TIPO_CAMBIO NUMBER,
    REPORTE VARCHAR2(4000),
    USUARIO VARCHAR2(4000),
    POLIZA VARCHAR2(4000),
    RELEVANTES VARCHAR2(4000),
    FECHA_OCURRIDO DATE,
    TIPO_VEHICULO VARCHAR2(4000),
    MODELO_VEHICULO VARCHAR2(4000),
    CSTROS NUMBER,
    CRVA_INICIAL NUMBER,
    IRVA_INICIAL NUMBER,
    CAJMAS NUMBER,
    IAJMAS NUMBER,
    CAJMENOS NUMBER,
    IAJMENOS NUMBER,
    CPAGOS NUMBER,
    IPAGOS NUMBER,
    CGASTO NUMBER,
    IGASTO NUMBER,
    CDED NUMBER,
    IREC NUMBER,
    CSALV NUMBER,
    ISALV NUMBER,
    FLAG_REC VARCHAR2(4000),
    COD_RESP VARCHAR2(4000),
    DEPRES1 VARCHAR2(4000),
    DEPRES2 VARCHAR2(4000),
    DEPRES3 VARCHAR2(4000),
    DEPRESLIT VARCHAR2(4000),
    MONTO_INDEM_RECUP NUMBER,
    MONTO_INDEM_RECUP_DM NUMBER,
    IMPORTE_MN NUMBER,
    IRVA_INICIAL_MN NUMBER,
    IAJMASMN NUMBER,
    IAJMENOSMN NUMBER,
    IPAGOSMN NUMBER,
    IGASTOMN NUMBER,
    IDEDMN NUMBER,
    IRECMN NUMBER,
    ISALVMN NUMBER,
    MARCA_RVA VARCHAR2(4000),
    COAS NUMBER,
    NOMBRE_ASEGURADORA VARCHAR2(4000),
    CODIGO_POBLACION_ACC VARCHAR2(4000),
    REC_CANTO NUMBER,
    INVSALV VARCHAR2(4000),
    CODIGO_ESTADO_ACC VARCHAR2(4000),
    SINIESDIA NUMBER,
    CLAVE_ABOGADO VARCHAR2(4000)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_COLOR CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE 	SASPRVFRAP.STG_COLOR
(
    IDCOLOR                 VARCHAR2(4000),
    DESCRIPCION             VARCHAR2(4000),
    ALTA                    DATE,
    ACTUALIZACION           DATE,
    USUARIOACTUALIZA        VARCHAR2(4000)
);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_COMPLEMENTO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_COMPLEMENTO
(
    IDCOMPLEMENTO               VARCHAR2(4000),
    IDEXPEDIENTE                NUMBER,
    CODPROVEEDOR                VARCHAR2(4000),
    IDREFACCION                 VARCHAR2(4000),
    CONCEPTO                    VARCHAR2(4000),
    FECHA                       DATE,
    MONTO                       NUMBER,
    DESCRIPCION                 VARCHAR2(4000),
    REFERENCIA                  VARCHAR2(4000),
    LISTA                       VARCHAR2(4000),
    NUMPARTE                    VARCHAR2(4000),
    FECHAACTUALIZACION          DATE,
    DEMERITO                    NUMBER,
    OBSERVACIONES               VARCHAR2(4000),
    FECRECEPCION                DATE,
    COTIZADO                    VARCHAR2(4000),
    FECSURTIDO                  DATE,
    ORIGENANTERIOR              VARCHAR2(4000),
    IDTIPOTOT                   VARCHAR2(4000),
    ADMINREF                    VARCHAR2(4000),
    PIEZAPAQUETE                NUMBER,
    MONTOCONVENIO               NUMBER,
    PORCENTAJEADQUISICION       NUMBER,
    IDTRUCKEST                  NUMBER,
    FECHAENVIO                  DATE,
    NUMEROGUIA                  VARCHAR2(4000),
    MENSAJERIA                  VARCHAR2(4000),
    BLOQUEOREFACCION            NUMBER,
    FECASIGNACIONMANUAL         DATE,
    FECASIGNACIONDIRECTA        DATE,
    IDDEDUCIBLECOBERTURA        NUMBER,
    IDDEMERITOTIPO              VARCHAR2(4000),
    ORIGENSOLICITADO            VARCHAR2(4000),
    PENDIENTEAUTORIZAR          NUMBER,
    CLAVENAGS                   VARCHAR2(4000),
    BLINDAJE                    NUMBER NOT NULL,
    IDCAUSACAMBIOVALE           VARCHAR2(4000),
    ORIGENINICIAL               VARCHAR2(4000),
    ORIGENVALUADOR              VARCHAR2(4000),
    FECHACHATARRA               DATE,
    CANTIDAD                    VARCHAR2(4000),
    MOTIVONORECCHATARRA         VARCHAR2(4000),
    NUMPARTEVALUADOR            VARCHAR2(4000),
    ID_REF_COSTO_MEDIO          VARCHAR2(4000),
    IDDISPONIBILIDAD            VARCHAR2(4000),
    IDCAUSACANCELARPIEZA        VARCHAR2(4000),
    FECHACANCELACION            DATE
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_DATOS_GENERALES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_DATOS_GENERALES (
    ID VARCHAR2(4000),
    ID_EXPEDIENTE NUMBER,
    ID_ORIGEN VARCHAR2(4000),
    ID_IVA VARCHAR2(4000),
    ID_VALUACION VARCHAR2(4000),
    CLAVE_CAUSA_DIF VARCHAR2(4000),
    ID_RIESGO VARCHAR2(4000),
    NUMERO_POLIZA VARCHAR2(4000),
    NUMERO_ENDOSO VARCHAR2(4000),
    NUMERO_INCISO VARCHAR2(4000),
    NUMERO_REPORTE VARCHAR2(4000),
    NUMERO_SINIESTRO VARCHAR2(4000),
    CODIGO_RAMO VARCHAR2(4000),
    EJERCICIO VARCHAR2(4000),
    CODIGO_SEGUIMIENTO VARCHAR2(4000),
    CODIGO_AFECTADO VARCHAR2(4000),
    NOMBRE_CONDUCTOR VARCHAR2(4000),
    STATUS_DOCUMENTO VARCHAR2(4000),
    CLAVE_TALLER VARCHAR2(4000),
    TIPO_PROVEEDOR VARCHAR2(4000),
    CODIGO_VALUADOR VARCHAR2(4000),
    SUMA_ASEGURADA BINARY_DOUBLE,
    PORCENTAJE_COSTOS BINARY_DOUBLE,
    MONTO_DEDUCIBLE BINARY_DOUBLE,
    MONTO_COSTOS BINARY_DOUBLE,
    MONTO_COMP BINARY_DOUBLE,
    MONTO_TOTS BINARY_DOUBLE,
    REPARACION NUMBER,
    MONTO_REPARACION BINARY_DOUBLE,
    PAGO_DANOS NUMBER,
    MONTO_PD BINARY_DOUBLE,
    PERDIDA_TOTAL NUMBER,
    MONTO_PT BINARY_DOUBLE,
    USUARIO VARCHAR2(4000),
    ORIGEN VARCHAR2(4000),
    CLAVE_ORIGEN VARCHAR2(4000),
    ABONADO VARCHAR2(4000),
    SISTEMA_CAPTURA VARCHAR2(4000),
    SISTEMA_CLAVE VARCHAR2(4000),
    OBSERVACIONES VARCHAR2(4000),
    TIPO_RIESGO VARCHAR2(4000),
    OFICINA VARCHAR2(4000),
    REF_TALLER VARCHAR2(4000),
    PORCENTAJE_DEDUCIBLE BINARY_DOUBLE,
    OBSERVACIONES_DEDUCIBLE VARCHAR2(4000),
    CLAVE_TALLER_ANTERIOR VARCHAR2(4000),
    AUTORIZADO_ADMIN NUMBER,
    PRESUPUESTO_MOB BINARY_DOUBLE,
    PIEZAS_CAMBIO NUMBER,
    FOLIO_CABINA VARCHAR2(4000),
    OBSERVACIONES_PT VARCHAR2(4000),
    VEHICULO_REPARABLE NUMBER,
    ID_CAUSA_PT VARCHAR2(4000),
    CONSECUTIVO VARCHAR2(4000),
    MONTO_RESCATE_PT BINARY_DOUBLE,
    RESCATE_PT NUMBER,
    ID_COBERTURA_TIPO VARCHAR2(4000),
    CODIGO_VALUADOR_COMPLEMENTO VARCHAR2(4000),
    FOLIO_ORDEN_ADMISION_DE VARCHAR2(4000),
    SOLICITANTE_DE VARCHAR2(4000),
    PERDIDA_TOTAL_EVIDENTE NUMBER,
    DEDUCIBLE_MODIFICADO NUMBER,
    PAGO_ANTICIPADO NUMBER,
    FOLIO_MO VARCHAR2(4000),
    AGENTE VARCHAR2(4000),
    CODIGO_ASEGURADO VARCHAR2(4000),
    ID_CODIGO_EVENTO VARCHAR2(4000),
    CODIGO_VALUADOR_MASTER_PT VARCHAR2(4000),
    CODIGO_VALUADOR_INICIAL VARCHAR2(4000),
    ID_VALUACION_INICIAL VARCHAR2(4000),
    ID_VALUACION_PT_INICIAL VARCHAR2(4000),
    ESTATUS_INICIAL_ENVIO VARCHAR2(4000),
    ESTATUS_FINAL_ENVIO VARCHAR2(4000),
    ESTATUS_GRUA NUMBER,
    DIRECCION_GRUA VARCHAR2(4000),
    SYNC_SALVAMENTOS VARCHAR2(4000),
    CANCELA_PT VARCHAR2(4000),
    ESTATUS_PT VARCHAR2(4000),
    GRANIZADOS VARCHAR2(4000),
    MOTIVO_AX VARCHAR2(4000),
    SUBRAMO VARCHAR2(4000),
    REC_CHATARRA VARCHAR2(4000),
    CONV_COSTO_MEDIO VARCHAR2(4000),
    MNT_COSTO_MEDIO BINARY_DOUBLE,
    MONTO_ESTIMACION_PT VARCHAR2(4000),
    CAUSA_CODIGO VARCHAR2(4000),
    CAUSA_DESCRIPCION VARCHAR2(4000),
    OFICINA_EMISION_CODIGO VARCHAR2(4000),
    OFICINA_EMISION_DESCRIPCION VARCHAR2(4000),
    RESP_VALUADOR_CM VARCHAR2(4000),
    RESPONSABLE VARCHAR2(4000),
    CARRIL_EXPRESS VARCHAR2(4000),
    RESPUESTA_COORD_CM VARCHAR2(4000),
    AUT_CON_CM VARCHAR2(4000),
    RESPUESTA_VALUADOR_COMBO_CMPL_CM VARCHAR2(4000),
    SELECC_REF_VALUADOR_CM VARCHAR2(4000),
    CANCELO_REF_VALUADOR VARCHAR2(4000),
    ID_COMPLEMENTO_CM VARCHAR2(4000),
    ACTIVAR_FECHA_ESTENT NUMBER,
    DANO_MENOR_DEDU VARCHAR2(4000),
    CODIGO_RECUPERACION VARCHAR2(4000),
    USUARIO_LIB_CHATARRA VARCHAR2(4000),
    MARCA_PTENPDD NUMBER,
    DEDUCIBLE_CRMJ VARCHAR2(4000),
    TEL_ORDEN VARCHAR2(4000),
    CORREO VARCHAR2(4000),
    CONDUCTOR VARCHAR2(4000),
    DEDU_ADMIN VARCHAR2(4000),
    FOTOS_DIGITAL_PRO VARCHAR2(4000)
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_DATOS_VEHICULO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_DATOS_VEHICULO
(
    IDDATOSVEHICULO         VARCHAR2(4000),
    IDEXPEDIENTE            VARCHAR2(4000),
    IDVEHICULO              VARCHAR2(4000),
    IDUSO                   VARCHAR2(4000),
    IDMARCA                 VARCHAR2(4000),
    IDCOLOR                 VARCHAR2(4000),
    CVESUBMARCA             VARCHAR2(4000),
    CVEAMIS                 VARCHAR2(4000),
    TIPO                    VARCHAR2(4000),
    MODELO                  VARCHAR2(4000),
    PLACAS                  VARCHAR2(4000),
    SERIE                   VARCHAR2(4000),
    MOTOR                   VARCHAR2(4000),
    USOAMIS                 VARCHAR2(4000),
    PLACASANTERIOR          VARCHAR2(4000),
    SERIEANTERIOR           VARCHAR2(4000),
    IDUNIDAD                VARCHAR2(4000),
    IDMARCATALLER           VARCHAR2(4000)
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_DUA CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE SASPRVFRAP.STG_DUA (
    DU_NUM_REPORTE VARCHAR2(4000),
    PROCESO NUMBER(19),
    ENVIADO_EMAIL NUMBER(19),
    CHECK_2 NUMBER(19),
    CHECK_3 NUMBER(19),
    CHECK_4 NUMBER(19),
    DU_ID NUMBER(19),
    CHECK_5 NUMBER(19),
    CHECK_6 NUMBER(19),
    DU_RESPONSABLE_A NUMBER(19),
    DU_SIPAC NUMBER(19),
    DU_EN_ESPERA NUMBER(19),
    DU_VOLANTE_ADMISON NUMBER(19),
    DU_VEHICUO_CORRALON NUMBER(19),
    DU_TRADICIONAL_ENT NUMBER(19),
    DU_TRADICIONAL_REC NUMBER(19),
    DU_SIPAC_ENT NUMBER(19),
    DU_SIPAC_REC NUMBER(19),
    DU_OTROS_REC NUMBER(19),
    DU_OTROS_ENT NUMBER(19),
    DU_ESTADO_AJUSTE NUMBER(19),
    DU_INFORME_ADICIONAL NUMBER(19),
    DU_PREGUNTA_1A NUMBER(19),
    DU_PREGUNTA_2A NUMBER(19),
    DU_PREGUNTA_3A NUMBER(19),
    DU_PREGUNTA_4A NUMBER(19),
    DU_PREGUNTA_5A NUMBER(19),
    DU_PREGUNTA_6A NUMBER(19),
    DU_PREGUNTA_7A NUMBER(19),
    DU_PREGUNTA_8A NUMBER(19),
    DU_PREGUNTA_9A NUMBER(19),
    DU_PREGUNTA_10A NUMBER(19),
    DU_PREGUNTA_11A NUMBER(19),
    DU_PREGUNTA_12A NUMBER(19),
    DU_PREGUNTA_13A NUMBER(19),
    DU_PREGUNTA_14A NUMBER(19),
    DU_PREGUNTA_15A NUMBER(19),
    DU_PREGUNTA_16A NUMBER(19),
    DU_PREGUNTA_17A NUMBER(19),
    DU_PREGUNTA_18A NUMBER(19),
    DU_PREGUNTA_19A NUMBER(19),
    DU_PREGUNTA_1B NUMBER(19),
    DU_PREGUNTA_2B NUMBER(19),
    DU_PREGUNTA_3B NUMBER(19),
    DU_PREGUNTA_4B NUMBER(19),
    DU_PREGUNTA_5B NUMBER(19),
    DU_PREGUNTA_6B NUMBER(19),
    DU_PREGUNTA_7B NUMBER(19),
    DU_PREGUNTA_8B NUMBER(19),
    DU_PREGUNTA_9B NUMBER(19),
    DU_PREGUNTA_10B NUMBER(19),
    DU_PREGUNTA_11B NUMBER(19),
    DU_PREGUNTA_12B NUMBER(19),
    DU_PREGUNTA_13B NUMBER(19),
    DU_PREGUNTA_14B NUMBER(19),
    DU_PREGUNTA_15B NUMBER(19),
    DU_PREGUNTA_16B NUMBER(19),
    DU_PREGUNTA_17B NUMBER(19),
    DU_PREGUNTA_18B NUMBER(19),
    DU_PREGUNTA_19B NUMBER(19),
    ENVIADO_FTP NUMBER(19),
    DU_PREGUNTA_A_BOOL NUMBER(19),
    DU_PREGUNTA_B_BOOL NUMBER(19),
    CHECK_1 NUMBER(19),
    HORA_ENVIO_EMAIL DATE,
    DU_HORA_ABOGADO DATE,
    DU_FECHA_OCURRIDO DATE,
    DU_FECHA_ATENCION DATE,
    DU_VIGENCIA_DE DATE,
    DU_VIGENCIA_AL DATE,
    DU_CADUCIDAD_LICENCIA DATE,
    DU_ARRIBO_AJUSTADOR DATE,
    DU_TERMINO_AJUSTADOR DATE,
    DU_FECHA_OCURRIDO_B DATE,
    DU_FECHA_ATENCION_B DATE,
    DU_VIGENCIA_DE_B DATE,
    DU_VIGENCIA_AL_B DATE,
    DU_CADUCIDAD_LICENCIA_B DATE,
    DU_ARRIBO_AJUSTADOR_B DATE,
    DU_TERMINO_AJUSTADOR_B DATE,
    DU_HORA_GRUA DATE,
    DU_HORA_AMBULANCIA DATE,
    HORA_ENVIO_SFTP DATE,
    DU_COBERTURA VARCHAR2(4000),
    DU_USO_AUTO_B VARCHAR2(4000),
    DU_TEL_ASEGURADO VARCHAR2(4000),
    DU_TEL_CONDUCTOR VARCHAR2(4000),
    DU_LICENCIA_NUM VARCHAR2(4000),
    DU_LICENCIA_ESTADO VARCHAR2(4000),
    DU_COBRANZA VARCHAR2(4000),
    DU_USO_AUTO_A VARCHAR2(4000),
    DU_PREGUNTA_A VARCHAR2(4000),
    DU_CONDICIONADO_A VARCHAR2(4000),
    DU_OTROS VARCHAR2(4000),
    DU_COLOR_AUTO VARCHAR2(4000),
    DU_PLACAS_AUTO VARCHAR2(4000),
    DU_SERIE VARCHAR2(4000),
    DU_COBERTURA_B VARCHAR2(4000),
    DU_COBRANZA_B VARCHAR2(4000),
    DU_TEL_CONDUCTOR_B VARCHAR2(4000),
    DU_LICENCIA_NUM_B VARCHAR2(4000),
    DU_LICENCIA_ESTADO_B VARCHAR2(4000),
    DU_COLOR_AUTO_B VARCHAR2(4000),
    DU_PLACAS_AUTO_B VARCHAR2(4000),
    DU_SERIE_B VARCHAR2(4000),
    DU_TEL_ASEGURADO_B VARCHAR2(4000),
    DU_TIPO_LICENCIA_B VARCHAR2(4000),
    DU_TIPO_LICENCIA VARCHAR2(4000),
    DU_AUTORIDAD VARCHAR2(4000),
    DU_CONCLUSIONES VARCHAR2(4000),
    DU_APLICO_DEDUCIBLE VARCHAR2(4000),
    DU_NOM_CIA VARCHAR2(4000),
    DU_MARCA_AUTO VARCHAR2(4000),
    DU_TIPO_AUTO VARCHAR2(4000),
    DU_NOM_CIA_B VARCHAR2(4000),
    DU_MARCA_AUTO_B VARCHAR2(4000),
    DU_TIPO_AUTO_B VARCHAR2(4000),
    DU_NOM_AJUSTADOR VARCHAR2(4000),
    DU_NOM_AJUSTADOR_B VARCHAR2(4000),
    DU_NOM_ABOGADO VARCHAR2(4000),
    DU_NOM_SUPERVISOR VARCHAR2(4000),
    DU_NOM_AJUSTADOR_GRAL VARCHAR2(4000),
    DU_MODELO_AUTO_A VARCHAR2(4000),
    DU_MODELO_AUTO_B VARCHAR2(4000),
    DU_NOM_CONDUCTOR_B VARCHAR2(4000),
    DU_NOM_ASEGURADO_B VARCHAR2(4000),
    DU_NOM_CONDUCTOR VARCHAR2(4000),
    DU_NOM_ASEGURADO VARCHAR2(4000),
    DU_DESCRIPCION_CROQUIS VARCHAR2(4000),
    FTP_RESPUESTA VARCHAR2(4000),
    CORREO_OCULTO VARCHAR2(4000),
    DU_FOLIO_INFORME VARCHAR2(4000),
    NODO_ENVIO VARCHAR2(4000),
    MENSAJES_EMAIL VARCHAR2(4000),
    FUENTE_WS VARCHAR2(4000),
    DU_EDAD_CONDUCTOR VARCHAR2(4000),
    DU_NUM_PERSONAS VARCHAR2(4000),
    DU_NUM_OCUPANTES VARCHAR2(4000),
    DU_EDAD_CONDUCTOR_B VARCHAR2(4000),
    DU_NUM_RC VARCHAR2(4000),
    DU_NUM_PERSONALES VARCHAR2(4000),
    DU_NUM_SINIESTRO_B VARCHAR2(4000),
    DU_NUM_REPORTE_B VARCHAR2(4000),
    DU_CLAVE_AJUSTADOR VARCHAR2(4000),
    DU_CLAVE_AJUSTADOR_B VARCHAR2(4000),
    DU_RECUPERACION VARCHAR2(4000),
    DU_NUM_ACTA VARCHAR2(4000),
    DU_NUM_REPORTE_AUT VARCHAR2(4000),
    DU_DANIOS_MATERIALES VARCHAR2(4000),
    DU_EQUIPO_ESPECIAL VARCHAR2(4000),
    DU_ROBO_TOTAL VARCHAR2(4000),
    DU_RES_BIENES VARCHAR2(4000),
    DU_RES_PERSONAS VARCHAR2(4000),
    DU_GASTOS_MEDICOS VARCHAR2(4000),
    DU_INC_B VARCHAR2(4000),
    DU_NUM_POLIZA_B VARCHAR2(4000),
    DU_NUM_SINIESTRO VARCHAR2(4000),
    DU_INC VARCHAR2(4000),
    DU_CLAVE_AJUSTADOR_GRAL VARCHAR2(4000),
    DU_NUM_POLIZA VARCHAR2(4000),
    DU_NUM_ENDOSO VARCHAR2(4000),
    DU_NUM_INCISO VARCHAR2(4000),
    DU_GASTOS_LEGALES VARCHAR2(4000),
    DU_ACCI_PERSONALES VARCHAR2(4000),
    DU_RC_VIAJERO VARCHAR2(4000),
    DU_CRISTALES VARCHAR2(4000),
    DU_OTRO VARCHAR2(4000),
    DU_FOLIO VARCHAR2(4000),
    DU_CODIGO_RESPONSABILIDAD VARCHAR2(4000),
    DU_EMAIL_CONDUCTOR VARCHAR2(4000),
    DU_EMAIL_CONDUCTOR_B VARCHAR2(4000),
    DU_LUGAR VARCHAR2(4000),
    DU_DIR_CONDUCTOR_B VARCHAR2(4000),
    DU_LUGAR_B VARCHAR2(4000),
    DU_DIR_CONDUCTOR VARCHAR2(4000),
    DU_ASEGURADO VARCHAR2(4000),
    DU_DANIOS_PRE VARCHAR2(4000),
    DU_NARRACION_B VARCHAR2(4000),
    DU_DANIOS_APRE_B VARCHAR2(4000),
    DU_DANIOS_PRE_B VARCHAR2(4000),
    DU_OCUPANTE_1 VARCHAR2(4000),
    DU_OCUPANTE_2 VARCHAR2(4000),
    DU_OCUPANTE_3 VARCHAR2(4000),
    DU_OCUPANTE_4 VARCHAR2(4000),
    DU_OCUPANTE_5 VARCHAR2(4000),
    DU_OCUPANTE_1_B VARCHAR2(4000),
    DU_OCUPANTE_2_B VARCHAR2(4000),
    DU_OCUPANTE_3_B VARCHAR2(4000),
    DU_OCUPANTE_4_B VARCHAR2(4000),
    DU_OCUPANTE_5_B VARCHAR2(4000),
    DU_NARRACION VARCHAR2(4000),
    DU_DANIOS_APRE VARCHAR2(4000),
    DU_OTRO_ESPECIFICAR VARCHAR2(4000)
);




BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_ENVIO_HISTORICO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_ENVIO_HISTORICO
(
    IDENVIOHISTORICO            VARCHAR2(4000),
    IDEXPEDIENTE                VARCHAR2(4000),
    FECHAENVIOTALLER            DATE,
    FECHAASIGNACIONVALUADOR     DATE,
    FECHAAUTORIZACIONVALUADOR   DATE,
    DATO                        VARCHAR2(4000),
    IDCAUSAASIGNARCOMPLEMENTO   VARCHAR2(4000),
    AUTORIZADOAUTOMATICO        NUMBER,
    CODVALUADORCOMPLEMENTO      VARCHAR2(4000)
);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_ESTADO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_ESTADO
(
    IDESTADO                VARCHAR2(4000),
    NOMBRE                  VARCHAR2(4000),
    IDREGIONGEOGRAFICA      NUMBER,
    ACTIVO                  NUMBER
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_ESTADOS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_ESTADOS (
    ID VARCHAR2(4000),
    ESTADO_POBLACION VARCHAR2(4000),
    ESTATUS VARCHAR2(4000),
    CLAVE_INEGI VARCHAR2(4000),
    REGION VARCHAR2(4000),
    RADIO_PERFIL VARCHAR2(4000),
    ESTADO_ESTANDAR VARCHAR2(4000),
    ESTADO_POBLACION_2 VARCHAR2(4000),
    CODIGO_ESTADO VARCHAR2(2),
    ESTADO VARCHAR2(256)
);




BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_ESTATUS_EXPEDIENTES  CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
CREATE TABLE SASPRVFRAP.STG_ESTATUS_EXPEDIENTES
(
    IDESTATUSEXPEDIENTE     VARCHAR2(4000) NOT NULL,
    DESCRIPCION             VARCHAR2(4000),
    ALTA                    DATE,
    ACTUALIZACION           DATE,
    USUARIOACTUALIZA        VARCHAR2(4000)
);




BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_ESTATUS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_ESTATUS
(
    IDESTATUS                       VARCHAR2(4000),
    IDEXPEDIENTE                    VARCHAR2(4000),
    IDESTATUSEXPEDIENTE             VARCHAR2(4000),
    IDRECHAZO                       VARCHAR2(4000),
    IDPENDIENTE                     VARCHAR2(4000),
    TRANSITO                        NUMBER,
    PISO                            NUMBER,
    GRUA                            NUMBER,
    FECESTATUSEXPEDIENTE            DATE,
    MANUAL                          NUMBER,
    SISE                            NUMBER,
    ENVIOSSISE                      NUMBER,
    SISEMENSAJE                     VARCHAR2(4000),
    COTIZADOR                       NUMBER,
    COTIZADORESTATUS                VARCHAR2(4000),
    AUTORIZACIONCOORDINADOR         NUMBER,
    AUTORIZACIONUSUARIO             VARCHAR2(4000),
    PRESUPUESTOENHERRAMIENTA        NUMBER,
    ADMINREF                        VARCHAR2(4000),
    REASIGNADOVALUADOR              NUMBER,
    IDMOVOPERADOR                   VARCHAR2(4000),
    IDRECHAZOCOMPLEMENTO            VARCHAR2(4000),
    CAMBIOREGIONEXP                 VARCHAR2(4000),
    PROCESOHERRAMIENTA              NUMBER,
    VECESRECHAZADO                  NUMBER,
    PAGOANTICIPADO                  NUMBER,
    REVISIONMASTERPT                VARCHAR2(4000),
    IDRESCATEMASTERPT               VARCHAR2(4000),
    REVISIONBLINDAJES               VARCHAR2(4000),
    ENVIOSHERRAMIENTA               NUMBER,
    HISTOSINSINIESTRO               VARCHAR2(4000),
    HISTOINVESTIGACION              VARCHAR2(4000),
    FECSINSINIESTRO                 DATE,
    FECINVESTIGACION                DATE,
    HISTOACTUALIZACIONSINIESTRO     DATE,
    REGRESOVALEP                    VARCHAR2(4000),
    FECHACANCELACION                DATE,
    ISPIEZASCANCELADAS              VARCHAR2(4000),
    XNUUP                           NUMBER
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_ETIQUETA_SINIESTRO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Tabla DM_ETIQUETA_SINIESTRO (con referencias a DM_SINIESTROS)
CREATE TABLE SASPRVFRAP.STG_ETIQUETA_SINIESTRO (
    ID VARCHAR2(50),
    ID_REPORTE VARCHAR2(50),
    ID_SINIESTRO VARCHAR2(50),
    CODIGO_ESTATUS VARCHAR2(50),
    FECHA_INVESTIGACION DATE,
    TEXTO_INVESTIGACION VARCHAR2(4000),
    USUARIO_INVESTIGACION VARCHAR2(255),
    TEXTO_LOCALIZADO VARCHAR2(4000),
    FECHA_LOCALIZADO DATE,
    FECHA_CARGA DATE,
    FECHA_LOTE DATE,
    ID_USUARIO_SISTEMA VARCHAR2(50),
    CONSECUTIVO NUMBER(19),
    VALIDO_DESDE DATE,
    VALIDO_HASTA DATE,
    VALIDO NUMBER(1)
);




BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_FECHAS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_FECHAS
(
    IDFECHAS                        VARCHAR2(4000),
    IDEXPEDIENTE                    VARCHAR2(4000),
    FECASIGNACION                   DATE,
    FECADJUDICACION                 DATE,
    FECINGRESO                      DATE,
    FECVALUACION                    DATE,
    FECTERMINADO                    DATE,
    FECENTREGADO                    DATE,
    FECREGISTRO                     DATE,
    FECENVIO                        DATE,
    DIASREPARACION                  NUMBER,
    FECASIGNACIONVAL                DATE,
    FECAUTORIZACION                 DATE,
    FECSINIESTRO                    DATE,
    FECPROMESA                      DATE,
    FECREFACCIONESENTREGADAS        DATE,
    FECREGISTROLLAVECRM             DATE,
    FECACTUALIZACIONLLAVECRM        DATE,
    FECREGISTROPAGOANTICIPADO       DATE,
    FECENVIOCARRUSELA8              DATE,
    FECENVIOCARRUSELBLINDAJE        DATE,
    FECPRIMERENVIOHERRAMIENTA       DATE,
    FECHAENVIOPT                    DATE,
    FECHAPROGPT                     DATE,
    FECMARCADOUSUARIO               DATE,
    FECADJUDICACCQ                  DATE,
    PROMESA_ENVIO_CRM               DATE,
    FECHAFINIQUITO                  DATE,
    INGRESO_CLIENTE                 DATE,
    FECLIBCHATARRA                  DATE,
    FECHAOCURRIDOSISE               DATE,
    AUT_UNA_PZA_CM                  DATE,
    FECHAESTENT                     DATE,
    SEMANAESTENT                    VARCHAR2(4000),
    ESTIMADAENVIOCRM                DATE
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_GERENTES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE SASPRVFRAP.STG_GERENTES (
  CODIGO_OFICINA VARCHAR2(16),
  CODIGO_GERENTE VARCHAR2(16),
  GERENTE VARCHAR2(256)
);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_HISTORICO_TERMINO_ENTREGA CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_HISTORICO_TERMINO_ENTREGA
(
    IDHISTORICOTERMINOENTREGA   VARCHAR2(4000),
    IDEXPEDIENTE                VARCHAR2(4000),
    TIPOFECHA                   VARCHAR2(4000),
    FECHA                       DATE
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_INCISOS_POLIZAS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE SASPRVFRAP.STG_INCISOS_POLIZAS (
    ID VARCHAR2(4000),
    SECCION VARCHAR2(4000),
    POLIZA VARCHAR2(4000),
    ENDOSO VARCHAR2(4000),
    ANEXO_INCISO VARCHAR2(4000),
    POLIZA_ENDOSO VARCHAR2(4000),
    MARCA_COMP VARCHAR2(4000),
    MARCA_CORTA VARCHAR2(4000),
    AMIS VARCHAR2(4000),
    SUBRAMO VARCHAR2(4000),
    MODELO VARCHAR2(4000),
    ORIGEN VARCHAR2(4000),
    TIPO_VEH VARCHAR2(4000),
    CARROCERIA VARCHAR2(4000),
    USO VARCHAR2(4000),
    SERVICIO VARCHAR2(4000),
    OCUPANTES NUMBER,
    TONELADAS NUMBER,
    CARGA VARCHAR2(4000),
    TRAILES VARCHAR2(4000),
    URBANO VARCHAR2(4000),
    PLACAS VARCHAR2(4000),
    MOTOR VARCHAR2(4000),
    SERIE VARCHAR2(4000),
    COLOR VARCHAR2(4000),
    TRANSMISION VARCHAR2(4000),
    CILINDROS NUMBER,
    PUERTAS NUMBER,
    ANEXOS VARCHAR2(4000),
    ESTATUS VARCHAR2(4000),
    TIPO_COBER VARCHAR2(4000),
    CATEGORIA VARCHAR2(4000),
    TARIF_AUT VARCHAR2(4000),
    VALOR_0KM NUMBER,
    SUMA_ASEGURADA NUMBER,
    SUMA_ASEGURADA_GM NUMBER,
    SUMA_ASEGURADA_RC NUMBER,
    SUMA_ASEGURADA_ADAP NUMBER,
    NUMERO_PASAJEROS NUMBER,
    PRIMA_TOTAL NUMBER,
    PRIMA_DM NUMBER,
    PRIMA_RT NUMBER,
    PRIMA_RC NUMBER,
    PRIMA_GM NUMBER,
    PRIMA_EE NUMBER,
    PRIMA_ADAP NUMBER,
    PRIMA_RT_ADAP NUMBER,
    CALC_PRORRATA VARCHAR2(4000),
    DEDUCIBLE_DM NUMBER,
    DEDUCIBLE_RT NUMBER,
    DEDUCIBLE_RC NUMBER,
    DEDUCIBLE_EE NUMBER,
    DEDUCIBLE_DM_ADAP NUMBER,
    DEDUCIBLE_RT_ADAP NUMBER,
    REC_RC_TRAILER NUMBER,
    REC_RC_X_DANO_CARGA NUMBER,
    DESC_DM_X_USO NUMBER,
    DESC_RT_X_USO NUMBER,
    DESC_RC_X_USO NUMBER,
    DESC_GM_X_USO NUMBER,
    NOMBRE_CONDUCTOR VARCHAR2(4000),
    SUMA_ASEG_ACC_OCUP NUMBER,
    SUMA_ASEG_EXT_RC NUMBER,
    SUMA_ASEG_GL NUMBER,
    PRIMA_RCP NUMBER,
    PRIMA_EXT_RC NUMBER,
    PRIMA_ACC_OCUP NUMBER,
    PRIMA_GT NUMBER,
    PRIMA_GL NUMBER,
    PRIMA_SPT NUMBER,
    PRIMA_EXE_DED NUMBER,
    PAQUETE_GL NUMBER,
    DESC_RP NUMBER,
    SUMA_ASEG_RP NUMBER,
    DED_RP NUMBER,
    PMA_RP NUMBER,
    PMA_AJUSTE_INFL NUMBER,
    SUMA_ASEG_AV NUMBER,
    TASA_AV NUMBER,
    PRIMA_EXT_TERRITORIAL NUMBER,
    PRIMA_RC_ECOLOGICA NUMBER,
    SUMA_ASEG_RC_ECOLOGICA NUMBER,
    DIAS_DED_RC_ECOLOGICA NUMBER,
    DESC_DED_RC_ECOLOGICA NUMBER,
    PRIMA_RC_LEGAL NUMBER,
    SUMA_ASEG_RC_LEGAL NUMBER,
    DIAS_DED_RC_LEGAL NUMBER,
    DESC_DED_RC_LEGAL NUMBER,
    SUMA_ASEG_RCB NUMBER,
    PRIMA_RCB NUMBER,
    DIAS_DED_RCB NUMBER,
    SUMA_ASEG_RCP NUMBER,
    DIAS_DED_RCP NUMBER,
    SUMA_ASEG_RCC NUMBER,
    PRIMA_RCC NUMBER,
    DIAS_DED_RCC NUMBER,
    DESC_DED_RCB NUMBER,
    DESC_DED_RCP NUMBER,
    DESC_DED_RCC NUMBER,
    PAQUETE_AV NUMBER,
    PRIMA_SERV_ASISTENCIA NUMBER,
    DESCRIP_CARGA VARCHAR2(4000),
    REPUVE VARCHAR2(4000),
    DED_RC_PASAJERO NUMBER,
    PRIMA_DANO_X_CARGA NUMBER,
    PRIMA_ASISTENCIA_SATELITAL NUMBER,
    UNIDAD_DE_SALVAMENTO VARCHAR2(4000),
    SERIE_ENCONTRACK VARCHAR2(4000),
    FEC_INST_ENCONTRACK DATE,
    SUMA_ASEG_RC_EXT NUMBER,
    PRIMA_RC_EXT NUMBER,
    DESC_RC_EXT NUMBER,
    SUMA_ASEG_GM_EXT NUMBER,
    PRIMA_GM_EXT NUMBER,
    DESC_GM_EXT NUMBER,
    PRIMA_EXE_DED_X_VEH_IDENT NUMBER,
    PRIMA_AJUSTE_VALOR_COM NUMBER,
    PRIMA_GT_X_PP NUMBER,
    SUMA_ASEG_GT_X_PT NUMBER,
    SUMA_ASEG_GT_X_PP NUMBER,
    DIAS_DED_GT_PT NUMBER,
    DIAS_DED_GT_PP NUMBER,
    SUMA_ASEG_AJ_VAL_COM_X_PT NUMBER,
    PRIMA_EXTENSION_GARANTIA NUMBER,
    PRIMA_EXTENSION_MTTO NUMBER,
    COD_ANIO_EXT_GARANTIA NUMBER,
    PRIMA_ADAPT_SPT NUMBER,
    FECHA_PROCESO DATE,
    PRIMA_EXE_DED_RT NUMBER,
    PROV_ASIST_SAT VARCHAR2(4000),
    SA_GTP_DIARIA NUMBER,
    SA_RC_DANOS_AL_VEH_ARRASTRA NUMBER,
    PMA_RC_DAN_VEH_ARRASTRA NUMBER,
    DIAS_RC_DAN_VEH_ARRASTRA NUMBER,
    DESC_DED_RC_DAN_VEH_ARRASTRA NUMBER,
    AUTORIZA_SOBREPASAR_SA_RC_DVA NUMBER,
    SA_RC_EN_EUA NUMBER,
    PMA_RC_EN_EUA NUMBER,
    DIAS_RC_EUA NUMBER,
    SA_RCP_EUA NUMBER,
    PMA_RCP_EUA NUMBER,
    DIAS_RCP_EUA NUMBER,
    SA_RCB_EUA NUMBER,
    PMA_RCB_EUA NUMBER,
    DIAS_RCB_EUA NUMBER,
    PAQUETE_RCB_EUA NUMBER,
    NUM_ECONOMICO NUMBER,
    SA_AVERIA_MEC_ELEC NUMBER,
    PMA_AVERIA_MEC_ELEC NUMBER,
    SA_AV_AVERIA_MEC_ELEC NUMBER,
    PMA_AV_AVERIA_MEC_ELEC NUMBER,
    SA_AUTO_SUSTITUTO NUMBER,
    PMA_AUTO_SUSTITUTO NUMBER,
    SA_LLANTAS NUMBER,
    PMA_LLANTAS NUMBER,
    SA_RINES NUMBER,
    DED_LLANTAS_Y_RINES NUMBER,
    PMA_RINES NUMBER,
    GAP1 NUMBER,
    SA_CB_FLEX NUMBER,
    DSCTO_COB VARCHAR2(4000),
    AMPARA_P2MIL_PREMIUM VARCHAR2(4000),
    MARCA_VEH_ALTO_RGO VARCHAR2(4000),
    INSP_VEH VARCHAR2(4000),
    DANIOS_PREEXISTENTES VARCHAR2(4000),
    DESC_DANOS_PREEXISTENTES VARCHAR2(4000),
    FEC_INSP_VEH DATE,
    COND_VIG_A_NIVEL_DI VARCHAR2(4000),
    AMPARA_AV_REM_ENGAN VARCHAR2(4000),
    REGISTRO_CNSF VARCHAR2(4000),
    PMA_AV_REMOLQUE_ENGANC VARCHAR2(4000),
    QUIEN_HIZO_INSP_VEH VARCHAR2(4000),
    INSP_VEH_X_OFIC VARCHAR2(4000),
    VEH_BLINDADO VARCHAR2(4000),
    FACTOR_BLINDAJE VARCHAR2(4000),
    GAP2 VARCHAR2(4000),
    SA_RCP_OBLIGATORIA NUMBER,
    PMA_RCP_OBLIG NUMBER,
    DIAS_DED_RCP_OBLIG NUMBER,
    SA_RCB_OBLIG NUMBER,
    PMA_RCB_OBLIG NUMBER,
    DIAS_DED_RCB_OBLIG NUMBER,
    DESC_DED_RC_OBLIG NUMBER,
    DESC_DED_RCP_OBLIG NUMBER,
    PAQUETE_RC_OBLIG VARCHAR2(4000),
    ADICIONALES_AV VARCHAR2(4000),
    AV_MANIOBRAS VARCHAR2(4000),
    RECARGO_AV_MANIOBRAS NUMBER,
    PMA_ANUAL_RC NUMBER,
    PMA_ANUAL_RC_OBLIG NUMBER,
    PMA_TOT_RC_OBLIG NUMBER,
    SA_TOT_ANUAL_RC_OBLIG NUMBER,
    BENEF_PREF_INCISO VARCHAR2(4000),
    SA_SINIESTRALIDAD_CADE NUMBER,
    TIPO_OFIC_INSP_VEH VARCHAR2(4000),
    CUOTA_AUT_SUST_PT NUMBER,
    SUMA_ASEG_AS_PT NUMBER,
    PRIMA_AS_PT NUMBER,
    AUTORIZO_CAMBIO_USO VARCHAR2(4000),
    AUTORIZO_CVES_DIREC_SERIE VARCHAR2(4000),
    MARCA_UBER_CABIFY VARCHAR2(4000),
    SA_VEH_AUTOS_INC_X_PT VARCHAR2(4000),
    CAUSA_INSP_VEH VARCHAR2(4000),
    RGO_DESC_X_USO_SPT NUMBER,
    SUMA_ASEG_AJINFL NUMBER,
    PRIMA_AV NUMBER,
    DESC_DED_RCB_OBLIG NUMBER,
    PMA_RCP NUMBER,
    PORC_DED_RP NUMBER,
    ULTIMO_ENDOSO NUMBER(1),
    FECHA_CARGA DATE
);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_MARCA CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_MARCA
(
    IDMARCA                     VARCHAR2(4000) NOT NULL,
    DESCRIPCION                 VARCHAR2(4000),
    ALTA                        DATE,
    ACTUALIZACION               DATE,
    USUARIOACTUALIZA            VARCHAR2(4000),
    RESCATEPT                   NUMBER,
    APLICACONVENIO              NUMBER,
    TIEMPOMARCA                 NUMBER,
    AUTOS                       NUMBER NOT NULL,
    EP                          NUMBER NOT NULL,
    CHECKCALFECHAEE             VARCHAR2(4000),
    V0                          NUMBER,
    V1                          NUMBER,
    V2                          NUMBER,
    V3                          NUMBER,
    V4                          NUMBER,
    PORCENTAJE_V0               NUMBER,
    PORCENTAJE_V1               NUMBER,
    PORCENTAJE_V2               NUMBER,
    PORCENTAJE_V3               NUMBER,
    PORCENTAJE_V4               NUMBER,
    ACTIVAMARCAPT               VARCHAR2(4000),
    VESPECIALIZADO              VARCHAR2(4000),
    ALTAESPECIALIZADOMM         DATE,
    ALTAESPECIALIZADO           DATE
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_OFICINAS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Tabla STG_OFICINAS
CREATE TABLE SASPRVFRAP.STG_OFICINAS (
    ID VARCHAR2(50),
    OFICINA VARCHAR2(100),
    DIRECCION VARCHAR2(255),
    COLONIA VARCHAR2(100),
    POBLACION VARCHAR2(100),
    CODIGO_POBLACION VARCHAR2(50),
    CODIGO_POSTAL VARCHAR2(20),
    ZONA VARCHAR2(100)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_PAGOS_POLIZAS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_PAGOS_POLIZAS (
    ID VARCHAR2(50),
    FECHA_VENCIMIENTO DATE,
    POLIZA VARCHAR2(50),
    ENDOSO VARCHAR2(50),
    POLIZA_ENDOSO VARCHAR2(100),
    IMPORTE NUMBER,
    REMESA VARCHAR2(50),
    MARCA_IMP DATE,
    MARCA_ANUL DATE,
    PRIMA_NETA NUMBER,
    DERECHO_POLIZA NUMBER,
    RECIBO_FIN NUMBER,
    IVA NUMBER,
    BONIFICACION NUMBER,
    BONIFICACION_RF NUMBER,
    BONIFICACION_TEC NUMBER,
    PRIMA_TOTAL NUMBER,
    USUARIO_APLICA VARCHAR2(256),
    FECHA_APLICACION DATE,
    IMPRESION VARCHAR2(4000), 
    RFC_FACTURACION VARCHAR2(256),
    USUARIO_EMITE VARCHAR2(256),
    STATUS VARCHAR2(256),
    FECHA_PROCESO DATE,
    FECHA_CARGA DATE
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_PAGOS_PROVEEDORES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_PAGOS_PROVEEDORES (
    ID VARCHAR2(4000),
    ID_TRAMITE VARCHAR2(4000),
    IMPORTE_MANO_OBRA NUMBER,
    IMPORTE_REFACCIONES NUMBER,
    ID_PROVEEDOR VARCHAR2(4000),
    PROVEEDOR VARCHAR2(4000),
    CLAVE_DOCUMENTO VARCHAR2(4000),
    DOCUMENTO VARCHAR2(4000),
    IMPORTE NUMBER,
    ORDEN_PAGO VARCHAR2(4000),
    CODIGO_PAGO VARCHAR2(4000),
    CODIGO_GASTO VARCHAR2(4000),
    TIPO_GASTO VARCHAR2(4000),
    FECHA_PAGO DATE,
    ID_MONEDA VARCHAR2(4000),
    COBERTURA VARCHAR2(4000),
    POLIZA VARCHAR2(4000),
    ENDOSO VARCHAR2(4000),
    ID_POLIZA_ENDOSO VARCHAR2(4000),
    ID_POLIZA_ENDOSO_INCISO VARCHAR2(4000),
    INCISO VARCHAR2(4000),
    CLAVE_SUBRAMO VARCHAR2(4000),
    TIPO_VEHICULO VARCHAR2(4000),
    USO_VEHICULO VARCHAR2(4000),
    SERVICIO_VEHICULO VARCHAR2(4000),
    AMIS VARCHAR2(4000),
    UNIDAD_VEHICULO VARCHAR2(4000),
    MODELO_VEHICULO VARCHAR2(4000),
    PRIMA_POLIZA NUMBER,
    ASEGURADO VARCHAR2(4000),
    ID_AGENTE VARCHAR2(4000),
    ID_OFICINA_EMISION VARCHAR2(4000),
    ID_OFICINA_ATENCION VARCHAR2(4000),
    ID_SINIESTRO VARCHAR2(4000),
    FECHA_OCURRIDO DATE,
    DIAS NUMBER,
    ID_AJUSTADOR VARCHAR2(4000),
    ID_CAUSA VARCHAR2(4000),
    FECHA_REGISTRO DATE,
    CODIGO_TEXTO VARCHAR2(4000),
    MARCA_VEHICULO VARCHAR2(4000),
    IMPORTE_DEDUCIBLE NUMBER,
    IMPORTE_TOTAL NUMBER,
    ORIGEN VARCHAR2(4000),
    BANCO VARCHAR2(4000),
    CHEQUE VARCHAR2(4000),
    CARATULA VARCHAR2(4000),
    ENTIDAD VARCHAR2(4000),
    NUMERO_NAGS NUMBER,
    FACTURA VARCHAR2(4000),
    ID_USUARIO_FILTRO VARCHAR2(4000),
    ID_USUARIO_TECNICO VARCHAR2(4000),
    ID_USUARIO_PAGO VARCHAR2(4000),
    ID_USUARIO_RESERVA VARCHAR2(4000),
    ID_VALUACION VARCHAR2(4000),
    TIEMPO_PAGO NUMBER
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_POLIZAS_VIGENTES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_POLIZAS_VIGENTES (
    ID VARCHAR2(4000),
    RAMO VARCHAR2(4000),
    POLIZA VARCHAR2(4000),
    ENDOSO VARCHAR2(4000),
    POLIZA_ENDOSO VARCHAR2(4000),
    ID_ASEGURADO VARCHAR2(4000),
    FECHA_EMISION DATE,
    VIGENCIA_DESDE DATE,
    VIGENCIA_HASTA DATE,
    RENOVADA_POR VARCHAR2(4000),
    RENUEVA_A VARCHAR2(4000),
    CODIGO_MONEDA VARCHAR2(4000),
    CODIGO_FACTURACION VARCHAR2(4000),
    CODIGO_EMISION VARCHAR2(4000),
    PORC_RF NUMBER,
    PORC_IVA NUMBER,
    PORC_BONIF NUMBER,
    COD_CAMBIO_DP VARCHAR2(4000),
    RSR VARCHAR2(4000),
    AAMM_TARIFA NUMBER,
    AAMM_VALORES NUMBER,
    AAMM_DERPOL NUMBER,
    SUMA_ASEGURADA NUMBER,
    PRIMA_NETA NUMBER,
    DER_POL NUMBER,
    REC_FIN NUMBER,
    IVA NUMBER,
    BONIFICACION NUMBER,
    BONIF_RF NUMBER,
    BONIF_TEC NUMBER,
    PMA_ENDO_RF NUMBER,
    PRIMA_TOTAL NUMBER,
    CODIGO_PLAN_PAGO VARCHAR2(4000),
    CODIGO_PRODUCTO VARCHAR2(4000),
    AGENTE VARCHAR2(4000),
    PROMOTOR VARCHAR2(4000),
    COMIS_NORMAL NUMBER,
    COMIS_RF NUMBER,
    COMIS_TEC NUMBER,
    COTIZACION NUMBER,
    ENDOSO_QUE_MODIFICA VARCHAR2(4000),
    CODIGO_CONDUCTO_PAGO VARCHAR2(4000),
    ACREEDOR_PREND VARCHAR2(4000),
    MARCA_CANC_AUT VARCHAR2(4000),
    COD_COBZA_COAS VARCHAR2(4000),
    FECHA_AMORTIZACION DATE,
    FECHA_REHABILITACION DATE,
    ID_OFICINA VARCHAR2(4000),
    FECHA_PROCESO_SISE DATE,
    HORA_INICIO_CARGA VARCHAR2(4000),
    HORA_FIN_CARGA VARCHAR2(4000),
    CODIGO_OPERACION VARCHAR2(4000),
    POL_END_COAS VARCHAR2(4000),
    COMPANIA_PILOTO VARCHAR2(4000),
    CIAS_PARTICIPANTES VARCHAR2(4000),
    PART_CIAS VARCHAR2(4000),
    PART_CIAS_PN VARCHAR2(4000),
    CODIGO_CANCELACION VARCHAR2(4000),
    REASEGURO_AUT VARCHAR2(4000),
    TURISTA VARCHAR2(4000),
    CAMBIO_MONEDA NUMBER,
    USUARIO_EMITE VARCHAR2(4000),
    IVA_RCP NUMBER,
    BON_NORM_RCP NUMBER,
    REMESA_DERECHO VARCHAR2(4000),
    AUT_BONIF VARCHAR2(4000),
    AUT_TARIFA_MANUAL VARCHAR2(4000),
    DESCTO_X_ZONA_AUTOS VARCHAR2(4000),
    DESCTO_X_ZONA_CAMIONES VARCHAR2(4000),
    PRORRATEO_DERECHOS VARCHAR2(4000),
    AUT_PRORR_DERECHO VARCHAR2(4000),
    AUT_EE_Y_ADAP VARCHAR2(4000),
    AUT_TAR_EE VARCHAR2(4000),
    RENOVACION_AUTOMATICA VARCHAR2(4000),
    FLOT_POL_IND VARCHAR2(4000),
    AUT_BONIF_RENT_AUT VARCHAR2(4000),
    CONDICIONES_VIGENTES VARCHAR2(4000),
    AUT_RECARGO VARCHAR2(4000),
    AUT_REHAB_MAS60 VARCHAR2(4000),
    AUT_ENDO_POL_VENC VARCHAR2(4000),
    FORMATO_RECIBO VARCHAR2(4000),
    AUT_TARIFA_ESP VARCHAR2(4000),
    DIAS_PER_GRACIA_AGTE NUMBER,
    PORC_DESC_PER_GRACIA NUMBER,
    AUT_POL_TURISTA VARCHAR2(4000),
    NUM_VEH_TUR VARCHAR2(4000),
    PMA_ASIST_TURISTA NUMBER,
    POLITICA_BONO_AGENTE VARCHAR2(4000),
    POLITICA_BONO_PROM VARCHAR2(4000),
    AUT_MODIF_BONO VARCHAR2(4000),
    AUT_REUTILIZAR_COTIZACION VARCHAR2(4000),
    AUT_CAMBIAR_ASEG_ENDO VARCHAR2(4000),
    MARCA_RC_EXTRANJERO VARCHAR2(4000),
    COD_AGENCIA1 VARCHAR2(4000),
    DED_ADMV VARCHAR2(4000),
    AUT_PT_RCBOS VARCHAR2(4000),
    AUT_POL_CON_DED_ADMVO VARCHAR2(4000),
    AUT_PAGO_MENS_TRIM_BUSES VARCHAR2(4000),
    AUT_ELIM_ASISTSAT VARCHAR2(4000),
    PLAN_PISO VARCHAR2(4000),
    AUT_TAR_MANUAL VARCHAR2(4000),
    COD_AGENCIA2 VARCHAR2(4000),
    UDI_AGENCIA2 VARCHAR2(4000),
    AUT_TARIF_DIF_COTIZACION VARCHAR2(4000),
    DER_POL_1ER_RCBO NUMBER,
    USUARIO_MARCA_REC_CANC VARCHAR2(4000),
    AUT_MOD_COBER_EE VARCHAR2(4000),
    AUT_CAMBIO_DP VARCHAR2(4000),
    AUT_RENOVACION VARCHAR2(4000),
    AUT_AJUSTE_AUTOM VARCHAR2(4000),
    POL_COMP_AGENCIAS NUMBER,
    AUT_MOD_COM_NORM VARCHAR2(4000),
    AUT_MOD_COM_X_RECARGO VARCHAR2(4000),
    AUT_CAMBIO_COD_ASEGURADO VARCHAR2(4000),
    AUT_EMITIR_PAQ_FAM VARCHAR2(4000),
    AUT_AMPARAR_SERIES_DUP_C_AGTES VARCHAR2(4000),
    AUT_EMITIR_VEH_FRONT VARCHAR2(4000),
    NUM_ECOLOGICO_OPL VARCHAR2(4000),
    LEYENDA_DED_ADMVO VARCHAR2(4000),
    AUT_EMITIR_MOD_ANT_CON_TAR_NO_PERM VARCHAR2(4000),
    FECHA_CANCELACION_AUT DATE,
    AUT_EMITIR_TAR_NO_VIG VARCHAR2(4000),
    EXCLUSION_DIA_BISIESTO VARCHAR2(4000),
    VALIDACION_VEH_NO_ROBADO VARCHAR2(4000),
    AUT_EMITIR_SERVPUB_VIG_183DIA VARCHAR2(4000),
    AUT_AMP_VEH_MENOR25_ANIOS_RCPAS VARCHAR2(4000),
    VIG_GARANTIA_FABRICANTE VARCHAR2(4000),
    AUT_EMITIR_ASEG_MARCADO_ART140 VARCHAR2(4000),
    COD_AGENCIA3 VARCHAR2(4000),
    UDI_AGENCIA3 VARCHAR2(4000),
    SUBRAMO_DESCUENTO VARCHAR2(4000),
    POLIZA_A_MSI VARCHAR2(4000),
    FEC_CREACION_ENDO_X_CFP DATE,
    AUT_EMITIR_SERIES_CON_PT VARCHAR2(4000),
    NUMERO_INCISOS_POLIZA NUMBER,
    SA_VEH_NO_INCL_BONIF NUMBER,
    AUT_DED_ENCONTRACK VARCHAR2(4000),
    CP_ASEGURADO VARCHAR2(4000),
    CP_ALTERNO VARCHAR2(4000),
    USUARIO_MODIFICA_CP VARCHAR2(4000),
    COD_EDO_Y_GPO_CP VARCHAR2(4000),
    TIPO_POLIZA VARCHAR2(4000),
    CTRL_DIAS_PER_GRACIA VARCHAR2(4000),
    AUT_DIAS_PER_GRACIA VARCHAR2(4000),
    AUT_MODIF_CP VARCHAR2(4000),
    INCLUYE_ROBO_VALOR_TOTAL VARCHAR2(4000),
    MARCA_EMISION_EN_SISE VARCHAR2(4000),
    AUT_EMITIR_CON_PEPS VARCHAR2(4000),
    IMPRESION_CERT_RC_OBL VARCHAR2(4000),
    COBR_EMITIDAS_EN_INCISOS VARCHAR2(4000),
    AUT_CANCELAR_POL_RC_OBL VARCHAR2(4000),
    COB_AFECTADAS_POR_DED_ADMVO VARCHAR2(4000),
    MARCA_POL_CARGA_OPL VARCHAR2(4000),
    FEC_CARGA_POL_OPL VARCHAR2(4000),
    PMA_NETA_X_INCISO NUMBER,
    PMA_SIN_BT_X_INCISO NUMBER,
    PMA_SIN_ACUMULADO_X_INCISO NUMBER,
    PMA_NETA_BT_X_INCI NUMBER,
    SUBRAMO_X_INCI VARCHAR2(4000),
    DERPOL_X_INCI NUMBER,
    REC_FIN_X_INCISO NUMBER,
    IVA_X_INCI NUMBER,
    TOTAL_X_INCI NUMBER,
    BT_X_INCI NUMBER,
    BN_X_INCI NUMBER,
    BR_X_INCI NUMBER,
    METODO_PAGO_OPL VARCHAR2(4000),
    SW_VERIFICA_AGT VARCHAR2(4000),
    MARCA_AGTE_CUES_DIRECTA VARCHAR2(4000),
    AUT_SERIE_APP VARCHAR2(4000),
    MARCA_POL_DEPURADA_HIST VARCHAR2(4000),
    TIPO_NEGOCIO VARCHAR2(4000),
    HISTORIAL_ADEG_EN_PLIZA VARCHAR2(4000),
    AUT_EMITIR_PERSONA_SUJETA_A_REVISION VARCHAR2(4000),
    AUT_EMITIR_PERSONA_NO_ASEG VARCHAR2(4000),
    BLOQUEO_POLIZAS VARCHAR2(4000),
    POL_EMITIDA_VIA_COBZA_DELEGADA VARCHAR2(4000),
    POLIZA_A_REEXPEDIR VARCHAR2(4000),
    RFC_NORM_ASEG_UNICO VARCHAR2(4000),
    MARCA_PMA_INSUFICIENTE VARCHAR2(4000),
    ENDOSO_CFP VARCHAR2(4000),
    MARCA_CAMBIO_FP_SIN_RF VARCHAR2(4000),
    MARCA_POL_RC_CONTRACTUAL VARCHAR2(4000),
    POL_REFER_RC_CONTRAT VARCHAR2(4000),
    ENDO_REFER_RC_CONTRACT VARCHAR2(4000),
    INCI_REFER_RC_CONTRACT VARCHAR2(4000),
    FEC_EMI_REFER_RC_CONTRACT VARCHAR2(4000),
    DESDE_REFER_RC_CONTRACT VARCHAR2(4000),
    HASTA_REFER_RC_CONTRACT VARCHAR2(4000),
    TIPO_POL_RC_CONTRACT VARCHAR2(4000),
    TIPO_DOC_RC_CONTRACT VARCHAR2(4000),
    RCBOS_SUBSEC_BON_TEC_X_INCI VARCHAR2(4000),
    RCBOS_SUBSEC_BON_TEC_X_INCI_2 VARCHAR2(4000),
    SUBTOTAL NUMBER,
    ASEG_UNICO VARCHAR2(4000),
    AUT_EMITIR_ASEG_ALTO_RIESGO VARCHAR2(4000),
    AUT_SERIES_CANCELADAS VARCHAR2(4000),
    FECHA_PROCESO DATE,
    MARCA_POL_AUTOEXPEDIBLE VARCHAR2(4000),
    PORC_BONRF VARCHAR2(4000),
    BM VARCHAR2(4000),
    DESC_PER_GRACIA VARCHAR2(4000),
    TIPO_ENDOSO VARCHAR2(4000),
    CONSECUTIVO NUMBER,
    ULTIMO_ENDOSO NUMBER(1),
    FECHA_CARGA DATE
);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_PROVEEDOR CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_PROVEEDOR
(
    CODPROVEEDOR                        VARCHAR2(4000) NOT NULL,
    NOMBRE                              VARCHAR2(4000) NOT NULL,
    ALTA                                DATE NOT NULL,
    ACTUALIZACION                       DATE,
    USUARIOACTUALIZA                    VARCHAR2(4000),
    IDREGION                            VARCHAR2(4000),
    MAIL                                VARCHAR2(4000),
    DATO                                VARCHAR2(4000),
    TIPO                                VARCHAR2(4000),
    MULTIMARCA                          NUMBER,
    IDTIPOTOT                           VARCHAR2(4000),
    IDIVA                               VARCHAR2(4000),
    CELULARNEXTEL                       VARCHAR2(4000),
    NUMTELEFONICO                       VARCHAR2(4000),
    ASIGNACIONVALUADOR                  NUMBER,
    PORCENTAJEDESCUENTOADICIONAL        NUMBER,
    COSTOFIJO                           NUMBER,
    FECHAACEPTACIONPOLITICA             DATE,
    FIRMA                               NUMBER,
    ESTATUSPROVEEDOR                    NUMBER,
    RFC                                 VARCHAR2(4000),
    USUARIOALTA                         VARCHAR2(4000),
    RECCHATARRA                         VARCHAR2(4000),
    FECACEPTAETICACONDUCTAPROV          DATE,
    FECACEPTACONFLICTOPROV              DATE,
    VIP                                 NUMBER,
    VERINDICADORES                      VARCHAR2(4000),
    SUSPAUTO                            VARCHAR2(4000),
    NOMOSTRARMONTOENVALES               NUMBER NOT NULL,
    LIBERADO                            VARCHAR2(4000),
    MAIL2                               VARCHAR2(4000),
    FECACEPTAAVISOPRIV                  DATE,
    CONFIANZA                           VARCHAR2(4000),
    ACTUALIZACIONCONFIANZA              DATE,
    ASIGNACIONINACTIVA                  VARCHAR2(4000)
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_PROVEEDORES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Tabla STG_PROVEEDORES
CREATE TABLE SASPRVFRAP.STG_PROVEEDORES (
    ID VARCHAR2(50),
    NOMBRE VARCHAR2(255),
    MARCA VARCHAR2(100),
    TIPO VARCHAR2(100),
    OFICINA VARCHAR2(100),
    SUSPENCION VARCHAR2(100),
    STATUS VARCHAR2(50),
    FECHA_BAJA DATE,
    CODIGO_ESTADO VARCHAR2(50),
    POBLACION VARCHAR2(100),
    DIRECCION VARCHAR2(255),
    DIRECCION_COMER VARCHAR2(255),
    COLONIA_COMER VARCHAR2(100),
    POBLACION_COMER VARCHAR2(100),
    ESTADO_COMER VARCHAR2(100),
    NUMERO_DOCTO VARCHAR2(100),
    NOMBRE_COMER VARCHAR2(255),
    GRUPO VARCHAR2(100),
    FECHA_ALTA DATE,
    CTA_ESP VARCHAR2(100),
    TIPO_AJUSTE VARCHAR2(100),
    TIPO_MARCA VARCHAR2(100),
    RFC VARCHAR2(50),
    CORREO_COMERCIAL VARCHAR2(255),
    CORREO_CONTACTO VARCHAR2(255),
    CORREO_COMERCIAL_2 VARCHAR2(255),
    MARCA_MOTOS VARCHAR2(100),
    TELEFONO_SIICA VARCHAR2(50),
    AE NUMBER(19),
    LATITUD VARCHAR2(50),
    LONGITUD VARCHAR2(50),
    RECIBE_24 VARCHAR2(10),
    ZONA_PROVEEDOR VARCHAR2(100),
    VED VARCHAR2(50),
    TIPO_PERSONA VARCHAR2(50),
    CEXP NUMBER(19),
    TBODY VARCHAR2(255),
    NUMERO_EMPLEADO VARCHAR2(50)
);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_REFACCION CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE SASPRVFRAP.STG_REFACCION
(
    IDREFACCION             VARCHAR2(4000) NOT NULL,
    DESCRIPCION             VARCHAR2(4000),
    ALTA                    DATE,
    ACTUALIZACION           DATE,
    USUARIOACTUALIZA        VARCHAR2(4000),
    AUTOS                   VARCHAR2(4000),
    EP                      VARCHAR2(4000)
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_REGISTRO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE SASPRVFRAP.STG_REGISTRO (
    ID_SINIESTRO VARCHAR2(4000),
    ID_OFICINA VARCHAR2(4000),
    DESCRIPCION_OFICINA VARCHAR2(4000),
    USUARIO VARCHAR2(4000),
    NOMBRE VARCHAR2(4000),
    CORREO VARCHAR2(4000),
    MOTIVO VARCHAR2(4000),
    OBSERVACIONES VARCHAR2(4000),
    DOCUMENTO_ADICIONAL VARCHAR2(4000),
    SINIESTRO_ALERTADO VARCHAR2(4000),
    ID_ANALISTA VARCHAR2(4000),
    FECHA_ASIGNACION DATE,
    AREA VARCHAR2(4000),
    PUESTO VARCHAR2(4000),
    ID_MOTIVO VARCHAR2(4000),
    MARCA VARCHAR2(4000),
    MONTO_ESTIMADO NUMBER,
    FECHA_LOTE DATE,
    ID_USUARIO_SISTEMA VARCHAR2(4000)
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_SINIESTROS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Tabla DM_SINIESTROS (con referencias a tablas ya definidas)
CREATE TABLE SASPRVFRAP.STG_SINIESTROS (
    ID VARCHAR2(100),
    REPORTE VARCHAR2(100),
    POLIZA VARCHAR2(50),
    ENDOSO VARCHAR2(50),
    INCISO VARCHAR2(20),
    ID_POLIZA_ENDOSO VARCHAR2(100),
    ID_POLIZA_ENDOSO_INCISO VARCHAR2(150),
    ASEGURADO VARCHAR2(200),
    ID_ASEGURADO VARCHAR2(50),
    ID_CAUSA VARCHAR2(50),
    FECHA_OCURRIDO DATE,
    FECHA_REPORTE DATE,
    FECHA_REGISTRO DATE,
    FECHA_INICIO_VIGENCIA DATE,
    MARCA VARCHAR2(100),
    MODELO VARCHAR2(100),
    SERIE VARCHAR2(50),
    SEVERIDAD NUMBER,
    STATUS VARCHAR2(20),
    RESERVA NUMBER(15,2),
    UBICACION VARCHAR2(200),
    ENTIDAD VARCHAR2(100),
    ID_OFICINA VARCHAR2(50),
    LEIDO_SAS VARCHAR2(1),
    ID_OFICINA_DE_ATENCION VARCHAR2(50),
    ID_AJUSTADOR VARCHAR2(50),
    LATITUD VARCHAR2(30),
    LONGITUD VARCHAR2(30),
    CONDUCTOR VARCHAR2(200),
    CODIGO_USO VARCHAR2(20),
    USO VARCHAR2(100),
    SUMA_ASEGURADA NUMBER(15,2),
    PLACA VARCHAR2(20),
    FECHA_EMISION DATE,
    POLIZA_REHABILITADA NUMBER(1),
    FECHA_FIN_VIGENCIA DATE,
    OBSERVACIONES VARCHAR2(4000),
    FECHA_LOTE DATE,
    ID_USUARIO_SISTEMA VARCHAR2(50)
);




BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_SUPERVISOR_INTEGRAL  CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_SUPERVISOR_INTEGRAL
(
    IDSUPERVISORINTEGRAL    VARCHAR2(4000) NOT NULL,
    CLAVESUPERVISOR         VARCHAR2(4000) NOT NULL,
    NOMBRESUPERVISOR        VARCHAR2(4000) NOT NULL,
    CORREO                  VARCHAR2(4000) NOT NULL,
    TELEFONO                VARCHAR2(4000) NOT NULL,
    IDREGIONGEOGRAFICA      VARCHAR2(4000) NOT NULL,
    ESTATUS                 NUMBER NOT NULL,
    FECHAREGISTRO           DATE NOT NULL,
    FECHAACTUALIZACION      DATE NOT NULL,
    USUARIOREGISTRO         VARCHAR2(4000) NOT NULL
);




BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_TALLERES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_TALLERES
(
    IDTALLER                            NUMBER NOT NULL,
    IDOFICINA                           VARCHAR2(4000),
    CLAVETALLER                         VARCHAR2(4000),
    RAZONSOCIAL                         VARCHAR2(4000),
    NOMBRECOMERCIAL                     VARCHAR2(4000),
    CONTRIBUYENTE                       VARCHAR2(4000),
    REPRESENTANTELEGAL                  VARCHAR2(4000),
    CORREO                              VARCHAR2(4000),
    RFC                                 VARCHAR2(4000),
    DOMICILIOFISCAL                     VARCHAR2(4000),
    DIRECCIONCOMERCIAL                  VARCHAR2(4000),
    CELULARNEXTEL                       VARCHAR2(4000),
    TARIFAMOB                           NUMBER,
    ENTIDAD                             VARCHAR2(4000),
    PERFIL                              VARCHAR2(4000),
    COTIZADOR                           NUMBER,
    MITCHELL                            NUMBER,
    TIPO                                VARCHAR2(4000),
    MULTIMARCA                          NUMBER,
    IDMARCA                             VARCHAR2(4000),
    IDENTIDAD                           VARCHAR2(4000),
    ENVIOPRESUPUESTO                    NUMBER,
    NUMTELEFONICO                       VARCHAR2(4000),
    MENSAJE                             NUMBER,
    FRONTERIZO                          NUMBER,
    FECHAACEPTACIONPOLITICA             DATE,
    ESTATUSTALLER                       NUMBER,
    FECACEPTACIONPOLITICAEQPESADO       DATE,
    PAGOANTICIPADO                      NUMBER,
    USUARIOHERRAMIENTA                  VARCHAR2(4000),
    ACTIVARAUDACLAIMS                   NUMBER NOT NULL,
    COMPANIAASIGNADAACG                 VARCHAR2(4000),
    POOLASIGNADOACG                     VARCHAR2(4000),
    USUARIOALTA                         VARCHAR2(4000),
    USUARIOACTUALIZACION                VARCHAR2(4000),
    ALTA                                DATE,
    ACTUALIZACION                       DATE,
    IDESTADO                            VARCHAR2(4000),
    IMAGENQCONTENT                      VARCHAR2(4000),
    ANUNCIOS_PORTAL                     NUMBER,
    FECCAMPANIALIM                      DATE,
    RECCHATARRA                         VARCHAR2(4000),
    FECACEPTAETICACONDUCTATALLER        DATE,
    FECACEPTACONFLICTOTALLER            DATE,
    ACTIVO                              NUMBER,
    MAXIMO                              NUMBER,
    MINIMO                              NUMBER,
    RPM                                 NUMBER,
    LIBERADO                            VARCHAR2(4000),
    FECACEPTAAPPMOVIL                   DATE,
    ACTIVAPROORDER                      VARCHAR2(4000),
    FECACEPTAAVISOPRIV                  DATE,
    FECACEPTAAVISOPO                    DATE,
    IDTIPOTALLER                        VARCHAR2(4000),
    ACTIVAXNUUP                         NUMBER
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_TIPOS_PROVEEDORES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_TIPOS_PROVEEDORES (
    ID VARCHAR2(4000),
    TIPO_PROVEEDOR VARCHAR2(4000),
    GRUPO VARCHAR2(4000),
    NOMBRE_GRUPO VARCHAR2(4000)
);




BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_VALE_HISTORICO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_VALE_HISTORICO
(
    IDVALEHISTORICO             VARCHAR2(4000),
    CONCEPTO                    VARCHAR2(4000),
    NUMPARTE                    VARCHAR2(4000),
    REFERENCIA                  VARCHAR2(4000),
    DESCRIPCION                 VARCHAR2(4000),
    MONTO                       NUMBER,
    LISTA                       VARCHAR2(4000),
    TIPO                        VARCHAR2(4000),
    IDCOSTO                     VARCHAR2(4000),
    IDVALE                      VARCHAR2(4000),
    FECSURTIDO                  DATE,
    IDREFACCION                 VARCHAR2(4000),
    IDCAUSACAMBIOVALE           VARCHAR2(4000),
    USUARIO                     VARCHAR2(4000),
    FECENVIO                    DATE,
    FECENTREGAREFACCIONARIA     DATE,
    FECRECEPCION                DATE,
    NUMEROGUIA                  VARCHAR2(4000),
    MENSAJERIA                  VARCHAR2(4000),
    FECHARECOLECCION            DATE,
    GUIARECOLECCION             VARCHAR2(4000),
    MENSAJERIARECOLECCION       VARCHAR2(4000),
    CANTIDADREFACCIONES         NUMBER,
    NUMPARTEVALUADOR            VARCHAR2(4000),
    IDCAUSACANCELARPIEZA        VARCHAR2(4000)
);




BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_VALE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_VALE
(
    IDVALE                  VARCHAR2(4000),
    IDEXPEDIENTE            VARCHAR2(4000),
    CODPROVEEDOR            VARCHAR2(4000),
    MONTO                   NUMBER,
    FOLIO                   VARCHAR2(4000),
    FECHAEXPEDICION         DATE,
    FECHAACTUALIZACION      DATE,
    IDVALEESTATUS           VARCHAR2(4000),
    VALE                    BLOB,
    LEIDOORDEN              NUMBER,
    LEIDOVALE               NUMBER,
    PIEZASRECIBIDAS         NUMBER,
    AUTORIZADOR             VARCHAR2(4000),
    COTIZADOR               NUMBER,
    TOTALDESRESCATEPT       NUMBER,
    ESTATUSVALESISE         VARCHAR2(4000),
    MONTOPAGADOSISE         VARCHAR2(4000),
    FECHAPAGOSISE           DATE,
    PENDIENTELIBERAR        NUMBER NOT NULL,
    DEVUELTO                VARCHAR2(4000) NOT NULL,
    ESTATUSACTUALSISE       VARCHAR2(4000)
);




BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_VALUACION CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE SASPRVFRAP.STG_VALUACION
(
    IDVALUACION             VARCHAR2(4000) NOT NULL,
    DESCRIPCION             VARCHAR2(4000),
    ALTA                    DATE,
    ACTUALIZACION           DATE,
    USUARIOACTUALIZA        VARCHAR2(4000)
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SASPRVFRAP.STG_VALUACIONES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE SASPRVFRAP.STG_VALUACIONES (
 VALUACION VARCHAR2(4000),
    VALUADORES VARCHAR2(4000),
    TIPO_VALUADOR VARCHAR2(4000),
    TIPO_DE_VALUACION VARCHAR2(4000),
    OFICINA_VALUADOR VARCHAR2(4000),
    REGIONAL_VALUACION VARCHAR2(4000),
    PROVEEDORES VARCHAR2(4000),
    ASEG_TERCERO VARCHAR2(4000),
    TIPO_PROVEEDOR VARCHAR2(4000),
    OFICINA_PROVEEDOR VARCHAR2(4000),
    REGION_PROVEEDOR VARCHAR2(4000),
    TIPO_NEGOCIO VARCHAR2(4000),
    DIRECTOR_GERENTE VARCHAR2(4000),
    CLAVE_GERENTE VARCHAR2(4000),
    GERENTE VARCHAR2(4000),
    CLAVE_AGENTE VARCHAR2(4000),
    AGENTE VARCHAR2(4000),
    OFICINA_VENTAS VARCHAR2(4000),
    MODELO_VEHICULO NUMBER,
    MARCAS VARCHAR2(4000),
    TIPO_VEHICULO VARCHAR2(4000),
    FECHA_ASIGNACION DATE,
    FECHA_OCURRIDO DATE,
    FECHA_INGRESO DATE,
    FECHA_VALUACION DATE,
    FECHA_PROMESA DATE,
    FECHA_TERMINADO DATE,
    FECHA_ENTREGA DATE,
    FECHA_CAPTURA DATE,
    FECHA_MODIFICACION DATE,
    MONEDA VARCHAR2(4000),
    ESTATUS_PROCESO VARCHAR2(4000),
    SISTEMA_VALUACION VARCHAR2(4000),
    VALUACIONES NUMBER,
    NUMERO_PT NUMBER,
    IMPORTE_PT NUMBER,
    NUMERO_PD NUMBER,
    IMPORTE_PD NUMBER,
    NUMERO_DEDUCIBLES NUMBER,
    DEDUCIBLE NUMBER,
    NUMERO_DEMERITOS NUMBER,
    IMPORTE_DEMERITO NUMBER,
    DN_MONEDA_NACIONAL_DEDUCIBLE NUMBER,
    NO_PROCEDE VARCHAR2(4000),
    RECHAZADO VARCHAR2(4000),
    POLIZA_PERIODO_GRACIA VARCHAR2(4000),
    REPARACIONES NUMBER,
    INICIAL_MO NUMBER,
    INICIAL_REF NUMBER,
    COMP_MO NUMBER,
    COMP_REF NUMBER,
    TOTAL_VALUACION NUMBER,
    ESTADO VARCHAR2(4000),
    VALUACION_TIPO_VEHICULO VARCHAR2(4000),
    SUMA_ASEGURADA NUMBER,
    IMPORTE_REPARACIONES NUMBER,
    ANTIGUEDAD VARCHAR2(4000),
    AJUSTADOR VARCHAR2(4000),
    OFICINA_AJUSTADOR VARCHAR2(4000),
    REG_AJUSTADOR VARCHAR2(4000),
    CLASE_TIPO_VEHICULO VARCHAR2(4000),
    IDENTIFICADOR VARCHAR2(4000),
    PIEZAS_REPARADAS NUMBER,
    PIEZAS_SUSTITUIDAS NUMBER,
    MONTOS_REPARACION NUMBER,
    MONTOS_SUSTITUCION NUMBER,
    MARCA_PROVEEDOR VARCHAR2(4000),
    FECHA_COMPLE DATE,
    DIAS_VAL_MOD VARCHAR2(4000),
    NUM_COMP_MO NUMBER,
    NUM_COMP_REF NUMBER,
    TIPO_SISE VARCHAR2(4000),
    VALVSCAPTURA VARCHAR2(4000),
    TIPO_CAPTURA VARCHAR2(4000),
    COMPLEMENTOS VARCHAR2(4000),
    SINIESTRO VARCHAR2(4000),
    POLIZA VARCHAR2(4000),
    INCISO VARCHAR2(4000),
    CAUSA VARCHAR2(4000),
    GRUPOCOMERCIAL VARCHAR2(4000),
    COBERTURA VARCHAR2(4000),
    PAQUETE VARCHAR2(4000),
    COD_ESTATUS_VAL VARCHAR2(4000),
    SUBR VARCHAR2(4000),
    CATEGORIA VARCHAR2(4000),
    USO VARCHAR2(4000),
    CODIGO_CATEGORIA_VEHICULO VARCHAR2(4000),
    DESCRIPCION_CATEGORIA_VEHICULO VARCHAR2(4000),
    CODIGO_CAUSA VARCHAR2(4000),
    SERIE VARCHAR2(4000),
    TIEMPO_DE_VALUACION NUMBER,
    TIEMPO_DE_TERMINO NUMBER,
    TIEMPO_DE_TALLER NUMBER,
    REPORTE VARCHAR2(4000),
    REPORTECOBE VARCHAR2(4000),
    NUMERO_PIEZAS NUMBER,
    NUMERO_PIEZAS_ORIGINAL NUMBER,
    NUMERO_COMPLEMENTOS NUMBER,
    SUMAASEG NUMBER,
    TIPO_POLIZA VARCHAR2(4000),
    PISO NUMBER,
    TRANSITO NUMBER,
    CATVAL VARCHAR2(4000),
    DESC_COBER VARCHAR2(4000),
    TP_VAL VARCHAR2(4000),
    CONVENIO NUMBER,
    PT_USUARIO VARCHAR2(4000),
    PT_OFICINA VARCHAR2(4000),
    QVSQ NUMBER,
    FECHA_PAGO DATE
);