BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_TIPOS_PROVEEDORES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE INSUMOS.DM_TIPOS_PROVEEDORES (
    ID VARCHAR2(4000) PRIMARY KEY,
    TIPO_PROVEEDOR VARCHAR2(4000),
    GRUPO VARCHAR2(4000),
    NOMBRE_GRUPO VARCHAR2(4000)
);