CREATE USER RAW_INSUMOS 
IDENTIFIED BY RAW_INSUMOS  -- Reemplaza "contraseña" con una contraseña segura
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO RAW_INSUMOS;

-- Paso 3: Otorgar privilegios específicos para trabajar dentro de su propio esquema
GRANT CREATE SESSION TO RAW_INSUMOS;
GRANT CREATE TABLE TO RAW_INSUMOS;
GRANT CREATE VIEW TO RAW_INSUMOS;
GRANT CREATE PROCEDURE TO RAW_INSUMOS;
GRANT CREATE TRIGGER TO RAW_INSUMOS;
GRANT CREATE SEQUENCE TO RAW_INSUMOS;
GRANT CREATE SYNONYM TO RAW_INSUMOS;
GRANT CREATE MATERIALIZED VIEW TO RAW_INSUMOS;
GRANT CREATE TYPE TO RAW_INSUMOS;