SELECT
    Z_ID,
    REPLACE(REPLACE(REPLACE(OFICINA, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS OFICINA,
    REPLACE(REPLACE(REPLACE(DIRECCION, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS DIRECCION,
    REPLACE(REPLACE(REPLACE(COLONIA, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS COLONIA,
    REPLACE(REPLACE(REPLACE(POBLACION, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS POBLACION,
    REPLACE(REPLACE(REPLACE(EDOPOB, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS EDOPOB,
    REPLACE(REPLACE(REPLACE(CP, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS CP,
    REPLACE(REPLACE(REPLACE(ZONA, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS ZONA
FROM
    BSCSiniestros.dbo.TSUC_BSC;