SELECT 
    REPLACE(REPLACE(REPLACE(Z_ID, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS Z_ID,
    REPLACE(REPLACE(REPLACE(EDOPOB, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS EDOPOB,
    REPLACE(REPLACE(REPLACE(ESTATUS, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS ESTATUS,
    REPLACE(REPLACE(REPLACE(CVEMPIO_INEGI, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS CVEMPIO_INEGI,
    REPLACE(REPLACE(REPLACE(REGION, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS REGION,
    REPLACE(REPLACE(REPLACE(RADIOPERFIL, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS RADIOPERFIL,
    REPLACE(REPLACE(REPLACE(EDO_ESTANDAR, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS EDO_ESTANDAR,
    REPLACE(REPLACE(REPLACE(EDOPOB2, CHAR(10), ''), CHAR(13), ''), CHAR(9), '') AS EDOPOB2
FROM 
    BSCSiniestros.dbo.TESTADO_BSC;