SELECT * FROM "VAL2"."DATOSVEHICULO"
WHERE 1=1
AND IDEXPEDIENTE IN (SELECT DISTINCT IDEXPEDIENTE FROM "VAL2"."DATOSGENERALES" WHERE TO_NUMBER(EJERCICIO) >= (TO_NUMBER(SUBSTR('${final_date}', 3, 2)) - 2)
AND TO_NUMBER(EJERCICIO) <= TO_NUMBER(SUBSTR('${final_date}', 3, 2)) )
AND $CONDITIONS


(SELECT DISTINCT IDVALE FROM "VAL2"."VALE"
WHERE IDEXPEDIENTE IN (SELECT DISTINCT IDEXPEDIENTE FROM "VAL2"."DATOSGENERALES" WHERE TO_NUMBER(EJERCICIO) >= (TO_NUMBER(SUBSTR('${final_date}', 3, 2)) - 2)
AND TO_NUMBER(EJERCICIO) <= TO_NUMBER(SUBSTR('${final_date}', 3, 2)) ))


