CREATE TABLE `qlts-dev-mx-au-bro-verificacio.DM_VERIFICACIONES.DM_ASEGURADOS`
(
  ID STRING,
  NOMBRE STRING,
  GIRO STRING,
  NACIONALIDAD STRING,
  FOLIO STRING,
  APODERADO STRING,
  NACIMIENTO_APODERADO STRING,
  RFC STRING,
  ART_140 STRING,
  FECHA_NACIMIENTO DATETIME,
  FECHA_ALTA DATETIME,
  TIPO_ASEGURADOS STRING,
  CORREO STRING,
  CURP STRING,
  ID_OFICINA STRING,
  NOMBRE_OFICINA STRING
);
