BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_AGENTES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE INSUMOS.DM_AGENTES (
  CODIGO_OFICINA VARCHAR2(16),
  CODIGO_GERENTE VARCHAR2(16),
  CODIGO_AGENTE VARCHAR2(16)PRIMARY KEY,
  AGENTE VARCHAR2(256)
);