BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_ANALISTAS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE INSUMOS.DM_ANALISTAS (
    ID VARCHAR2(4000) PRIMARY KEY,
    ANALISTA VARCHAR2(4000),
    NOMBRE VARCHAR2(4000),
    CORREO VARCHAR2(4000),
    ESTATUS VARCHAR2(4000),
    CARRUSEL NUMBER,
    ID_USER_94 VARCHAR2(4000),
    FECHA_LOTE DATE,
    ID_USUARIO_SISTEMA VARCHAR2(4000)
);