BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_CERCO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE INSUMOS.DM_CERCO
(
    IDCERCO                 VARCHAR2(4000) PRIMARY KEY,
    NOMBRE                  VARCHAR2(4000),
    FECHAREGISTRO           DATE,
    FECHAACTUALIZACION      DATE,
    IDENTIDAD               VARCHAR2(4000),
    SUSPAUT                 VARCHAR2(4000),
    IDCATEGORIACERCO        VARCHAR2(4000),
    IDSEGMENTACION          VARCHAR2(4000)
);