BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_ESTADO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE INSUMOS.DM_ESTADO
(
    IDESTADO                VARCHAR2(4000) NOT NULL PRIMARY KEY,
    NOMBRE                  VARCHAR2(4000),
    IDREGIONGEOGRAFICA      NUMBER,
    ACTIVO                  NUMBER
);