BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_ESTATUS_EXPEDIENTES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE INSUMOS.DM_ESTATUS_EXPEDIENTES
(
    IDESTATUSEXPEDIENTE     VARCHAR2(4000) NOT NULL PRIMARY KEY,
    DESCRIPCION             VARCHAR2(4000),
    ALTA                    DATE,
    ACTUALIZACION           DATE,
    USUARIOACTUALIZA        VARCHAR2(4000)
);