BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_GERENTES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE INSUMOS.DM_GERENTES (
  CODIGO_OFICINA VARCHAR2(16),
  CODIGO_GERENTE VARCHAR2(16) PRIMARY KEY,
  GERENTE VARCHAR2(256)
);