BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_REFACCION CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE INSUMOS.DM_REFACCION
(
    IDREFACCION             VARCHAR2(4000) NOT NULL PRIMARY KEY,
    DESCRIPCION             VARCHAR2(4000),
    ALTA                    DATE,
    ACTUALIZACION           DATE,
    USUARIOACTUALIZA        VARCHAR2(4000),
    AUTOS                   VARCHAR2(4000),
    EP                      VARCHAR2(4000)
);