BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_SUPERVISOR_INTEGRAL CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE INSUMOS.DM_SUPERVISOR_INTEGRAL
(
    IDSUPERVISORINTEGRAL    VARCHAR2(4000) NOT NULL PRIMARY KEY,
    CLAVESUPERVISOR         VARCHAR2(4000) NOT NULL,
    NOMBRESUPERVISOR        VARCHAR2(4000) NOT NULL,
    CORREO                  VARCHAR2(4000) NOT NULL,
    TELEFONO                VARCHAR2(4000) NOT NULL,
    IDREGIONGEOGRAFICA      VARCHAR2(4000) NOT NULL,
    ESTATUS                 NUMBER NOT NULL,
    FECHAREGISTRO           DATE NOT NULL,
    FECHAACTUALIZACION      DATE NOT NULL,
    USUARIOREGISTRO         VARCHAR2(4000) NOT NULL
);