BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_VALE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE INSUMOS.DM_VALE
(
    IDVALE                  VARCHAR2(4000) PRIMARY KEY,
    IDEXPEDIENTE            VARCHAR2(4000),
    CODPROVEEDOR            VARCHAR2(4000),
    MONTO                   NUMBER,
    FOLIO                   VARCHAR2(4000),
    FECHAEXPEDICION         DATE,
    FECHAACTUALIZACION      DATE,
    IDVALEESTATUS           VARCHAR2(4000),
    VALE                    BLOB,
    LEIDOORDEN              NUMBER,
    LEIDOVALE               NUMBER,
    PIEZASRECIBIDAS         NUMBER,
    AUTORIZADOR             VARCHAR2(4000),
    COTIZADOR               NUMBER,
    TOTALDESRESCATEPT       NUMBER,
    ESTATUSVALESISE         VARCHAR2(4000),
    MONTOPAGADOSISE         VARCHAR2(4000),
    FECHAPAGOSISE           DATE,
    PENDIENTELIBERAR        NUMBER NOT NULL,
    DEVUELTO                VARCHAR2(4000) NOT NULL,
    ESTATUSACTUALSISE       VARCHAR2(4000)
);