-- =====================================================
-- SCRIPT DE ÍNDICES RECOMENDADOS PARA ESQUEMA INSUMOS
-- =====================================================

-- ===========================
-- TABLA: DM_AGENTES
-- ===========================
-- Índices para búsquedas por oficina y gerente
CREATE INDEX IDX_AGENTES_OFICINA ON INSUMOS.DM_AGENTES(CODIGO_OFICINA);
CREATE INDEX IDX_AGENTES_GERENTE ON INSUMOS.DM_AGENTES(CODIGO_GERENTE);
CREATE INDEX IDX_AGENTES_OFICINA_GERENTE ON INSUMOS.DM_AGENTES(CODIGO_OFICINA, CODIGO_GERENTE);

-- ===========================
-- TABLA: DM_ANALISTAS
-- ===========================
-- Índices para búsquedas frecuentes
CREATE INDEX IDX_ANALISTAS_ESTATUS ON INSUMOS.DM_ANALISTAS(ESTATUS);
CREATE INDEX IDX_ANALISTAS_FECHA_LOTE ON INSUMOS.DM_ANALISTAS(FECHA_LOTE);
CREATE INDEX IDX_ANALISTAS_USER_94 ON INSUMOS.DM_ANALISTAS(ID_USER_94);
CREATE INDEX IDX_ANALISTAS_USUARIO_SISTEMA ON INSUMOS.DM_ANALISTAS(ID_USUARIO_SISTEMA);

-- ===========================
-- TABLA: DM_APERCAB (Tabla principal de reportes)
-- ===========================
-- Índices críticos para rendimiento
CREATE INDEX IDX_APERCAB_SINIESTRO ON INSUMOS.DM_APERCAB(SINIESTRO);
CREATE INDEX IDX_APERCAB_POLIZA ON INSUMOS.DM_APERCAB(POLIZA);
CREATE INDEX IDX_APERCAB_AJUSTADOR ON INSUMOS.DM_APERCAB(CLAVE_AJUSTADOR);
CREATE INDEX IDX_APERCAB_AGENTE ON INSUMOS.DM_APERCAB(CLAVE_AGENTE);
CREATE INDEX IDX_APERCAB_FECHA_REPORTE ON INSUMOS.DM_APERCAB(FECHA_REPORTE);
CREATE INDEX IDX_APERCAB_FECHA_OCURRIDO ON INSUMOS.DM_APERCAB(FECHA_OCURRIDO);
CREATE INDEX IDX_APERCAB_FECHA_REGISTRO ON INSUMOS.DM_APERCAB(FECHA_REGISTRO);
CREATE INDEX IDX_APERCAB_OFICINA_VTA ON INSUMOS.DM_APERCAB(OFICINA_VTA);
CREATE INDEX IDX_APERCAB_CAUSA ON INSUMOS.DM_APERCAB(CAUSA);
CREATE INDEX IDX_APERCAB_ESTADO_ACC ON INSUMOS.DM_APERCAB(CODIGO_ESTADO_ACCIDENTE);
CREATE INDEX IDX_APERCAB_POBLACION_ACC ON INSUMOS.DM_APERCAB(CODIGO_POBLACION_ACCIDENTE);

-- Índices compuestos para consultas complejas
CREATE INDEX IDX_APERCAB_FECHA_OFICINA ON INSUMOS.DM_APERCAB(FECHA_REPORTE, OFICINA_VTA);
CREATE INDEX IDX_APERCAB_AGENTE_FECHA ON INSUMOS.DM_APERCAB(CLAVE_AGENTE, FECHA_REPORTE);
CREATE INDEX IDX_APERCAB_AJUSTADOR_FECHA ON INSUMOS.DM_APERCAB(CLAVE_AJUSTADOR, FECHA_REPORTE);

-- ===========================
-- TABLA: DM_CAUSAS
-- ===========================
CREATE INDEX IDX_CAUSAS_FECHA_LOTE ON INSUMOS.DM_CAUSAS(FECHA_LOTE);
CREATE INDEX IDX_CAUSAS_USUARIO_SISTEMA ON INSUMOS.DM_CAUSAS(ID_USUARIO_SISTEMA);

-- ===========================
-- TABLA: DM_COBERTURAS_MOVIMIENTOS
-- ===========================
-- Índices críticos para análisis de siniestros
CREATE INDEX IDX_COBMOV_SINIESTRO ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(SINIESTRO);
CREATE INDEX IDX_COBMOV_POLIZA ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(POLIZA);
CREATE INDEX IDX_COBMOV_REPORTE ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(REPORTE);
CREATE INDEX IDX_COBMOV_FECHA_REGISTRO ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(FECHA_REGISTRO);
CREATE INDEX IDX_COBMOV_FECHA_MOVIMIENTO ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(FECHA_MOVIMIENTO);
CREATE INDEX IDX_COBMOV_FECHA_OCURRIDO ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(FECHA_OCURRIDO);
CREATE INDEX IDX_COBMOV_OFICINA_VENTAS ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(ID_OFICINA_VENTAS);
CREATE INDEX IDX_COBMOV_OFICINA_ATENCION ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(ID_OFICINA_DE_ATENCION);
CREATE INDEX IDX_COBMOV_AJUSTADOR ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(AJUSTADOR);
CREATE INDEX IDX_COBMOV_AGENTE ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(AGENTE);
CREATE INDEX IDX_COBMOV_GERENTE ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(GERENTE);
CREATE INDEX IDX_COBMOV_TIPO_MOVIMIENTO ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(TIPO_MOVIMIENTO);
CREATE INDEX IDX_COBMOV_COBERTURA ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(COBERTURA);
CREATE INDEX IDX_COBMOV_CODIGO_COBERTURA ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(CODIGO_COBERTURA);

-- Índices compuestos para análisis financiero
CREATE INDEX IDX_COBMOV_FECHA_TIPO_MOV ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(FECHA_MOVIMIENTO, TIPO_MOVIMIENTO);
CREATE INDEX IDX_COBMOV_POLIZA_FECHA ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(POLIZA, FECHA_MOVIMIENTO);
CREATE INDEX IDX_COBMOV_AGENTE_FECHA ON INSUMOS.DM_COBERTURAS_MOVIMIENTOS(AGENTE, FECHA_MOVIMIENTO);

-- ===========================
-- TABLA: DM_DATOS_GENERALES
-- ===========================
-- Índices para valuaciones y seguimiento
CREATE INDEX IDX_DATGEN_POLIZA ON INSUMOS.DM_DATOS_GENERALES(NUMERO_POLIZA);
CREATE INDEX IDX_DATGEN_SINIESTRO ON INSUMOS.DM_DATOS_GENERALES(NUMERO_SINIESTRO);
CREATE INDEX IDX_DATGEN_REPORTE ON INSUMOS.DM_DATOS_GENERALES(NUMERO_REPORTE);
CREATE INDEX IDX_DATGEN_VALUADOR ON INSUMOS.DM_DATOS_GENERALES(CODIGO_VALUADOR);
CREATE INDEX IDX_DATGEN_TALLER ON INSUMOS.DM_DATOS_GENERALES(CLAVE_TALLER);
CREATE INDEX IDX_DATGEN_TIPO_PROVEEDOR ON INSUMOS.DM_DATOS_GENERALES(TIPO_PROVEEDOR);
CREATE INDEX IDX_DATGEN_EXPEDIENTE ON INSUMOS.DM_DATOS_GENERALES(ID_EXPEDIENTE);
CREATE INDEX IDX_DATGEN_AGENTE ON INSUMOS.DM_DATOS_GENERALES(AGENTE);
CREATE INDEX IDX_DATGEN_ASEGURADO ON INSUMOS.DM_DATOS_GENERALES(CODIGO_ASEGURADO);

-- ===========================
-- TABLA: DM_DUA
-- ===========================
-- Índices para reportes DUA
CREATE INDEX IDX_DUA_FECHA_OCURRIDO ON INSUMOS.DM_DUA(DU_FECHA_OCURRIDO);
CREATE INDEX IDX_DUA_FECHA_ATENCION ON INSUMOS.DM_DUA(DU_FECHA_ATENCION);
CREATE INDEX IDX_DUA_PROCESO ON INSUMOS.DM_DUA(PROCESO);
CREATE INDEX IDX_DUA_POLIZA ON INSUMOS.DM_DUA(DU_NUM_POLIZA);
CREATE INDEX IDX_DUA_SINIESTRO ON INSUMOS.DM_DUA(DU_NUM_SINIESTRO);

-- ===========================
-- TABLA: DM_ESTADOS
-- ===========================
CREATE INDEX IDX_ESTADOS_CODIGO ON INSUMOS.DM_ESTADOS(CODIGO_ESTADO);
CREATE INDEX IDX_ESTADOS_INEGI ON INSUMOS.DM_ESTADOS(CLAVE_INEGI);
CREATE INDEX IDX_ESTADOS_REGION ON INSUMOS.DM_ESTADOS(REGION);

-- ===========================
-- TABLA: DM_ETIQUETA_SINIESTRO
-- ===========================
CREATE INDEX IDX_ETIQ_REPORTE ON INSUMOS.DM_ETIQUETA_SINIESTRO(ID_REPORTE);
CREATE INDEX IDX_ETIQ_SINIESTRO ON INSUMOS.DM_ETIQUETA_SINIESTRO(ID_SINIESTRO);
CREATE INDEX IDX_ETIQ_ESTATUS ON INSUMOS.DM_ETIQUETA_SINIESTRO(CODIGO_ESTATUS);
CREATE INDEX IDX_ETIQ_FECHA_INVESTIGACION ON INSUMOS.DM_ETIQUETA_SINIESTRO(FECHA_INVESTIGACION);
CREATE INDEX IDX_ETIQ_FECHA_LOTE ON INSUMOS.DM_ETIQUETA_SINIESTRO(FECHA_LOTE);
CREATE INDEX IDX_ETIQ_VALIDO ON INSUMOS.DM_ETIQUETA_SINIESTRO(VALIDO);
CREATE INDEX IDX_ETIQ_VIGENCIA ON INSUMOS.DM_ETIQUETA_SINIESTRO(VALIDO_DESDE, VALIDO_HASTA);

-- ===========================
-- TABLA: DM_GERENTES
-- ===========================
CREATE INDEX IDX_GERENTES_OFICINA ON INSUMOS.DM_GERENTES(CODIGO_OFICINA);

-- ===========================
-- TABLA: DM_INCISOS_POLIZAS
-- ===========================
-- Índices críticos para pólizas
CREATE INDEX IDX_INCISOS_POLIZA ON INSUMOS.DM_INCISOS_POLIZAS(POLIZA);
CREATE INDEX IDX_INCISOS_ENDOSO ON INSUMOS.DM_INCISOS_POLIZAS(ENDOSO);
CREATE INDEX IDX_INCISOS_POLIZA_ENDOSO ON INSUMOS.DM_INCISOS_POLIZAS(POLIZA_ENDOSO);
CREATE INDEX IDX_INCISOS_SERIE ON INSUMOS.DM_INCISOS_POLIZAS(SERIE);
CREATE INDEX IDX_INCISOS_PLACAS ON INSUMOS.DM_INCISOS_POLIZAS(PLACAS);
CREATE INDEX IDX_INCISOS_MARCA ON INSUMOS.DM_INCISOS_POLIZAS(MARCA_COMP);
CREATE INDEX IDX_INCISOS_MODELO ON INSUMOS.DM_INCISOS_POLIZAS(MODELO);
CREATE INDEX IDX_INCISOS_SUBRAMO ON INSUMOS.DM_INCISOS_POLIZAS(SUBRAMO);
CREATE INDEX IDX_INCISOS_FECHA_PROCESO ON INSUMOS.DM_INCISOS_POLIZAS(FECHA_PROCESO);
CREATE INDEX IDX_INCISOS_FECHA_CARGA ON INSUMOS.DM_INCISOS_POLIZAS(FECHA_CARGA);
CREATE INDEX IDX_INCISOS_ULTIMO_ENDOSO ON INSUMOS.DM_INCISOS_POLIZAS(ULTIMO_ENDOSO);

-- ===========================
-- TABLA: DM_OFICINAS
-- ===========================
CREATE INDEX IDX_OFICINAS_POBLACION ON INSUMOS.DM_OFICINAS(POBLACION);
CREATE INDEX IDX_OFICINAS_CODIGO_POBLACION ON INSUMOS.DM_OFICINAS(CODIGO_POBLACION);
CREATE INDEX IDX_OFICINAS_ZONA ON INSUMOS.DM_OFICINAS(ZONA);

-- ===========================
-- TABLA: DM_PAGOS_POLIZAS
-- ===========================
CREATE INDEX IDX_PAGOS_POL_POLIZA ON INSUMOS.DM_PAGOS_POLIZAS(POLIZA);
CREATE INDEX IDX_PAGOS_POL_ENDOSO ON INSUMOS.DM_PAGOS_POLIZAS(ENDOSO);
CREATE INDEX IDX_PAGOS_POL_POLIZA_ENDOSO ON INSUMOS.DM_PAGOS_POLIZAS(POLIZA_ENDOSO);
CREATE INDEX IDX_PAGOS_POL_FECHA_VENC ON INSUMOS.DM_PAGOS_POLIZAS(FECHA_VENCIMIENTO);
CREATE INDEX IDX_PAGOS_POL_FECHA_APLICACION ON INSUMOS.DM_PAGOS_POLIZAS(FECHA_APLICACION);
CREATE INDEX IDX_PAGOS_POL_STATUS ON INSUMOS.DM_PAGOS_POLIZAS(STATUS);
CREATE INDEX IDX_PAGOS_POL_FECHA_PROCESO ON INSUMOS.DM_PAGOS_POLIZAS(FECHA_PROCESO);
CREATE INDEX IDX_PAGOS_POL_FECHA_CARGA ON INSUMOS.DM_PAGOS_POLIZAS(FECHA_CARGA);

-- ===========================
-- TABLA: DM_PAGOS_PROVEEDORES
-- ===========================
CREATE INDEX IDX_PAGOS_PROV_PROVEEDOR ON INSUMOS.DM_PAGOS_PROVEEDORES(ID_PROVEEDOR);
CREATE INDEX IDX_PAGOS_PROV_POLIZA ON INSUMOS.DM_PAGOS_PROVEEDORES(POLIZA);
CREATE INDEX IDX_PAGOS_PROV_SINIESTRO ON INSUMOS.DM_PAGOS_PROVEEDORES(ID_SINIESTRO);
CREATE INDEX IDX_PAGOS_PROV_FECHA_PAGO ON INSUMOS.DM_PAGOS_PROVEEDORES(FECHA_PAGO);
CREATE INDEX IDX_PAGOS_PROV_FECHA_OCURRIDO ON INSUMOS.DM_PAGOS_PROVEEDORES(FECHA_OCURRIDO);
CREATE INDEX IDX_PAGOS_PROV_FECHA_REGISTRO ON INSUMOS.DM_PAGOS_PROVEEDORES(FECHA_REGISTRO);
CREATE INDEX IDX_PAGOS_PROV_AJUSTADOR ON INSUMOS.DM_PAGOS_PROVEEDORES(ID_AJUSTADOR);
CREATE INDEX IDX_PAGOS_PROV_AGENTE ON INSUMOS.DM_PAGOS_PROVEEDORES(ID_AGENTE);
CREATE INDEX IDX_PAGOS_PROV_OFICINA_EMISION ON INSUMOS.DM_PAGOS_PROVEEDORES(ID_OFICINA_EMISION);
CREATE INDEX IDX_PAGOS_PROV_OFICINA_ATENCION ON INSUMOS.DM_PAGOS_PROVEEDORES(ID_OFICINA_ATENCION);
CREATE INDEX IDX_PAGOS_PROV_TIPO_GASTO ON INSUMOS.DM_PAGOS_PROVEEDORES(TIPO_GASTO);
CREATE INDEX IDX_PAGOS_PROV_COBERTURA ON INSUMOS.DM_PAGOS_PROVEEDORES(COBERTURA);

-- Índices compuestos para análisis financiero
CREATE INDEX IDX_PAGOS_PROV_FECHA_PROVEEDOR ON INSUMOS.DM_PAGOS_PROVEEDORES(FECHA_PAGO, ID_PROVEEDOR);
CREATE INDEX IDX_PAGOS_PROV_AGENTE_FECHA ON INSUMOS.DM_PAGOS_PROVEEDORES(ID_AGENTE, FECHA_PAGO);

-- ===========================
-- TABLA: DM_POLIZAS_VIGENTES
-- ===========================
-- Índices críticos para pólizas vigentes
CREATE INDEX IDX_POLVIG_POLIZA ON INSUMOS.DM_POLIZAS_VIGENTES(POLIZA);
CREATE INDEX IDX_POLVIG_ENDOSO ON INSUMOS.DM_POLIZAS_VIGENTES(ENDOSO);
CREATE INDEX IDX_POLVIG_POLIZA_ENDOSO ON INSUMOS.DM_POLIZAS_VIGENTES(POLIZA_ENDOSO);
CREATE INDEX IDX_POLVIG_ASEGURADO ON INSUMOS.DM_POLIZAS_VIGENTES(ID_ASEGURADO);
CREATE INDEX IDX_POLVIG_AGENTE ON INSUMOS.DM_POLIZAS_VIGENTES(AGENTE);
CREATE INDEX IDX_POLVIG_OFICINA ON INSUMOS.DM_POLIZAS_VIGENTES(ID_OFICINA);
CREATE INDEX IDX_POLVIG_FECHA_EMISION ON INSUMOS.DM_POLIZAS_VIGENTES(FECHA_EMISION);
CREATE INDEX IDX_POLVIG_VIGENCIA_DESDE ON INSUMOS.DM_POLIZAS_VIGENTES(VIGENCIA_DESDE);
CREATE INDEX IDX_POLVIG_VIGENCIA_HASTA ON INSUMOS.DM_POLIZAS_VIGENTES(VIGENCIA_HASTA);
CREATE INDEX IDX_POLVIG_FECHA_PROCESO ON INSUMOS.DM_POLIZAS_VIGENTES(FECHA_PROCESO);
CREATE INDEX IDX_POLVIG_FECHA_CARGA ON INSUMOS.DM_POLIZAS_VIGENTES(FECHA_CARGA);
CREATE INDEX IDX_POLVIG_ULTIMO_ENDOSO ON INSUMOS.DM_POLIZAS_VIGENTES(ULTIMO_ENDOSO);

-- Índices para consultas de vigencia
CREATE INDEX IDX_POLVIG_VIGENCIA ON INSUMOS.DM_POLIZAS_VIGENTES(VIGENCIA_DESDE, VIGENCIA_HASTA);
CREATE INDEX IDX_POLVIG_AGENTE_VIGENCIA ON INSUMOS.DM_POLIZAS_VIGENTES(AGENTE, VIGENCIA_DESDE, VIGENCIA_HASTA);

-- ===========================
-- TABLA: DM_REGISTRO
-- ===========================
CREATE INDEX IDX_REGISTRO_OFICINA ON INSUMOS.DM_REGISTRO(ID_OFICINA);
CREATE INDEX IDX_REGISTRO_ANALISTA ON INSUMOS.DM_REGISTRO(ID_ANALISTA);
CREATE INDEX IDX_REGISTRO_FECHA_ASIGNACION ON INSUMOS.DM_REGISTRO(FECHA_ASIGNACION);
CREATE INDEX IDX_REGISTRO_MOTIVO ON INSUMOS.DM_REGISTRO(ID_MOTIVO);
CREATE INDEX IDX_REGISTRO_FECHA_LOTE ON INSUMOS.DM_REGISTRO(FECHA_LOTE);
CREATE INDEX IDX_REGISTRO_USUARIO_SISTEMA ON INSUMOS.DM_REGISTRO(ID_USUARIO_SISTEMA);

-- ===========================
-- TABLA: DM_SINIESTROS (Tabla principal)
-- ===========================
-- Índices críticos para la tabla más importante
CREATE INDEX IDX_SINIESTROS_REPORTE ON INSUMOS.DM_SINIESTROS(REPORTE);
CREATE INDEX IDX_SINIESTROS_POLIZA ON INSUMOS.DM_SINIESTROS(POLIZA);
CREATE INDEX IDX_SINIESTROS_POLIZA_ENDOSO ON INSUMOS.DM_SINIESTROS(ID_POLIZA_ENDOSO);
CREATE INDEX IDX_SINIESTROS_POLIZA_ENDOSO_INCISO ON INSUMOS.DM_SINIESTROS(ID_POLIZA_ENDOSO_INCISO);
CREATE INDEX IDX_SINIESTROS_ASEGURADO ON INSUMOS.DM_SINIESTROS(ID_ASEGURADO);
CREATE INDEX IDX_SINIESTROS_CAUSA ON INSUMOS.DM_SINIESTROS(ID_CAUSA);
CREATE INDEX IDX_SINIESTROS_FECHA_OCURRIDO ON INSUMOS.DM_SINIESTROS(FECHA_OCURRIDO);
CREATE INDEX IDX_SINIESTROS_FECHA_REPORTE ON INSUMOS.DM_SINIESTROS(FECHA_REPORTE);
CREATE INDEX IDX_SINIESTROS_FECHA_REGISTRO ON INSUMOS.DM_SINIESTROS(FECHA_REGISTRO);
CREATE INDEX IDX_SINIESTROS_OFICINA ON INSUMOS.DM_SINIESTROS(ID_OFICINA);
CREATE INDEX IDX_SINIESTROS_OFICINA_ATENCION ON INSUMOS.DM_SINIESTROS(ID_OFICINA_DE_ATENCION);
CREATE INDEX IDX_SINIESTROS_AJUSTADOR ON INSUMOS.DM_SINIESTROS(ID_AJUSTADOR);
CREATE INDEX IDX_SINIESTROS_STATUS ON INSUMOS.DM_SINIESTROS(STATUS);
CREATE INDEX IDX_SINIESTROS_SERIE ON INSUMOS.DM_SINIESTROS(SERIE);
CREATE INDEX IDX_SINIESTROS_PLACA ON INSUMOS.DM_SINIESTROS(PLACA);
CREATE INDEX IDX_SINIESTROS_FECHA_LOTE ON INSUMOS.DM_SINIESTROS(FECHA_LOTE);

-- Índices compuestos para consultas complejas de siniestros
CREATE INDEX IDX_SINIESTROS_FECHA_STATUS ON INSUMOS.DM_SINIESTROS(FECHA_OCURRIDO, STATUS);
CREATE INDEX IDX_SINIESTROS_OFICINA_FECHA ON INSUMOS.DM_SINIESTROS(ID_OFICINA, FECHA_OCURRIDO);
CREATE INDEX IDX_SINIESTROS_AJUSTADOR_FECHA ON INSUMOS.DM_SINIESTROS(ID_AJUSTADOR, FECHA_OCURRIDO);

-- ===========================
-- TABLA: DM_TIPOS_PROVEEDORES
-- ===========================
CREATE INDEX IDX_TIPOS_PROV_GRUPO ON INSUMOS.DM_TIPOS_PROVEEDORES(GRUPO);

-- ===========================
-- TABLA: DM_VALUACIONES
-- ===========================
-- Índices críticos para valuaciones
CREATE INDEX IDX_VALUACIONES_SINIESTRO ON INSUMOS.DM_VALUACIONES(SINIESTRO);
CREATE INDEX IDX_VALUACIONES_POLIZA ON INSUMOS.DM_VALUACIONES(POLIZA);
CREATE INDEX IDX_VALUACIONES_REPORTE ON INSUMOS.DM_VALUACIONES(REPORTE);
CREATE INDEX IDX_VALUACIONES_VALUADORES ON INSUMOS.DM_VALUACIONES(VALUADORES);
CREATE INDEX IDX_VALUACIONES_PROVEEDORES ON INSUMOS.DM_VALUACIONES(PROVEEDORES);
CREATE INDEX IDX_VALUACIONES_AGENTE ON INSUMOS.DM_VALUACIONES(CLAVE_AGENTE);
CREATE INDEX IDX_VALUACIONES_GERENTE ON INSUMOS.DM_VALUACIONES(CLAVE_GERENTE);
CREATE INDEX IDX_VALUACIONES_AJUSTADOR ON INSUMOS.DM_VALUACIONES(AJUSTADOR);
CREATE INDEX IDX_VALUACIONES_FECHA_ASIGNACION ON INSUMOS.DM_VALUACIONES(FECHA_ASIGNACION);
CREATE INDEX IDX_VALUACIONES_FECHA_OCURRIDO ON INSUMOS.DM_VALUACIONES(FECHA_OCURRIDO);
CREATE INDEX IDX_VALUACIONES_FECHA_VALUACION ON INSUMOS.DM_VALUACIONES(FECHA_VALUACION);
CREATE INDEX IDX_VALUACIONES_FECHA_TERMINADO ON INSUMOS.DM_VALUACIONES(FECHA_TERMINADO);
CREATE INDEX IDX_VALUACIONES_FECHA_PAGO ON INSUMOS.DM_VALUACIONES(FECHA_PAGO);
CREATE INDEX IDX_VALUACIONES_ESTATUS ON INSUMOS.DM_VALUACIONES(ESTATUS_PROCESO);
CREATE INDEX IDX_VALUACIONES_TIPO_PROVEEDOR ON INSUMOS.DM_VALUACIONES(TIPO_PROVEEDOR);
CREATE INDEX IDX_VALUACIONES_TIPO_VALUACION ON INSUMOS.DM_VALUACIONES(TIPO_DE_VALUACION);

-- Índices compuestos para análisis de rendimiento
CREATE INDEX IDX_VALUACIONES_FECHA_ESTATUS ON INSUMOS.DM_VALUACIONES(FECHA_ASIGNACION, ESTATUS_PROCESO);
CREATE INDEX IDX_VALUACIONES_AGENTE_FECHA ON INSUMOS.DM_VALUACIONES(CLAVE_AGENTE, FECHA_ASIGNACION);



-- =====================================================
-- COMENTARIOS Y RECOMENDACIONES