CREATE USER INSUMOS 
IDENTIFIED BY INSUMOS  -- Reemplaza "contraseña" con una contraseña segura
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO INSUMOS;

-- Paso 3: Otorgar privilegios específicos para trabajar dentro de su propio esquema
GRANT CREATE SESSION TO INSUMOS;
GRANT CREATE TABLE TO INSUMOS;
GRANT CREATE VIEW TO INSUMOS;
GRANT CREATE PROCEDURE TO INSUMOS;
GRANT CREATE TRIGGER TO INSUMOS;
GRANT CREATE SEQUENCE TO INSUMOS;
GRANT CREATE SYNONYM TO INSUMOS;
GRANT CREATE MATERIALIZED VIEW TO INSUMOS;
GRANT CREATE TYPE TO INSUMOS;

GRANT CONNECT, RESOURCE TO SGFRAAP;

-- Paso 3: Otorgar privilegios específicos para trabajar dentro de su propio esquema
GRANT CREATE SESSION TO SGFRAAP;
GRANT CREATE TABLE TO SGFRAAP;
GRANT CREATE VIEW TO SGFRAAP;
GRANT CREATE PROCEDURE TO SGFRAAP;
GRANT CREATE TRIGGER TO SGFRAAP;
GRANT CREATE SEQUENCE TO SGFRAAP;
GRANT CREATE SYNONYM TO SGFRAAP;
GRANT CREATE MATERIALIZED VIEW TO SGFRAAP;
GRANT CREATE TYPE TO SGFRAAP;


GRANT CONNECT, RESOURCE TO RAW_INSUMOS;

-- Paso 3: Otorgar privilegios específicos para trabajar dentro de su propio esquema
GRANT CREATE SESSION TO RAW_INSUMOS;
GRANT CREATE TABLE TO RAW_INSUMOS;
GRANT CREATE VIEW TO RAW_INSUMOS;
GRANT CREATE PROCEDURE TO RAW_INSUMOS;
GRANT CREATE TRIGGER TO RAW_INSUMOS;
GRANT CREATE SEQUENCE TO RAW_INSUMOS;
GRANT CREATE SYNONYM TO RAW_INSUMOS;
GRANT CREATE MATERIALIZED VIEW TO RAW_INSUMOS;
GRANT CREATE TYPE TO RAW_INSUMOS;