CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.DM_CONTROL_FRAUDES.DM_RECUPERACIONES` AS
SELECT 
  -- 1. RAMO
  SAFE_CAST(SAFE_CAST(NULLIF(RAMO, '') AS FLOAT64) AS INT64) AS RAMO,
  
  -- 2. ANIO
  SAFE_CAST(SAFE_CAST(NULLIF(ANIO, '') AS FLOAT64) AS INT64) AS ANIO,
  
  -- 3. SINIESTRO
  SAFE_CAST(SAFE_CAST(NULLIF(SINIESTRO, '') AS FLOAT64) AS INT64) AS SINIESTRO,
  
  -- 4. POLIZA
  SAFE_CAST(SAFE_CAST(NULLIF(POLIZA, '') AS FLOAT64) AS INT64) AS POLIZA,
  
  -- 5. INCISO
  SAFE_CAST(SAFE_CAST(NULLIF(INCISO, '') AS FLOAT64) AS INT64) AS INCISO,
  
  -- 6. NOMBRE_ASEGURADO
  NOMBRE_ASEGURADO,
  
  -- 7. ORDEN_DE_PAGO
  SAFE_CAST(SAFE_CAST(NULLIF(ORDEN_DE_PAGO, '') AS FLOAT64) AS INT64) AS ORDEN_DE_PAGO,
  
  -- 8. FECHA_INGRESO (fecha Oracle formato ddMMMyyyy:hh:mm:ss)
  CASE 
    WHEN FECHA_INGRESO IS NOT NULL AND FECHA_INGRESO != '' 
    THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', FECHA_INGRESO)
    ELSE NULL 
  END AS FECHA_INGRESO,
  
  -- 9. MONTO_INGRESO
  SAFE_CAST(NULLIF(MONTO_INGRESO, '') AS FLOAT64) AS MONTO_INGRESO,
  
  -- 10. TIPO
  TIPO,
  
  -- 11. COBERTURA
  COBERTURA,
  
  -- 12. REA_CIAS_MEXICANAS
  SAFE_CAST(SAFE_CAST(NULLIF(REA_CIAS_MEXICANAS, '') AS FLOAT64) AS INT64) AS REA_CIAS_MEXICANAS,
  
  -- 13. REA_CIAS_EXTRANJERAS
  SAFE_CAST(SAFE_CAST(NULLIF(REA_CIAS_EXTRANJERAS, '') AS FLOAT64) AS INT64) AS REA_CIAS_EXTRANJERAS,
  
  -- 14. FECHA_DE_OCURRIDO (fecha Oracle formato ddMMMyyyy:hh:mm:ss)
  CASE 
    WHEN FECHA_DE_OCURRIDO IS NOT NULL AND FECHA_DE_OCURRIDO != '' 
    THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', FECHA_DE_OCURRIDO)
    ELSE NULL 
  END AS FECHA_DE_OCURRIDO,
  
  -- 15. CLAVE_AJUSTADOR
  SAFE_CAST(SAFE_CAST(NULLIF(CLAVE_AJUSTADOR, '') AS FLOAT64) AS INT64) AS CLAVE_AJUSTADOR,
  
  -- 16. NOMBRE_AJUSTADOR
  NOMBRE_AJUSTADOR,
  
  -- 17. REPORTE
  SAFE_CAST(SAFE_CAST(NULLIF(REPORTE, '') AS FLOAT64) AS INT64) AS REPORTE,
  
  -- 18. CVE_OFI_ATENCION
  SAFE_CAST(SAFE_CAST(NULLIF(CVE_OFI_ATENCION, '') AS FLOAT64) AS INT64) AS CVE_OFI_ATENCION,
  
  -- 19. OFI_ATENCION
  OFI_ATENCION,
  
  -- 20. CODIGO_INGRESO
  SAFE_CAST(SAFE_CAST(NULLIF(CODIGO_INGRESO, '') AS FLOAT64) AS INT64) AS CODIGO_INGRESO,
  
  -- 21. TIPO_INGRESO
  TIPO_INGRESO,
  
  -- 22. COMPANIA
  COMPANIA,
  
  -- 23. FEC_DEPOSITO (fecha Oracle formato ddMMMyyyy:hh:mm:ss)
  CASE 
    WHEN FEC_DEPOSITO IS NOT NULL AND FEC_DEPOSITO != '' 
    THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', FEC_DEPOSITO)
    ELSE NULL 
  END AS FEC_DEPOSITO,
  
  -- 24. MON_ING
  MON_ING,
  
  -- 25. FEC_REP (fecha Oracle formato ddMMMyyyy:hh:mm:ss)
  CASE 
    WHEN FEC_REP IS NOT NULL AND FEC_REP != '' 
    THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', FEC_REP)
    ELSE NULL 
  END AS FEC_REP,
  
  -- 26. CVE_OFI_AGENTE
  SAFE_CAST(SAFE_CAST(NULLIF(CVE_OFI_AGENTE, '') AS FLOAT64) AS INT64) AS CVE_OFI_AGENTE,
  
  -- 27. OFI_AGENTE
  OFI_AGENTE,
  
  -- 28. ZONA_REGIONAL
  ZONA_REGIONAL,
  
  -- 29. EST_INI_INV
  SAFE_CAST(NULLIF(EST_INI_INV, '') AS FLOAT64) AS EST_INI_INV,
  
  -- 30. PORCENT_COAS
  SAFE_CAST(NULLIF(PORCENT_COAS, '') AS FLOAT64) AS PORCENT_COAS,
  
  -- 31. T_CAMBIO
  T_CAMBIO,
  
  -- 32. USUARIO_QUE_AUTORIZA
  USUARIO_QUE_AUTORIZA,
  
  -- 33. ID_EST
  SAFE_CAST(SAFE_CAST(NULLIF(ID_EST, '') AS FLOAT64) AS INT64) AS ID_EST,
  
  -- 34. ID_COB
  SAFE_CAST(SAFE_CAST(NULLIF(ID_COB, '') AS FLOAT64) AS INT64) AS ID_COB,
  
  -- 35. FACTURA_E
  FACTURA_E,
  
  -- 36. NRO_SINIESTRO
  SAFE_CAST(SAFE_CAST(NULLIF(NRO_SINIESTRO, '') AS FLOAT64) AS INT64) AS NRO_SINIESTRO,
  
  -- 37. NRO_REPORTE
  SAFE_CAST(SAFE_CAST(NULLIF(NRO_REPORTE, '') AS FLOAT64) AS INT64) AS NRO_REPORTE,
  
  -- 38. BATCHDATE
  CASE 
    WHEN BATCHDATE IS NOT NULL AND BATCHDATE != '' THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', BATCHDATE)
    ELSE NULL 
  END AS BATCHDATE,  
  -- 39. SYSUSERID
  SYSUSERID

FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.RECUPERACIONES`;