CREATE OR REPLACE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}` AS
SELECT 
  -- 1. FEC_EMI (fecha Oracle formato ddMMMyyyy:hh:mm:ss)
  CASE 
    WHEN FEC_EMI IS NOT NULL AND FEC_EMI != '' 
    THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', FEC_EMI)
    ELSE NULL 
  END AS FEC_EMI,
  
  -- 2. RAMO
  SAFE_CAST(SAFE_CAST(NULLIF(RAMO, '') AS FLOAT64) AS INT64) AS RAMO,
  
  -- 3. POLIZA
  SAFE_CAST(SAFE_CAST(NULLIF(POLIZA, '') AS FLOAT64) AS INT64) AS POLIZA,
  
  -- 4. ENDOSO
  SAFE_CAST(SAFE_CAST(NULLIF(ENDOSO, '') AS FLOAT64) AS INT64) AS ENDOSO,
  
  -- 5. INC
  SAFE_CAST(SAFE_CAST(NULLIF(INC, '') AS FLOAT64) AS INT64) AS INC,
  
  -- 6. ASEGURADO
  ASEGURADO,
  
  -- 7. RFC
  RFC,
  
  -- 8. CALLE
  CALLE,
  
  -- 9. COLONIA
  COLONIA,
  
  -- 10. CP
  CP,
  
  -- 11. CIUDAD
  CIUDAD,
  
  -- 12. ESTADO
  ESTADO,
  
  -- 13. TELEFONO (mantener como STRING para preservar formato)
  TELEFONO,
  
  -- 14. CONDUCTOR
  CONDUCTOR,
  
  -- 15. INI_VIG (fecha Oracle formato ddMMMyyyy:hh:mm:ss)
  CASE 
    WHEN INI_VIG IS NOT NULL AND INI_VIG != '' 
    THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', INI_VIG)
    ELSE NULL 
  END AS INI_VIG,
  
  -- 16. FIN_VIG (fecha Oracle formato ddMMMyyyy:hh:mm:ss)
  CASE 
    WHEN FIN_VIG IS NOT NULL AND FIN_VIG != '' 
    THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', FIN_VIG)
    ELSE NULL 
  END AS FIN_VIG,
  
  -- 17. AMIS
  SAFE_CAST(SAFE_CAST(NULLIF(AMIS, '') AS FLOAT64) AS INT64) AS AMIS,
  
  -- 18. Q_MARCA
  Q_MARCA,
  
  -- 19. DESC_VEH
  DESC_VEH,
  
  -- 20. MODELO
  SAFE_CAST(SAFE_CAST(NULLIF(MODELO, '') AS FLOAT64) AS INT64) AS MODELO,
  
  -- 21. SUMA_ASEG
  SAFE_CAST(NULLIF(SUMA_ASEG, '') AS FLOAT64) AS SUMA_ASEG,
  
  -- 22. COBERTURA
  COBERTURA,
  
  -- 23. COLOR
  COLOR,
  
  -- 24. USO
  USO,
  
  -- 25. SERVICIO
  SERVICIO,
  
  -- 26. END_EE_AYC
  END_EE_AYC,
  
  -- 27. MOTOR
  MOTOR,
  
  -- 28. SERIE
  SERIE,
  
  -- 29. PLACAS
  PLACAS,
  
  -- 30. ELABORO
  ELABORO,
  
  -- 31. CVE_AGENTE
  SAFE_CAST(SAFE_CAST(NULLIF(CVE_AGENTE, '') AS FLOAT64) AS INT64) AS CVE_AGENTE,
  
  -- 32. MONEDA
  SAFE_CAST(SAFE_CAST(NULLIF(MONEDA, '') AS FLOAT64) AS INT64) AS MONEDA,
  
  -- 33. PRIMA_NETA
  SAFE_CAST(NULLIF(PRIMA_NETA, '') AS FLOAT64) AS PRIMA_NETA,
  
  -- 34. RECARGO
  SAFE_CAST(NULLIF(RECARGO, '') AS FLOAT64) AS RECARGO,
  
  -- 35. DERECHO
  SAFE_CAST(NULLIF(DERECHO, '') AS FLOAT64) AS DERECHO,
  
  -- 36. IMPUESTO
  SAFE_CAST(NULLIF(IMPUESTO, '') AS FLOAT64) AS IMPUESTO,
  
  -- 37. PRIMA_TOTAL
  SAFE_CAST(NULLIF(PRIMA_TOTAL, '') AS FLOAT64) AS PRIMA_TOTAL,
  
  -- 38. RECIBO
  RECIBO,
  
  -- 39. PT_RECIBO
  SAFE_CAST(NULLIF(PT_RECIBO, '') AS FLOAT64) AS PT_RECIBO,
  
  -- 40. PT_PAGADA
  SAFE_CAST(NULLIF(PT_PAGADA, '') AS FLOAT64) AS PT_PAGADA,
  
  -- 41. REMESA
  SAFE_CAST(SAFE_CAST(NULLIF(REMESA, '') AS FLOAT64) AS INT64) AS REMESA,
  
  -- 42. RC_EXTRANJERO
  SAFE_CAST(SAFE_CAST(NULLIF(RC_EXTRANJERO, '') AS FLOAT64) AS INT64) AS RC_EXTRANJERO,
  
  -- 43. COMISION
  SAFE_CAST(NULLIF(COMISION, '') AS FLOAT64) AS COMISION,
  
  -- 44. TIPO_PAGO
  TIPO_PAGO,
  
  -- 45. VIGENCIA
  VIGENCIA,
  
  -- 46. PT_PENDIENTE
  SAFE_CAST(NULLIF(PT_PENDIENTE, '') AS FLOAT64) AS PT_PENDIENTE,
  
  -- 47. BENEFICIARIO
  SAFE_CAST(SAFE_CAST(NULLIF(BENEFICIARIO, '') AS FLOAT64) AS INT64) AS BENEFICIARIO,
  
  -- 48. OTRO_BENEF
  OTRO_BENEF,
  
  -- 49. OFICINA
  OFICINA,
  
  -- 50. COD_SUAUTO
  COD_SUAUTO,
  
  -- 51. ZONA
  ZONA,
  
  -- 52. SUB_CLV_AGT
  SUB_CLV_AGT,
  
  -- 53. ESTATUS
  ESTATUS,
  
  -- 54. PORCENT_BT
  SAFE_CAST(NULLIF(PORCENT_BT, '') AS FLOAT64) AS PORCENT_BT,
  
  -- 55. GRABADO
  GRABADO,
  
  -- 56. TARJETA
  TARJETA,
  
  -- 57. NUM_CATALO
  SAFE_CAST(SAFE_CAST(NULLIF(NUM_CATALO, '') AS FLOAT64) AS INT64) AS NUM_CATALO,
  
  -- 58. AGENCIA
  AGENCIA,
  
  -- 59. NUM_AGENCIA
  NUM_AGENCIA,
  
  -- 60. TEXTO_AGTE
  TEXTO_AGTE,
  
  -- 61. NRO_ECO
  SAFE_CAST(SAFE_CAST(NULLIF(NRO_ECO, '') AS FLOAT64) AS INT64) AS NRO_ECO,
  
  -- 62. PNCCC
  PNCCC,
  
  -- 63. CVE_GEREN
  SAFE_CAST(SAFE_CAST(NULLIF(CVE_GEREN, '') AS FLOAT64) AS INT64) AS CVE_GEREN,
  
  -- 64. GERENTE
  GERENTE,
  
  -- 65. PN_COASEG
  SAFE_CAST(NULLIF(PN_COASEG, '') AS FLOAT64) AS PN_COASEG,
  
  -- 66. RECARGO_COASEG
  SAFE_CAST(NULLIF(RECARGO_COASEG, '') AS FLOAT64) AS RECARGO_COASEG,
  
  -- 67. DER_COASEG
  SAFE_CAST(NULLIF(DER_COASEG, '') AS FLOAT64) AS DER_COASEG,
  
  -- 68. IMPUESTO_COASEG
  SAFE_CAST(NULLIF(IMPUESTO_COASEG, '') AS FLOAT64) AS IMPUESTO_COASEG,
  
  -- 69. PT_COASEG
  SAFE_CAST(NULLIF(PT_COASEG, '') AS FLOAT64) AS PT_COASEG,
  
  -- 70. BATCHDATE
  CASE 
    WHEN BATCHDATE IS NOT NULL AND BATCHDATE != '' THEN SAFE.PARSE_DATETIME('%d%b%Y:%H:%M:%S', BATCHDATE)
    ELSE NULL 
  END AS BATCHDATE,
  
  -- 71. SYSUSERID
  SYSUSERID

FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`;