CREATE TABLE `qlts-dev-mx-au-bro-verificacio.DM_VERIFICACIONES.DM_OFICINAS`
(
  ID STRING,
  OFICINA STRING,
  DIRECCION STRING,
  COLONIA STRING,
  POBLACION STRING,
  CODIGO_POBLACION STRING,
  CODIGO_POSTAL STRING,
  ZONA STRING
);
