CREATE TABLE `qlts-dev-mx-au-bro-verificacio.DM_VERIFICACIONES.DM_ANALISTA_CDR`
(
  IDANALISTACDR STRING NOT NULL,
  CLAVEANALISTA STRING NOT NULL,
  NOMBRENNALISTA STRING NOT NULL,
  ESTATUS BIGNUMERIC NOT NULL,
  IDREGIONGEOGRAFICA STRING NOT NULL,
  FECHAREGISTROANL DATETIME NOT NULL,
  FECHAACTUALIZACIONANL DATETIME,
  CORREO STRING,
  TELEFONO STRING,
  CONSULTA BIGNUMERIC
);
