CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  ID STRING,
  OFICINA STRING,
  DIRECCION STRING,
  COLONIA STRING,
  POBLACION STRING,
  CODIGO_POBLACION STRING,
  CODIGO_POSTAL STRING,
  ZONA STRING
);
