CREATE TABLE `qlts-dev-mx-au-bro-verificacio.DM_VERIFICACIONES.DM_DATOS_VEHICULO`
(
  IDDATOSVEHICULO STRING,
  IDEXPEDIENTE STRING,
  IDVEHICULO STRING,
  IDUSO STRING,
  IDMARCA STRING,
  IDCOLOR STRING,
  CVESUBMARCA STRING,
  CVEAMIS STRING,
  TIPO STRING,
  MODELO STRING,
  PLACAS STRING,
  SERIE STRING,
  MOTOR STRING,
  USOAMIS STRING,
  PLACASANTERIOR STRING,
  SERIEANTERIOR STRING,
  IDUNIDAD STRING,
  IDMARCATALLER STRING
);
