CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  ID STRING,
  ID_REPORTE STRING,
  ID_SINIESTRO STRING,
  CODIGO_ESTATUS STRING,
  FECHA_INVESTIGACION DATETIME,
  TEXTO_INVESTIGACION STRING,
  USUARIO_INVESTIGACION STRING,
  TEXTO_LOCALIZADO STRING,
  FECHA_LOCALIZADO DATETIME,
  FECHA_CARGA DATETIME,
  FECHA_LOTE DATETIME,
  ID_USUARIO_SISTEMA STRING,
  CONSECUTIVO INT64,
  VALIDO_DESDE DATETIME,
  VALIDO_HASTA DATETIME,
  VALIDO BOOL
);
