CREATE TABLE `qlts-dev-mx-au-bro-verificacio.DM_VERIFICACIONES.DM_CALENDARIO`
(
  DATE DATE,
  DAY INT64,
  MONTH INT64,
  YEAR INT64,
  QUARTER INT64,
  PERIOD_NUMBER INT64,
  PERIOD_STRING STRING,
  DAY_OF_YEAR INT64,
  DAY_OF_WEEK INT64,
  WEEK INT64
);
