CREATE TABLE `qlts-dev-mx-au-bro-verificacio.DM_VERIFICACIONES.DM_ESTATUS_EXPEDIENTES`
(
  IDESTATUSEXPEDIENTE STRING NOT NULL,
  DESCRIPCION STRING,
  ALTA DATETIME,
  ACTUALIZACION DATETIME,
  USUARIOACTUALIZA STRING
);
