CREATE TABLE `qlts-dev-mx-au-bro-verificacio.DM_VERIFICACIONES.DM_SUPERVISOR_INTEGRAL`
(
  IDSUPERVISORINTEGRAL STRING NOT NULL,
  CLAVESUPERVISOR STRING NOT NULL,
  NOMBRESUPERVISOR STRING NOT NULL,
  CORREO STRING NOT NULL,
  TELEFONO STRING NOT NULL,
  IDREGIONGEOGRAFICA STRING NOT NULL,
  ESTATUS BIGNUMERIC NOT NULL,
  FECHAREGISTRO DATETIME NOT NULL,
  FECHAACTUALIZACION DATETIME NOT NULL,
  USUARIOREGISTRO STRING NOT NULL
);
