CREATE TABLE `qlts-dev-mx-au-bro-verificacio.DM_VERIFICACIONES.DM_CAUSA_CAMBIO_VALE`
(
  IDCAUSACAMBIOVALE STRING NOT NULL,
  DESCRIPCION STRING NOT NULL,
  FECHAREGISTRO DATETIME NOT NULL,
  FECHAACTUALIZACION DATETIME NOT NULL,
  USUARIO STRING NOT NULL
);
