CREATE TABLE `qlts-dev-mx-au-bro-verificacio.DM_VERIFICACIONES.DM_VALUACION`
(
  IDVALUACION STRING NOT NULL,
  DESCRIPCION STRING,
  ALTA DATETIME,
  ACTUALIZACION DATETIME,
  USUARIOACTUALIZA STRING
);
