CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  ID STRING,
  NOMBRE STRING,
  GIRO STRING,
  NACIONALIDAD STRING,
  FOLIO STRING,
  APODERADO STRING,
  NACIMIENTO_APODERADO STRING,
  RFC STRING,
  ART_140 STRING,
  FECHA_NACIMIENTO DATETIME,
  FECHA_ALTA DATETIME,
  TIPO_ASEGURADOS STRING,
  CORREO STRING,
  CURP STRING,
  ID_OFICINA STRING,
  NOMBRE_OFICINA STRING
);
