CREATE TABLE `qlts-dev-mx-au-bro-verificacio.DM_VERIFICACIONES.DM_REFACCION`
(
  IDREFACCION STRING NOT NULL,
  DESCRIPCION STRING,
  ALTA DATETIME,
  ACTUALIZACION DATETIME,
  USUARIOACTUALIZA STRING,
  AUTOS STRING,
  EP STRING
);
