CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  ID STRING,
  CAUSA STRING,
  CAUSA_HOMOLOGADA STRING,
  FECHA_LOTE DATETIME,
  ID_USUARIO_SISTEMA STRING
);
