CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  ID STRING,
  ESTADO_POBLACION STRING,
  ESTATUS STRING,
  CLAVE_INEGI STRING,
  REGION STRING,
  RADIO_PERFIL STRING,
  ESTADO_ESTANDAR STRING,
  ESTADO_POBLACION_2 STRING,
  CODIGO_ESTADO STRING,
  ESTADO STRING
);
