TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`; 
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}` 
SELECT 
  VALUACION
  ,VALUADORES
  ,TIPO_VALUADOR
  ,TIPO_DE_VALUACION
  ,OFICINA_VALUADOR
  ,REGIONAL_VALUACION
  ,PROVEEDORES
  ,ASEG_TERCERO
  ,TIPO_PROVEEDOR
  ,OFICINA_PROVEEDOR
  ,REGION_PROVEEDOR
  ,TIPO_NEGOCIO
  ,Director_Gerente AS DIRECTOR_GERENTE
  ,CVE_GERENTE AS CLAVE_GERENTE
  ,GERENTE AS GERENTE
  ,CVE_AGENTE AS CLAVE_AGENTE
  ,AGENTE
  ,OF_VENTAS AS OFICINA_VENTAS
  ,MODELO_VEHICULO 
  ,MARCAS
  ,TIPO_VEHICULO
  ,FECHA_ASIGNACION
  ,FECHA_OCURRIDO
  ,FECHA_INGRESO
  ,FECHA_VALUACION
  ,FECHA_PROMESA
  ,FECHA_TERMINADO
  ,FECHA_ENTREGA
  ,FECHA_CAPTURA
  ,FECHA_MODIFICACION
  ,MONEDA
  ,ESTATUS_PROCESO
  ,SIST_VALUACION AS SISTEMA_VALUACION
  ,VALUACIONES
  ,NUM_PT AS NUMERO_PT
  ,IMPORTE_PT 
  ,NUM_PD AS NUMERO_PD
  ,IMPORTE_PD
  ,NUM_DEDUCIBLES AS NUMERO_DEDUCIBLES
  ,DEDUCIBLE
  ,NUM_DEMERITOS AS NUMERO_DEMERITOS
  ,IMPORTE_DEMERITO
  ,DN_MN_DED DN_MONEDA_NACIONAL_DEDUCIBLE
  ,NO_PROCEDE 
  ,RECHAZADO
  ,POLIZA_PRIODO_GRACIA AS POLIZA_PERIODO_GRACIA
  ,REPARACIONES
  ,INICIAL_MO
  ,INICIAL_REF
  ,COMP_MO
  ,COMP_REF
  ,TOTAL_VALUACION
  ,Estado AS ESTADO
  ,VALUACION_TIPO_VEHICULO
  ,SUMA_ASEGURADA
  ,IMPORTE_REPARACIONES
  ,ANTIGUEDAD
  ,AJUSTADOR
  ,OF_AJUSTADOR AS OFICINA_AJUSTADOR
  ,REG_AJUSTADOR 
  ,CLASS_TIPOVEHICULO AS CLASE_TIPO_VEHICULO
  ,IDENTIFICADOR
  ,PIEZAS_REPARADAS
  ,PIEZAS_SUSTITUIDAS
  ,MONTOS_REPARACION
  ,MONTOS_SUSTITUCION
  ,MARCA_PROVEEDOR
  ,FECHA_COMPLE
  ,DIAS_VAL_MOD
  ,NUM_COMP_MO
  ,NUM_COMP_REF
  ,TIPOSISE AS TIPO_SISE
  ,VALVSCAPTURA
  ,TIPO_CAPTURA
  ,COMPLEMENTOS
  ,SINIESTRO
  ,POLIZA
  ,INCISO
  ,CAUSA
  ,GRUPOCOMERCIAL
  ,COBERTURA
  ,PAQUETE
  ,COD_ESTATUS_VAL 
  ,SUBR
  ,CATEGORIA
  ,USO
  ,COD_CAT_VEH AS CODIGO_CATEGORIA_VEHICULO
  ,DESC_CAT_VEH AS DESCRIPCION_CATEGORIA_VEHICULO
  ,COD_CAUSA AS CODIGO_CAUSA
  ,SERIE
  ,TIEMPO_DE_VALUACION
  ,TIEMPO_DE_TERMINO
  ,TIEMPO_DE_TALLER
  ,REPORTE
  ,REPORTECOBE
  ,NumPiezas AS NUMERO_PIEZAS
  ,NumPiezasOriginal AS NUMERO_PIEZAS_ORIGINAL
  ,NumComplementos AS NUMERO_COMPLEMENTOS
  ,SUMAASEG
  ,TIPOPOLIZA AS TIPO_POLIZA
  ,PISO
  ,TRANSITO
  ,CATVAL
  ,DESC_COBER
  ,TP_VAL
  ,CONVENIO
  ,PT_USUARIO
  ,PT_OFICINA
  ,QVSQ
  ,FEC_PAGO AS FECHA_PAGO
FROM  `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`
