TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`;
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`  
SELECT
  ZID AS ID,
  NOMBRE,
  GIRO,
  NACIONALIDAD,
  FOLIO,
  APODERADO,
  NAC_APODERADO AS NACIMIENTO_APODERADO,
  RFC,
  ART_140,
  FEC_NACE AS FECHA_NACIMIENTO,
  FEC_ALTA AS FECHA_ALTA,
  TIP_ASEG AS TIPO_ASEGURADOS,
  CORREO,
  CURP,
  OFICINA as ID_OFICINA,
  NOM_OFICINA as NOMBRE_OFICINA
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`;