CREATE OR REPLACE TABLE `DM_FRAUDES.DM_ASEGURADOS`  AS
SELECT
ZID AS ID,
NOMBRE,
GIRO,
NACIONALIDAD,
FOLIO,
APODERADO,
NAC_APODERADO AS NACIMIENTO_APODERADO,
RFC,
ART_140,
FEC_NACE AS FECHA_NACIMIENTO,
FEC_ALTA AS FECHA_ALTA,
TIP_ASEG AS TIPO_ASEGURADOS,
CORREO,
CURP,
OFICINA as ID_OFICINA,
NOM_OFICINA as NOMBRE_OFICINA
FROM `qualitasfraude.sample_landing_siniestros_bsc.maseg_bsc`;