MERGE INTO INSUMOS.DM_VALUACION tgt
USING RAW_INSUMOS.STG_VALUACION stg
ON (tgt.IDVALUACION = stg.IDVALUACION)
WHEN MATCHED THEN
  UPDATE SET
    tgt.DESCRIPCION = stg.DESCRIPCION,
    tgt.ALTA = stg.ALTA,
    tgt.ACTUALIZACION = stg.ACTUALIZACION,
    tgt.USUARIOACTUALIZA = stg.USUARIOACTUALIZA
WHEN NOT MATCHED THEN
  INSERT (
    IDVALUACION,
    DESCRIPCION,
    ALTA,
    ACTUALIZACION,
    USUARIOACTUALIZA
  )
  VALUES (
    stg.IDVALUACION,
    stg.DESCRIPCION,
    stg.ALTA,
    stg.ACTUALIZACION,
    stg.USUARIOACTUALIZA
  )