MERGE INTO INSUMOS.DM_AGENTES tgt
USING RAW_INSUMOS.STG_AGENTES stg
ON (tgt.CODIGO_AGENTE = stg.CODIGO_AGENTE)
WHEN MATCHED THEN
  UPDATE SET
    tgt.CODIGO_OFICINA = stg.CODIGO_OFICINA,
    tgt.CODIGO_GERENTE = stg.CODIGO_GERENTE,
    tgt.AGENTE = stg.AGENTE
WHEN NOT MATCHED THEN
  INSERT (
    CODIGO_OFICINA,
    CODIGO_GERENTE,
    CODIGO_AGENTE,
    AGENTE
  )
  VALUES (
    stg.CODIGO_OFICINA,
    stg.CODIGO_GERENTE,
    stg.CODIGO_AGENTE,
    stg.AGENTE
  )