MERGE INTO INSUMOS.DM_CAUSA_CAMBIO_VALE tgt
USING RAW_INSUMOS.STG_CAUSA_CAMBIO_VALE stg
ON (tgt.IDCAUSACAMBIOVALE = stg.IDCAUSACAMBIOVALE)
WHEN MATCHED THEN
  UPDATE SET
    tgt.DESCRIPCION = stg.DESCRIPCION,
    tgt.FECHAREGISTRO = stg.FECHAREGISTRO,
    tgt.FECHAACTUALIZACION = stg.FECHAACTUALIZACION,
    tgt.USUARIO = stg.USUARIO
WHEN NOT MATCHED THEN
  INSERT (
    IDCAUSACAMBIOVALE,
    DESCRIPCION,
    FECHAREGISTRO,
    FECHAACTUALIZACION,
    USUARIO
  )
  VALUES (
    stg.IDCAUSACAMBIOVALE,
    stg.DESCRIPCION,
    stg.FECHAREGISTRO,
    stg.FECHAACTUALIZACION,
    stg.USUARIO
  )