MERGE INTO INSUMOS.DM_CERCO tgt
USING RAW_INSUMOS.STG_CERCO stg
ON (tgt.IDCERCO = stg.IDCERCO)
WHEN MATCHED THEN
  UPDATE SET
    tgt.NOMBRE = stg.NOMBRE,
    tgt.FECHAREGISTRO = stg.FECHAREGISTRO,
    tgt.FECHAACTUALIZACION = stg.FECHAACTUALIZACION,
    tgt.IDENTIDAD = stg.IDENTIDAD,
    tgt.SUSPAUT = stg.SUSPAUT,
    tgt.IDCATEGORIACERCO = stg.IDCATEGORIACERCO,
    tgt.IDSEGMENTACION = stg.IDSEGMENTACION
WHEN NOT MATCHED THEN
  INSERT (
    IDCERCO,
    NOMBRE,
    FECHAREGISTRO,
    FECHAACTUALIZACION,
    IDENTIDAD,
    SUSPAUT,
    IDCATEGORIACERCO,
    IDSEGMENTACION
  )
  VALUES (
    stg.IDCERCO,
    stg.NOMBRE,
    stg.FECHAREGISTRO,
    stg.FECHAACTUALIZACION,
    stg.IDENTIDAD,
    stg.SUSPAUT,
    stg.IDCATEGORIACERCO,
    stg.IDSEGMENTACION
  );