MERGE INTO INSUMOS.DM_ESTADO tgt
USING RAW_INSUMOS.STG_ESTADO stg
ON (tgt.IDESTADO = stg.IDESTADO)
WHEN MATCHED THEN
  UPDATE SET
    tgt.NOMBRE = stg.NOMBRE,
    tgt.IDREGIONGEOGRAFICA = stg.IDREGIONGEOGRAFICA,
    tgt.ACTIVO = stg.ACTIVO
WHEN NOT MATCHED THEN
  INSERT (
    IDESTADO,
    NOMBRE,
    IDREGIONGEOGRAFICA,
    ACTIVO
  )
  VALUES (
    stg.IDESTADO,
    stg.NOMBRE,
    stg.IDREGIONGEOGRAFICA,
    stg.ACTIVO
  );