MERGE INTO INSUMOS.DM_DATOS_VEHICULO tgt
USING RAW_INSUMOS.STG_DATOS_VEHICULO stg
ON (tgt.IDDATOSVEHICULO = stg.IDDATOSVEHICULO)
WHEN MATCHED THEN
  UPDATE SET
    tgt.IDEXPEDIENTE = stg.IDEXPEDIENTE,
    tgt.IDVEHICULO = stg.IDVEHICULO,
    tgt.IDUSO = stg.IDUSO,
    tgt.IDMARCA = stg.IDMARCA,
    tgt.IDCOLOR = stg.IDCOLOR,
    tgt.CVESUBMARCA = stg.CVESUBMARCA,
    tgt.CVEAMIS = stg.CVEAMIS,
    tgt.TIPO = stg.TIPO,
    tgt.MODELO = stg.MODELO,
    tgt.PLACAS = stg.PLACAS,
    tgt.SERIE = stg.SERIE,
    tgt.MOTOR = stg.MOTOR,
    tgt.USOAMIS = stg.USOAMIS,
    tgt.PLACASANTERIOR = stg.PLACASANTERIOR,
    tgt.SERIEANTERIOR = stg.SERIEANTERIOR,
    tgt.IDUNIDAD = stg.IDUNIDAD,
    tgt.IDMARCATALLER = stg.IDMARCATALLER
WHEN NOT MATCHED THEN
  INSERT (
    IDDATOSVEHICULO,
    IDEXPEDIENTE,
    IDVEHICULO,
    IDUSO,
    IDMARCA,
    IDCOLOR,
    CVESUBMARCA,
    CVEAMIS,
    TIPO,
    MODELO,
    PLACAS,
    SERIE,
    MOTOR,
    USOAMIS,
    PLACASANTERIOR,
    SERIEANTERIOR,
    IDUNIDAD,
    IDMARCATALLER
  )
  VALUES (
    stg.IDDATOSVEHICULO,
    stg.IDEXPEDIENTE,
    stg.IDVEHICULO,
    stg.IDUSO,
    stg.IDMARCA,
    stg.IDCOLOR,
    stg.CVESUBMARCA,
    stg.CVEAMIS,
    stg.TIPO,
    stg.MODELO,
    stg.PLACAS,
    stg.SERIE,
    stg.MOTOR,
    stg.USOAMIS,
    stg.PLACASANTERIOR,
    stg.SERIEANTERIOR,
    stg.IDUNIDAD,
    stg.IDMARCATALLER
  )