MERGE INTO INSUMOS.DM_ANALISTA_CDR tgt
USING RAW_INSUMOS.STG_ANALISTA_CDR stg
ON (tgt.IDANALISTACDR = stg.IDANALISTACDR)
WHEN MATCHED THEN
  UPDATE SET
    tgt.CLAVEANALISTA = stg.CLAVEANALISTA,
    tgt.NOMBRENNALISTA = stg.NOMBRENNALISTA,
    tgt.ESTATUS = stg.ESTATUS,
    tgt.IDREGIONGEOGRAFICA = stg.IDREGIONGEOGRAFICA,
    tgt.FECHAREGISTROANL = stg.FECHAREGISTROANL,
    tgt.FECHAACTUALIZACIONANL = stg.FECHAACTUALIZACIONANL,
    tgt.CORREO = stg.CORREO,
    tgt.TELEFONO = stg.TELEFONO,
    tgt.CONSULTA = stg.CONSULTA
WHEN NOT MATCHED THEN
  INSERT (
    IDANALISTACDR,
    CLAVEANALISTA,
    NOMBRENNALISTA,
    ESTATUS,
    IDREGIONGEOGRAFICA,
    FECHAREGISTROANL,
    FECHAACTUALIZACIONANL,
    CORREO,
    TELEFONO,
    CONSULTA
  )
  VALUES (
    stg.IDANALISTACDR,
    stg.CLAVEANALISTA,
    stg.NOMBRENNALISTA,
    stg.ESTATUS,
    stg.IDREGIONGEOGRAFICA,
    stg.FECHAREGISTROANL,
    stg.FECHAACTUALIZACIONANL,
    stg.CORREO,
    stg.TELEFONO,
    stg.CONSULTA
  )