MERGE INTO INSUMOS.DM_OFICINAS tgt
USING RAW_INSUMOS.STG_OFICINAS stg
ON (tgt.ID = stg.ID)
WHEN MATCHED THEN
  UPDATE SET
    tgt.OFICINA = stg.OFICINA,
    tgt.DIRECCION = stg.DIRECCION,
    tgt.COLONIA = stg.COLONIA,
    tgt.POBLACION = stg.POBLACION,
    tgt.CODIGO_POBLACION = stg.CODIGO_POBLACION,
    tgt.CODIGO_POSTAL = stg.CODIGO_POSTAL,
    tgt.ZONA = stg.ZONA
WHEN NOT MATCHED THEN
  INSERT (
    ID,
    OFICINA,
    DIRECCION,
    COLONIA,
    POBLACION,
    CODIGO_POBLACION,
    CODIGO_POSTAL,
    ZONA
  )
  VALUES (
    stg.ID,
    stg.OFICINA,
    stg.DIRECCION,
    stg.COLONIA,
    stg.POBLACION,
    stg.CODIGO_POBLACION,
    stg.CODIGO_POSTAL,
    stg.ZONA
  )