MERGE INTO INSUMOS.DM_REGISTRO tgt
USING RAW_INSUMOS.STG_REGISTRO stg
ON (tgt.ID_SINIESTRO = stg.ID_SINIESTRO)
WHEN MATCHED THEN
  UPDATE SET
    tgt.ID_OFICINA = stg.ID_OFICINA,
    tgt.DESCRIPCION_OFICINA = stg.DESCRIPCION_OFICINA,
    tgt.USUARIO = stg.USUARIO,
    tgt.NOMBRE = stg.NOMBRE,
    tgt.CORREO = stg.CORREO,
    tgt.MOTIVO = stg.MOTIVO,
    tgt.OBSERVACIONES = stg.OBSERVACIONES,
    tgt.DOCUMENTO_ADICIONAL = stg.DOCUMENTO_ADICIONAL,
    tgt.SINIESTRO_ALERTADO = stg.SINIESTRO_ALERTADO,
    tgt.ID_ANALISTA = stg.ID_ANALISTA,
    tgt.FECHA_ASIGNACION = stg.FECHA_ASIGNACION,
    tgt.AREA = stg.AREA,
    tgt.PUESTO = stg.PUESTO,
    tgt.ID_MOTIVO = stg.ID_MOTIVO,
    tgt.MARCA = stg.MARCA,
    tgt.MONTO_ESTIMADO = stg.MONTO_ESTIMADO,
    tgt.FECHA_LOTE = stg.FECHA_LOTE,
    tgt.ID_USUARIO_SISTEMA = stg.ID_USUARIO_SISTEMA
WHEN NOT MATCHED THEN
  INSERT (
    ID_SINIESTRO,
    ID_OFICINA,
    DESCRIPCION_OFICINA,
    USUARIO,
    NOMBRE,
    CORREO,
    MOTIVO,
    OBSERVACIONES,
    DOCUMENTO_ADICIONAL,
    SINIESTRO_ALERTADO,
    ID_ANALISTA,
    FECHA_ASIGNACION,
    AREA,
    PUESTO,
    ID_MOTIVO,
    MARCA,
    MONTO_ESTIMADO,
    FECHA_LOTE,
    ID_USUARIO_SISTEMA
  )
  VALUES (
    stg.ID_SINIESTRO,
    stg.ID_OFICINA,
    stg.DESCRIPCION_OFICINA,
    stg.USUARIO,
    stg.NOMBRE,
    stg.CORREO,
    stg.MOTIVO,
    stg.OBSERVACIONES,
    stg.DOCUMENTO_ADICIONAL,
    stg.SINIESTRO_ALERTADO,
    stg.ID_ANALISTA,
    stg.FECHA_ASIGNACION,
    stg.AREA,
    stg.PUESTO,
    stg.ID_MOTIVO,
    stg.MARCA,
    stg.MONTO_ESTIMADO,
    stg.FECHA_LOTE,
    stg.ID_USUARIO_SISTEMA
  )