MERGE INTO INSUMOS.DM_ETIQUETA_SINIESTRO tgt
USING RAW_INSUMOS.STG_ETIQUETA_SINIESTRO stg
ON (tgt.ID = stg.ID)
WHEN MATCHED THEN
  UPDATE SET
    tgt.ID_REPORTE = stg.ID_REPORTE,
    tgt.ID_SINIESTRO = stg.ID_SINIESTRO,
    tgt.CODIGO_ESTATUS = stg.CODIGO_ESTATUS,
    tgt.FECHA_INVESTIGACION = stg.FECHA_INVESTIGACION,
    tgt.TEXTO_INVESTIGACION = stg.TEXTO_INVESTIGACION,
    tgt.USUARIO_INVESTIGACION = stg.USUARIO_INVESTIGACION,
    tgt.TEXTO_LOCALIZADO = stg.TEXTO_LOCALIZADO,
    tgt.FECHA_LOCALIZADO = stg.FECHA_LOCALIZADO,
    tgt.FECHA_CARGA = stg.FECHA_CARGA,
    tgt.FECHA_LOTE = stg.FECHA_LOTE,
    tgt.ID_USUARIO_SISTEMA = stg.ID_USUARIO_SISTEMA,
    tgt.CONSECUTIVO = stg.CONSECUTIVO,
    tgt.VALIDO_DESDE = stg.VALIDO_DESDE,
    tgt.VALIDO_HASTA = stg.VALIDO_HASTA,
    tgt.VALIDO = stg.VALIDO
WHEN NOT MATCHED THEN
  INSERT (
    ID,
    ID_REPORTE,
    ID_SINIESTRO,
    CODIGO_ESTATUS,
    FECHA_INVESTIGACION,
    TEXTO_INVESTIGACION,
    USUARIO_INVESTIGACION,
    TEXTO_LOCALIZADO,
    FECHA_LOCALIZADO,
    FECHA_CARGA,
    FECHA_LOTE,
    ID_USUARIO_SISTEMA,
    CONSECUTIVO,
    VALIDO_DESDE,
    VALIDO_HASTA,
    VALIDO
  )
  VALUES (
    stg.ID,
    stg.ID_REPORTE,
    stg.ID_SINIESTRO,
    stg.CODIGO_ESTATUS,
    stg.FECHA_INVESTIGACION,
    stg.TEXTO_INVESTIGACION,
    stg.USUARIO_INVESTIGACION,
    stg.TEXTO_LOCALIZADO,
    stg.FECHA_LOCALIZADO,
    stg.FECHA_CARGA,
    stg.FECHA_LOTE,
    stg.ID_USUARIO_SISTEMA,
    stg.CONSECUTIVO,
    stg.VALIDO_DESDE,
    stg.VALIDO_HASTA,
    stg.VALIDO
  )