MERGE INTO INSUMOS.DM_ESTADOS tgt
USING RAW_INSUMOS.STG_ESTADOS stg
ON (tgt.ID = stg.ID)
WHEN MATCHED THEN
  UPDATE SET
    tgt.ESTADO_POBLACION = stg.ESTADO_POBLACION,
    tgt.ESTATUS = stg.ESTATUS,
    tgt.CLAVE_INEGI = stg.CLAVE_INEGI,
    tgt.REGION = stg.REGION,
    tgt.RADIO_PERFIL = stg.RADIO_PERFIL,
    tgt.ESTADO_ESTANDAR = stg.ESTADO_ESTANDAR,
    tgt.ESTADO_POBLACION_2 = stg.ESTADO_POBLACION_2,
    tgt.CODIGO_ESTADO = stg.CODIGO_ESTADO,
    tgt.ESTADO = stg.ESTADO
WHEN NOT MATCHED THEN
  INSERT (
    ID,
    ESTADO_POBLACION,
    ESTATUS,
    CLAVE_INEGI,
    REGION,
    RADIO_PERFIL,
    ESTADO_ESTANDAR,
    ESTADO_POBLACION_2,
    CODIGO_ESTADO,
    ESTADO
  )
  VALUES (
    stg.ID,
    stg.ESTADO_POBLACION,
    stg.ESTATUS,
    stg.CLAVE_INEGI,
    stg.REGION,
    stg.RADIO_PERFIL,
    stg.ESTADO_ESTANDAR,
    stg.ESTADO_POBLACION_2,
    stg.CODIGO_ESTADO,
    stg.ESTADO
  )