MERGE INTO INSUMOS.DM_HISTORICO_TERMINO_ENTREGA tgt
USING RAW_INSUMOS.STG_HISTORICO_TERMINO_ENTREGA stg
ON (tgt.IDHISTORICOTERMINOENTREGA = stg.IDHISTORICOTERMINOENTREGA)
WHEN MATCHED THEN
  UPDATE SET
    tgt.IDEXPEDIENTE = stg.IDEXPEDIENTE,
    tgt.TIPOFECHA = stg.TIPOFECHA,
    tgt.FECHA = stg.FECHA
WHEN NOT MATCHED THEN
  INSERT (
    IDHISTORICOTERMINOENTREGA,
    IDEXPEDIENTE,
    TIPOFECHA,
    FECHA
  )
  VALUES (
    stg.IDHISTORICOTERMINOENTREGA,
    stg.IDEXPEDIENTE,
    stg.TIPOFECHA,
    stg.FECHA
  )