MERGE INTO INSUMOS.DM_REFACCION tgt
USING RAW_INSUMOS.STG_REFACCION stg
ON (tgt.IDREFACCION = stg.IDREFACCION)
WHEN MATCHED THEN
  UPDATE SET
    tgt.DESCRIPCION = stg.DESCRIPCION,
    tgt.ALTA = stg.ALTA,
    tgt.ACTUALIZACION = stg.ACTUALIZACION,
    tgt.USUARIOACTUALIZA = stg.USUARIOACTUALIZA,
    tgt.AUTOS = stg.AUTOS,
    tgt.EP = stg.EP
WHEN NOT MATCHED THEN
  INSERT (
    IDREFACCION,
    DESCRIPCION,
    ALTA,
    ACTUALIZACION,
    USUARIOACTUALIZA,
    AUTOS,
    EP
  )
  VALUES (
    stg.IDREFACCION,
    stg.DESCRIPCION,
    stg.ALTA,
    stg.ACTUALIZACION,
    stg.USUARIOACTUALIZA,
    stg.AUTOS,
    stg.EP
  )