MERGE INTO INSUMOS.DM_COLOR tgt
USING RAW_INSUMOS.STG_COLOR stg
ON (tgt.IDCOLOR = stg.IDCOLOR)
WHEN MATCHED THEN
  UPDATE SET
    tgt.DESCRIPCION = stg.DESCRIPCION,
    tgt.ALTA = stg.ALTA,
    tgt.ACTUALIZACION = stg.ACTUALIZACION,
    tgt.USUARIOACTUALIZA = stg.USUARIOACTUALIZA
WHEN NOT MATCHED THEN
  INSERT (
    IDCOLOR,
    DESCRIPCION,
    ALTA,
    ACTUALIZACION,
    USUARIOACTUALIZA
  )
  VALUES (
    stg.IDCOLOR,
    stg.DESCRIPCION,
    stg.ALTA,
    stg.ACTUALIZACION,
    stg.USUARIOACTUALIZA
  )