MERGE INTO INSUMOS.DM_TIPOS_PROVEEDORES tgt
USING RAW_INSUMOS.STG_TIPOS_PROVEEDORES stg
ON (tgt.ID = stg.ID)
WHEN MATCHED THEN
  UPDATE SET
    tgt.TIPO_PROVEEDOR = stg.TIPO_PROVEEDOR,
    tgt.GRUPO = stg.GRUPO,
    tgt.NOMBRE_GRUPO = stg.NOMBRE_GRUPO
WHEN NOT MATCHED THEN
  INSERT (
    ID,
    TIPO_PROVEEDOR,
    GRUPO,
    NOMBRE_GRUPO
  )
  VALUES (
    stg.ID,
    stg.TIPO_PROVEEDOR,
    stg.GRUPO,
    stg.NOMBRE_GRUPO
  )