MERGE INTO INSUMOS.DM_ESTATUS_EXPEDIENTES tgt
USING RAW_INSUMOS.STG_ESTATUS_EXPEDIENTES stg
ON (tgt.IDESTATUSEXPEDIENTE = stg.IDESTATUSEXPEDIENTE)
WHEN MATCHED THEN
  UPDATE SET
    tgt.DESCRIPCION = stg.DESCRIPCION,
    tgt.ALTA = stg.ALTA,
    tgt.ACTUALIZACION = stg.ACTUALIZACION,
    tgt.USUARIOACTUALIZA = stg.USUARIOACTUALIZA
WHEN NOT MATCHED THEN
  INSERT (
    IDESTATUSEXPEDIENTE,
    DESCRIPCION,
    ALTA,
    ACTUALIZACION,
    USUARIOACTUALIZA
  )
  VALUES (
    stg.IDESTATUSEXPEDIENTE,
    stg.DESCRIPCION,
    stg.ALTA,
    stg.ACTUALIZACION,
    stg.USUARIOACTUALIZA
  )