MERGE INTO INSUMOS.DM_GERENTES tgt
USING RAW_INSUMOS.STG_GERENTES stg
ON (tgt.CODIGO_GERENTE = stg.CODIGO_GERENTE)
WHEN MATCHED THEN
  UPDATE SET
    tgt.CODIGO_OFICINA = stg.CODIGO_OFICINA,
    tgt.GERENTE = stg.GERENTE
WHEN NOT MATCHED THEN
  INSERT (
    CODIGO_OFICINA,
    CODIGO_GERENTE,
    GERENTE
  )
  VALUES (
    stg.CODIGO_OFICINA,
    stg.CODIGO_GERENTE,
    stg.GERENTE
  )