MERGE INTO INSUMOS.DM_CAUSAS tgt
USING RAW_INSUMOS.STG_CAUSAS stg
ON (tgt.ID = stg.ID)
WHEN MATCHED THEN
  UPDATE SET
    tgt.CAUSA = stg.CAUSA,
    tgt.CAUSA_HOMOLOGADA = stg.CAUSA_HOMOLOGADA,
    tgt.FECHA_LOTE = stg.FECHA_LOTE,
    tgt.ID_USUARIO_SISTEMA = stg.ID_USUARIO_SISTEMA
WHEN NOT MATCHED THEN
  INSERT (
    ID,
    CAUSA,
    CAUSA_HOMOLOGADA,
    FECHA_LOTE,
    ID_USUARIO_SISTEMA
  )
  VALUES (
    stg.ID,
    stg.CAUSA,
    stg.CAUSA_HOMOLOGADA,
    stg.FECHA_LOTE,
    stg.ID_USUARIO_SISTEMA
  )