MERGE INTO INSUMOS.DM_SUPERVISOR_INTEGRAL tgt
USING RAW_INSUMOS.STG_SUPERVISOR_INTEGRAL stg
ON (tgt.IDSUPERVISORINTEGRAL = stg.IDSUPERVISORINTEGRAL)
WHEN MATCHED THEN
  UPDATE SET
    tgt.CLAVESUPERVISOR = stg.CLAVESUPERVISOR,
    tgt.NOMBRESUPERVISOR = stg.NOMBRESUPERVISOR,
    tgt.CORREO = stg.CORREO,
    tgt.TELEFONO = stg.TELEFONO,
    tgt.IDREGIONGEOGRAFICA = stg.IDREGIONGEOGRAFICA,
    tgt.ESTATUS = stg.ESTATUS,
    tgt.FECHAREGISTRO = stg.FECHAREGISTRO,
    tgt.FECHAACTUALIZACION = stg.FECHAACTUALIZACION,
    tgt.USUARIOREGISTRO = stg.USUARIOREGISTRO
WHEN NOT MATCHED THEN
  INSERT (
    IDSUPERVISORINTEGRAL,
    CLAVESUPERVISOR,
    NOMBRESUPERVISOR,
    CORREO,
    TELEFONO,
    IDREGIONGEOGRAFICA,
    ESTATUS,
    FECHAREGISTRO,
    FECHAACTUALIZACION,
    USUARIOREGISTRO
  )
  VALUES (
    stg.IDSUPERVISORINTEGRAL,
    stg.CLAVESUPERVISOR,
    stg.NOMBRESUPERVISOR,
    stg.CORREO,
    stg.TELEFONO,
    stg.IDREGIONGEOGRAFICA,
    stg.ESTATUS,
    stg.FECHAREGISTRO,
    stg.FECHAACTUALIZACION,
    stg.USUARIOREGISTRO
  );