MERGE INTO INSUMOS.DM_ENVIO_HISTORICO tgt
USING RAW_INSUMOS.STG_ENVIO_HISTORICO stg
ON (tgt.IDENVIOHISTORICO = stg.IDENVIOHISTORICO)
WHEN MATCHED THEN
  UPDATE SET
    tgt.IDEXPEDIENTE = stg.IDEXPEDIENTE,
    tgt.FECHAENVIOTALLER = stg.FECHAENVIOTALLER,
    tgt.FECHAASIGNACIONVALUADOR = stg.FECHAASIGNACIONVALUADOR,
    tgt.FECHAAUTORIZACIONVALUADOR = stg.FECHAAUTORIZACIONVALUADOR,
    tgt.DATO = stg.DATO,
    tgt.IDCAUSAASIGNARCOMPLEMENTO = stg.IDCAUSAASIGNARCOMPLEMENTO,
    tgt.AUTORIZADOAUTOMATICO = stg.AUTORIZADOAUTOMATICO,
    tgt.CODVALUADORCOMPLEMENTO = stg.CODVALUADORCOMPLEMENTO
WHEN NOT MATCHED THEN
  INSERT (
    IDENVIOHISTORICO,
    IDEXPEDIENTE,
    FECHAENVIOTALLER,
    FECHAASIGNACIONVALUADOR,
    FECHAAUTORIZACIONVALUADOR,
    DATO,
    IDCAUSAASIGNARCOMPLEMENTO,
    AUTORIZADOAUTOMATICO,
    CODVALUADORCOMPLEMENTO
  )
  VALUES (
    stg.IDENVIOHISTORICO,
    stg.IDEXPEDIENTE,
    stg.FECHAENVIOTALLER,
    stg.FECHAASIGNACIONVALUADOR,
    stg.FECHAAUTORIZACIONVALUADOR,
    stg.DATO,
    stg.IDCAUSAASIGNARCOMPLEMENTO,
    stg.AUTORIZADOAUTOMATICO,
    stg.CODVALUADORCOMPLEMENTO
  )