-- =====================================================
-- TRADUCCIÓN DE SAS SQL A BIGQUERY
-- Tablas intermedias: STG_PREVENCION_FRAUDES
-- Tabla final: DM_PREVENCION_FRAUDES.USUARIOHOMOLOGADO
-- =====================================================

-- 1. SUPERVISOR_SEGUIMENTO
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.SUPERVISOR_SEGUIMENTO` AS
SELECT 
    t1.CLAVESUPERVISOR AS CLAVE,
    t1.NOMBRESUPERVISOR AS USUARIO
FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.SUPERVISORINTEGRAL` t1
WHERE UPPER(t1.CLAVESUPERVISOR) LIKE '%SUPSEGQ%'
ORDER BY t1.NOMBRESUPERVISOR;

-- 2. SUPERVISOR_SERVICIOS
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.SUPERVISOR_SERVICIOS` AS
SELECT 
    t1.CLAVEANALISTA AS CLAVE,
    t1.NOMBRENNALISTA AS USUARIO
FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ANALISTACDR` t1
WHERE UPPER(t1.CLAVEANALISTA) LIKE '%SUPQ%'
ORDER BY t1.CLAVEANALISTA;

-- 3. SS1
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.SS1` AS
SELECT 
    t1.CLAVEANALISTA AS CLAVE,
    t1.NOMBRENNALISTA AS USUARIO
FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ANALISTACDR` t1
WHERE UPPER(t1.CLAVEANALISTA) LIKE '%ADMINCDR%';

-- 4. ASR
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.ASR` AS
SELECT 
    t1.IDADMINISTRADORREFACCIONES AS CLAVE,
    t1.NOMBRE AS USUARIO
FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ADMINISTRADORREFACCIONES` t1
WHERE UPPER(t1.IDADMINISTRADORREFACCIONES) LIKE '%ASR%'
ORDER BY t1.NOMBRE;

-- 5. COMP
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.COMP` AS
SELECT 
    t1.IDADMINISTRADORREFACCIONES AS CLAVE,
    t1.NOMBRE AS USUARIO
FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ADMINISTRADORREFACCIONES` t1
WHERE UPPER(t1.IDADMINISTRADORREFACCIONES) LIKE '%ADMINREFC%';

-- 6. ADMIN
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.ADMIN` AS
SELECT 
    t1.IDADMINISTRADORREFACCIONES AS CLAVE,
    t1.NOMBRE AS USUARIO
FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ADMINISTRADORREFACCIONES` t1
WHERE UPPER(t1.IDADMINISTRADORREFACCIONES) LIKE '%ADMIN%';

-- 7. PERSONALIZADO
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.PERSONALIZADO` AS
SELECT 
    t1.IDADMINISTRADORREFACCIONES AS CLAVE,
    t1.NOMBRE AS USUARIO
FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ADMINISTRADORREFACCIONES` t1
WHERE t1.IDADMINISTRADORREFACCIONES IN (
    'msalazar',
    'otoledo',
    'KGONZALEZ'
);

-- 8. CORCOMSEG
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.CORCOMSEG` AS
SELECT 
    t1.IDADMINISTRADORREFACCIONES AS CLAVE,
    t1.NOMBRE AS USUARIO
FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.ADMINISTRADORREFACCIONES` t1
WHERE UPPER(t1.IDADMINISTRADORREFACCIONES) LIKE '%CORCOMSEG%';

-- 9. VALUADORES
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.VALUADORES` AS
SELECT 
    t1.CODVALUADOR AS CLAVE,
    t3.Nombre AS USUARIO
FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.VALUADOR` t1
LEFT JOIN `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.PRESTADORES` t3 
    ON t1.CODVALUADOR = t3.Id
WHERE t3.Tipo = '45';

-- 10. TABLA CONSOLIDADA (APPEND_TABLE_0005)
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.APPEND_TABLE_0005` AS
SELECT * FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.SUPERVISOR_SEGUIMENTO`
UNION ALL
SELECT * FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.SUPERVISOR_SERVICIOS`
UNION ALL
SELECT * FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.VALUADORES`
UNION ALL
SELECT * FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.SS1`
UNION ALL
SELECT * FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.COMP`
UNION ALL
SELECT * FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.ADMIN`
UNION ALL
SELECT * FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.ASR`
UNION ALL
SELECT * FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.PERSONALIZADO`
UNION ALL
SELECT * FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.CORCOMSEG`;

-- 11. TABLA FINAL USUARIOHOMOLOGADO
CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.DM_PREVENCION_FRAUDES.USUARIOHOMOLOGADO` AS
SELECT DISTINCT 
    t1.CLAVE AS UsuarioBase,
    t1.USUARIO AS UsuarioHomologado
FROM `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.APPEND_TABLE_0005` t1;