-- Crea la tabla DM_ETIQUETA_SINIESTRO en el esquema DM_FRAUDES
-- y versiona los registros de como SCD-2
CREATE OR REPLACE TABLE `DM_FRAUDES.DM_ETIQUETA_SINIESTRO` AS
SELECT
  E1.Z_ID AS ID
  ,E1.REPORTE AS ID_REPORTE
  ,E1.SINIESTRO AS ID_SINIESTRO
  ,E1.COD_STATUS AS CODIGO_ESTATUS
  ,E1.FEC_INV AS FECHA_INVESTIGACION
  ,E1.TEXT_INVEST AS TEXTO_INVESTIGACION
  ,E1.USUARIO_INV AS USUARIO_INVESTIGACION
  ,E1.TEXT_LOC AS TEXTO_LOCALIZADO
  ,E1.FEC_LOC AS FECHA_LOCALIZADO
  ,E1.FEC_CARGA AS FECHA_CARGA
  ,E1.HORA_PROCESO FECHA_HORA_PROCESO
  ,E1.BATCHDATE AS FECHA_LOTE
  ,E1.SYSUSERID AS ID_USUARIO_SISTEMA
  ,E1.CONSECUTIVO AS CONSECUTIVO
  ,E1.FEC_CARGA AS VALIDO_DESDE
  ,CASE 
    WHEN E2.FEC_CARGA IS NOT NULL THEN E2.FEC_CARGA 
    ELSE TIMESTAMP('9999-12-31 23:59:59')
  END AS VALIDO_HASTA
  ,CASE 
    WHEN E2.FEC_CARGA IS NOT NULL THEN FALSE
    ELSE TRUE
  END AS VALIDO
FROM `STG_FRAUDES.STG_ETIQUETA_SINIESTRO_3` AS E1
LEFT JOIN `STG_FRAUDES.STG_ETIQUETA_SINIESTRO_3` AS E2
ON E1.REPORTE = E2.REPORTE AND E1.CONSECUTIVO+1 = E2.CONSECUTIVO
ORDER BY E1.Z_ID, E1.CONSECUTIVO