TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`;
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`
SELECT
  Z_ID
  ,CASE 
    WHEN REPORTE IS NULL THEN SUBSTRING(Z_ID, 1, (LENGTH(Z_ID)-2))
    ELSE REPORTE
  END AS REPORTE
  ,SINIESTRO
  ,COD_STATUS
  ,FEC_INV
  ,TEXT_INVEST
  ,USUARIO_INV
  ,TEXT_LOC
  ,FEC_LOC
  ,CAST(CONCAT(SUBSTRING(CAST(FEC_CARGA AS STRING),1,10),SUBSTRING(CAST(HORA_PROCESO AS STRING),11,9),'.000') AS DATETIME) AS FEC_CARGA
  ,BATCHDATE
  ,SYSUSERID
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`
WHERE SINIESTRO <> '0424' AND Z_ID IS NOT NULL
