CREATE OR REPLACE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`  AS
SELECT 
  ID_ANALISTA AS ID,
  ANALISTA,
  NOMBRE,
  CORREO,
  ESTATUS,
  CARRUSEL,
  ID_USER_94,
  BATCHDATE AS FECHA_LOTE,
  SYSUSERID AS ID_USUARIO_SISTEMA
  FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`
WHERE ID_ANALISTA IS NOT NULL AND ID_ANALISTA <> '10'