CREATE OR REPLACE TABLE `DM_FRAUDES.DM_ANALISTAS`  AS
SELECT 
ID_ANALISTA,
ANALISTA,
NOMBRE,
CORREO,
ESTATUS,
ESTATUS_DT AS FECHA_ESTATUS,
CARRUSEL,
ID_USER_94,
BATCHDATE AS FECHA_LOTE,
SYSUSERID AS ID_USUARIO_SISTEMA
FROM `qualitasfraude.sample_landing_siniestros.analistas`