BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_PROVEEDORES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Tabla DM_PROVEEDORES
CREATE TABLE INSUMOS.DM_PROVEEDORES (
    ID VARCHAR2(50) PRIMARY KEY,
    NOMBRE VARCHAR2(255),
    MARCA VARCHAR2(100),
    TIPO VARCHAR2(100),
    OFICINA VARCHAR2(100),
    SUSPENCION VARCHAR2(100),
    STATUS VARCHAR2(50),
    FECHA_BAJA DATE,
    CODIGO_ESTADO VARCHAR2(50),
    POBLACION VARCHAR2(100),
    DIRECCION VARCHAR2(255),
    DIRECCION_COMER VARCHAR2(255),
    COLONIA_COMER VARCHAR2(100),
    POBLACION_COMER VARCHAR2(100),
    ESTADO_COMER VARCHAR2(100),
    NUMERO_DOCTO VARCHAR2(100),
    NOMBRE_COMER VARCHAR2(255),
    GRUPO VARCHAR2(100),
    FECHA_ALTA DATE,
    CTA_ESP VARCHAR2(100),
    TIPO_AJUSTE VARCHAR2(100),
    TIPO_MARCA VARCHAR2(100),
    RFC VARCHAR2(50),
    CORREO_COMERCIAL VARCHAR2(255),
    CORREO_CONTACTO VARCHAR2(255),
    CORREO_COMERCIAL_2 VARCHAR2(255),
    MARCA_MOTOS VARCHAR2(100),
    TELEFONO_SIICA VARCHAR2(50),
    AE NUMBER(19),
    LATITUD VARCHAR2(50),
    LONGITUD VARCHAR2(50),
    RECIBE_24 VARCHAR2(10),
    ZONA_PROVEEDOR VARCHAR2(100),
    VED VARCHAR2(50),
    TIPO_PERSONA VARCHAR2(50),
    CEXP NUMBER(19),
    TBODY VARCHAR2(255),
    NUMERO_EMPLEADO VARCHAR2(50)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_CAUSAS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Tabla DM_CAUSAS
CREATE TABLE INSUMOS.DM_CAUSAS (
    ID VARCHAR2(50) PRIMARY KEY,
    CAUSA VARCHAR2(255),
    CAUSA_HOMOLOGADA VARCHAR2(255),
    FECHA_LOTE TIMESTAMP,
    ID_USUARIO_SISTEMA VARCHAR2(50)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_OFICINAS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Tabla DM_OFICINAS
CREATE TABLE INSUMOS.DM_OFICINAS (
    ID VARCHAR2(50) PRIMARY KEY,
    OFICINA VARCHAR2(100),
    DIRECCION VARCHAR2(255),
    COLONIA VARCHAR2(100),
    POBLACION VARCHAR2(100),
    CODIGO_POBLACION VARCHAR2(50),
    CODIGO_POSTAL VARCHAR2(20),
    ZONA VARCHAR2(100)
);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_SINIESTROS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Tabla DM_SINIESTROS (con referencias a tablas ya definidas)
CREATE TABLE INSUMOS.DM_SINIESTROS (
    ID VARCHAR2(100) PRIMARY KEY,
    REPORTE VARCHAR2(100),
    POLIZA VARCHAR2(50),
    ENDOSO VARCHAR2(50),
    INCISO VARCHAR2(20),
    ID_POLIZA_ENDOSO VARCHAR2(100),
    ID_POLIZA_ENDOSO_INCISO VARCHAR2(150),
    ASEGURADO VARCHAR2(200),
    ID_ASEGURADO VARCHAR2(50),
    ID_CAUSA VARCHAR2(50),
    FECHA_OCURRIDO DATE,
    FECHA_REPORTE DATE,
    FECHA_REGISTRO DATE,
    FECHA_INICIO_VIGENCIA DATE,
    MARCA VARCHAR2(100),
    MODELO VARCHAR2(100),
    SERIE VARCHAR2(50),
    SEVERIDAD NUMBER,
    STATUS VARCHAR2(20),
    RESERVA NUMBER(15,2),
    UBICACION VARCHAR2(200),
    ENTIDAD VARCHAR2(100),
    ID_OFICINA VARCHAR2(50),
    LEIDO_SAS VARCHAR2(1),
    ID_OFICINA_DE_ATENCION VARCHAR2(50),
    ID_AJUSTADOR VARCHAR2(50),
    LATITUD VARCHAR2(30),
    LONGITUD VARCHAR2(30),
    CONDUCTOR VARCHAR2(200),
    CODIGO_USO VARCHAR2(20),
    USO VARCHAR2(100),
    SUMA_ASEGURADA NUMBER(15,2),
    PLACA VARCHAR2(20),
    FECHA_EMISION DATE,
    POLIZA_REHABILITADA NUMBER(1),
    FECHA_FIN_VIGENCIA DATE,
    OBSERVACIONES VARCHAR2(4000),
    FECHA_LOTE DATE,
    ID_USUARIO_SISTEMA VARCHAR2(50)
);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_ETIQUETA_SINIESTRO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Tabla DM_ETIQUETA_SINIESTRO (con referencias a DM_SINIESTROS)
CREATE TABLE INSUMOS.DM_ETIQUETA_SINIESTRO (
    ID VARCHAR2(50) PRIMARY KEY,
    ID_REPORTE VARCHAR2(50),
    ID_SINIESTRO VARCHAR2(50),
    CODIGO_ESTATUS VARCHAR2(50),
    FECHA_INVESTIGACION TIMESTAMP,
    TEXTO_INVESTIGACION VARCHAR2(4000),
    USUARIO_INVESTIGACION VARCHAR2(255),
    TEXTO_LOCALIZADO VARCHAR2(4000),
    FECHA_LOCALIZADO TIMESTAMP,
    FECHA_CARGA TIMESTAMP,
    FECHA_LOTE TIMESTAMP,
    ID_USUARIO_SISTEMA VARCHAR2(50),
    CONSECUTIVO NUMBER(19),
    VALIDO_DESDE TIMESTAMP,
    VALIDO_HASTA TIMESTAMP,
    VALIDO NUMBER(1)
);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_PAGOS_POLIZAS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE INSUMOS.DM_PAGOS_POLIZAS (
    ID VARCHAR2(50) PRIMARY KEY,
    FECHA_VENCIMIENTO DATE,
    POLIZA VARCHAR2(50),
    ENDOSO VARCHAR2(50),
    POLIZA_ENDOSO VARCHAR2(100),
    IMPORTE NUMBER,
    REMESA VARCHAR2(50),
    MARCA_IMP DATE,
    MARCA_ANUL DATE,
    PRIMA_NETA NUMBER,
    DERECHO_POLIZA NUMBER,
    RECIBO_FIN NUMBER,
    IVA NUMBER,
    BONIFICACION NUMBER,
    BONIFICACION_RF NUMBER,
    BONIFICACION_TEC NUMBER,
    PRIMA_TOTAL NUMBER,
    USUARIO_APLICA VARCHAR2(50),
    FECHA_APLICACION DATE,
    RFC_FACTURACION VARCHAR2(13),
    USUARIO_EMITE VARCHAR2(50),
    STATUS VARCHAR2(10),
    FECHA_PROCESO DATE
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_PAGOS_PROVEEDORES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE INSUMOS.DM_PAGOS_PROVEEDORES (
    ID VARCHAR2(4000) PRIMARY KEY,
    ID_TRAMITE VARCHAR2(4000),
    IMPORTE_MANO_OBRA NUMBER,
    IMPORTE_REFACCIONES NUMBER,
    ID_PROVEEDOR VARCHAR2(4000),
    PROVEEDOR VARCHAR2(4000),
    CLAVE_DOCUMENTO VARCHAR2(4000),
    DOCUMENTO VARCHAR2(4000),
    IMPORTE NUMBER,
    ORDEN_PAGO VARCHAR2(4000),
    CODIGO_PAGO VARCHAR2(4000),
    CODIGO_GASTO VARCHAR2(4000),
    FECHA_PAGO TIMESTAMP,
    ID_MONEDA VARCHAR2(4000),
    COBERTURA VARCHAR2(4000),
    POLIZA VARCHAR2(4000),
    ENDOSO VARCHAR2(4000),
    ID_POLIZA_ENDOSO VARCHAR2(4000),
    ID_POLIZA_ENDOSO_INCISO VARCHAR2(4000),
    INCISO VARCHAR2(4000),
    CLAVE_SUBRAMO VARCHAR2(4000),
    TIPO_VEHICULO VARCHAR2(4000),
    USO_VEHICULO VARCHAR2(4000),
    SERVICIO_VEHICULO VARCHAR2(4000),
    AMIS VARCHAR2(4000),
    UNIDAD_VEHICULO VARCHAR2(4000),
    MODELO_VEHICULO VARCHAR2(4000),
    PRIMA_POLIZA NUMBER,
    ASEGURADO VARCHAR2(4000),
    ID_AGENTE VARCHAR2(4000),
    ID_OFICINA_EMISION VARCHAR2(4000),
    ID_OFICINA_ATENCION VARCHAR2(4000),
    ID_SINIESTRO VARCHAR2(4000),
    FECHA_OCURRIDO TIMESTAMP,
    DIAS NUMBER,
    ID_AJUSTADOR VARCHAR2(4000),
    ID_CAUSA VARCHAR2(4000),
    FECHA_REGISTRO TIMESTAMP,
    CODIGO_TEXTO VARCHAR2(4000),
    MARCA_VEHICULO VARCHAR2(4000),
    IMPORTE_DEDUCIBLE NUMBER,
    IMPORTE_TOTAL NUMBER,
    ORIGEN VARCHAR2(4000),
    BANCO VARCHAR2(4000),
    CHEQUE VARCHAR2(4000),
    CARATULA VARCHAR2(4000),
    ENTIDAD VARCHAR2(4000),
    NUMERO_NAGS NUMBER,
    FACTURA VARCHAR2(4000),
    ID_USUARIO_FILTRO VARCHAR2(4000),
    ID_USUARIO_TECNICO VARCHAR2(4000),
    ID_USUARIO_PAGO VARCHAR2(4000),
    ID_USUARIO_RESERVA VARCHAR2(4000),
    ID_VALUACION VARCHAR2(4000),
    TIEMPO_PAGO NUMBER
);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE INSUMOS.DM_COBERTURAS_MOVIMIENTOS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE INSUMOS.DM_COBERTURAS_MOVIMIENTOS (
    ID VARCHAR2(4000) PRIMARY KEY,
    RAMO VARCHAR2(4000),
    SUBRAMO VARCHAR2(4000),
    SINIESTRO VARCHAR2(4000),
    TIPO_SINIESTRO VARCHAR2(4000),
    ID_OFICINA_VENTAS VARCHAR2(4000),
    GERENTE VARCHAR2(4000),
    AGENTE VARCHAR2(4000),
    ID_OFICINA_DE_ATENCION VARCHAR2(4000),
    AJUSTADOR VARCHAR2(4000),
    FECHA_REGISTRO TIMESTAMP,
    FECHA_MOVIMIENTO TIMESTAMP,
    TIPO_MOVIMIENTO VARCHAR2(4000),
    GASTO VARCHAR2(4000),
    TIPO_MONEDA VARCHAR2(4000),
    COBERTURA VARCHAR2(4000),
    IMPORTE NUMBER,
    CAPUFE NUMBER,
    CODIGO_COBERTURA VARCHAR2(4000),
    CODIGO_TEXTO VARCHAR2(4000),
    TIPO_CAMBIO NUMBER,
    REPORTE VARCHAR2(4000),
    USUARIO VARCHAR2(4000),
    POLIZA VARCHAR2(4000),
    RELEVANTES VARCHAR2(4000),
    FECHA_OCURRIDO TIMESTAMP,
    TIPO_VEHICULO VARCHAR2(4000),
    MODELO_VEHICULO VARCHAR2(4000),
    CSTROS NUMBER,
    CRVA_INICIAL NUMBER,
    IRVA_INICIAL NUMBER,
    CAJMAS NUMBER,
    IAJMAS NUMBER,
    CAJMENOS NUMBER,
    IAJMENOS NUMBER,
    CPAGOS NUMBER,
    IPAGOS NUMBER,
    CGASTO NUMBER,
    IGASTO NUMBER,
    CDED NUMBER,
    IREC NUMBER,
    CSALV NUMBER,
    ISALV NUMBER,
    FLAG_REC VARCHAR2(4000),
    COD_RESP VARCHAR2(4000),
    DEPRES1 VARCHAR2(4000),
    DEPRES2 VARCHAR2(4000),
    DEPRES3 VARCHAR2(4000),
    DEPRESLIT VARCHAR2(4000),
    MONTO_INDEM_RECUP NUMBER,
    MONTO_INDEM_RECUP_DM NUMBER,
    IMPORTE_MN NUMBER,
    IRVA_INICIAL_MN NUMBER,
    IAJMASMN NUMBER,
    IAJMENOSMN NUMBER,
    IPAGOSMN NUMBER,
    IGASTOMN NUMBER,
    IDEDMN NUMBER,
    IRECMN NUMBER,
    ISALVMN NUMBER,
    MARCA_RVA VARCHAR2(4000),
    COAS NUMBER,
    NOMBRE_ASEGURADORA VARCHAR2(4000),
    CODIGO_POBLACION_ACC VARCHAR2(4000),
    REC_CANTO NUMBER,
    INVSALV VARCHAR2(4000),
    CODIGO_ESTADO_ACC VARCHAR2(4000),
    SINIESDIA NUMBER,
    CLAVE_ABOGADO VARCHAR2(4000)
);

