CREATE OR REPLACE TABLE `DM_FRAUDES.DM_PAGOS_PROVEEDORES` AS
SELECT 
  PP.SINIESTRO||PP.CVE_BENEF||PP.COD_PAGO||PP.NRO_OP||CAST(FLOOR(RAND() * 90000000) + 10000000 AS STRING) AS ID
  , PP.TRAMITE AS ID_TRAMITE
  , PP.MO AS IMPORTE_MANO_OBRA
  , PP.REFAC AS IMPORTE_REFACCIONES
  , PP.CVE_BENEF AS ID_PROVEEDOR
  , PP.BENEF AS PROVEEDOR
  , PP.CVE_DOCTO AS CLAVE_DOCUMENTO
  , PP.DOCTO AS DOCUMENTO
  , PP.IMPORTE
  , PP.NRO_OP AS ORDEN_PAGO
  , PP.COD_PAGO AS CODIGO_PAGO
  , PP.COD_GASTO AS CODIGO_GASTO
  , PP.FEC_PAGO AS FECHA_PAGO
  , PP.MONE AS ID_MONEDA
  , PP.COBER AS COBERTURA
  , PP.POL AS POLIZA
  , PP.ENDO AS ENDOSO
  , CONCAT(PPS.POLIZA,PPS.ENDOSO) AS ID_POLIZA_ENDOSO
  , CONCAT(PPS.POLIZA,PPS.ENDOSO,PPS.INCISO) AS ID_POLIZA_ENDOSO_INCISO
  , PP.INCI AS INCISO
  , PP.CVE_SUBR AS CLAVE_SUBRAMO
  , PP.TIPO AS TIPO_VEHICULO
  , PP.USO AS USO_VEHICULO
  , PP.SERVICIO AS SERVICIO_VEHICULO
  , PP.AMIS AS AMIS
  , PP.UNIDAD AS UNIDAD_VEHICULO
  , PP.MODELO AS MODELO_VEHICULO
  , PP.PRIMA_POL AS PRIMA_POLIZA
  , PP.ASEG AS ASEGURADO
  , PP.CVE_AGTE AS ID_AGENTE
  , PPS.Cve_Ofic_Emision AS ID_OFICINA_EMISION
  , PPS.Cve_Ofic_Atencion AS ID_OFICINA_ATENCION
  , PP.SINIESTRO AS ID_SINIESTRO
  , PP.FEC_OCU AS FECHA_OCURRIDO
  , PP.DIAS AS DIAS
  , PP.CVE_AJU AS ID_AJUSTADOR
  , PP.COD_CAUSA AS ID_CAUSA
  , PP.FEC_REG AS FECHA_REGISTRO
  , PP.COD_TXT CODIGO_TEXTO
  , PP.MARCA_VEH AS MARCA_VEHICULO
  , PP.IMP_DED IMPORTE_DEDUCIBLE
  , PP.IMP_TOT AS IMPORTE_TOTAL
  , PP.ORIGEN AS ORIGEN
  , PP.BANCO AS BANCO
  , PP.CHEQUE AS CHEQUE
  , PP.CARATULA AS CARATULA
  , PP.ENTIDAD AS ENTIDAD
  , PP.NUM_NAGS AS NUMERO_NAGS
  , PP.FACTURA
  , PP.`USU FILTRO` AS ID_USUARIO_FILTRO
  , PP.`USU TECNICO` AS ID_USUARIO_TECNICO
  , PP.`USU PAGO` AS ID_USUARIO_PAGO
  , PP.`USU RESERVA` AS ID_USUARIO_RESERVA
  , PP.VALUACION AS ID_VALUACION
  , PP.TMPO_PAGO_PT AS TIEMPO_PAGO
FROM sample_landing_siniestros_bsc.pagprove PP
INNER JOIN sample_landing_siniestros_bsc.pagosproveedores PPS ON PP.Z_ID = PPS.Clave 