TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`; 
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}` 
SELECT 
  SINIESTRO||CVE_BENEF||NRO_OP||CAST(FLOOR(RAND() * 90000000) + 10000000 AS STRING) AS ID 
  , TRAMITE AS ID_TRAMITE 
  , MO AS IMPORTE_MANO_OBRA 
  , REFAC AS IMPORTE_REFACCIONES 
  , CVE_BENEF AS ID_PROVEEDOR
  , BENEF AS PROVEEDOR
  , CVE_DOCTO AS CLAVE_DOCUMENTO
  , DOCTO AS DOCUMENTO
  , IMPORTE
  , NRO_OP AS ORDEN_PAGO
  , COD_PAGO AS CODIGO_PAGO
  , COD_GASTO AS CODIGO_GASTO
  , NULL AS TIPO_GASTO
  , FEC_PAGO AS FECHA_PAGO
  , MONE AS ID_MONEDA
  , COBER AS COBERTURA
  , POL AS POLIZA
  , ENDO AS ENDOSO
  , CONCAT(POL,ENDO) AS ID_POLIZA_ENDOSO
  , CONCAT(POL,ENDO,INCI) AS ID_POLIZA_ENDOSO_INCISO
  , INCI AS INCISO
  , CVE_SUBR AS CLAVE_SUBRAMO
  , TIPO AS TIPO_VEHICULO
  , USO AS USO_VEHICULO
  , SERVICIO AS SERVICIO_VEHICULO
  , AMIS AS AMIS
  , UNIDAD AS UNIDAD_VEHICULO
  , MODELO AS MODELO_VEHICULO
  , PRIMA_POL AS PRIMA_POLIZA
  , ASEG AS ASEGURADO
  , CVE_AGTE AS ID_AGENTE
  , NULL AS ID_OFICINA_EMISION
  , NULL AS ID_OFICINA_ATENCION
  , SINIESTRO AS ID_SINIESTRO
  , FEC_OCU AS FECHA_OCURRIDO
  , DIAS AS DIAS
  , CVE_AJU AS ID_AJUSTADOR
  , COD_CAUSA AS ID_CAUSA
  , FEC_REG AS FECHA_REGISTRO
  , COD_TXT CODIGO_TEXTO
  , MARCA_VEH AS MARCA_VEHICULO
  , IMP_DED IMPORTE_DEDUCIBLE
  , IMP_TOT AS IMPORTE_TOTAL
  , ORIGEN AS ORIGEN
  , BANCO AS BANCO
  , CHEQUE AS CHEQUE
  , CARATULA AS CARATULA
  , ENTIDAD AS ENTIDAD
  , NUM_NAGS AS NUMERO_NAGS
  , FACTURA
  , USU_FILTRO AS ID_USUARIO_FILTRO
  , USU_TECNICO AS ID_USUARIO_TECNICO
  , USU_PAGO AS ID_USUARIO_PAGO
  , USU_RESERVA AS ID_USUARIO_RESERVA
  , VALUACION AS ID_VALUACION
  , TMPO_PAGO_PT AS TIEMPO_PAGO
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`