TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`;
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`
SELECT 
  REPORTE
, SINIESTRO
, CVE_AJUS AS CLAVE_AJUSTADOR
, FEC_REP AS FECHA_REPORTE
, HORA_REP AS HORA_REPORTE  
, FEC_PAS AS FECHA_PASADO
, HORA_PAS AS HORA_PASADO
, TMPO_PASADO AS TIEMPO_PASADO
, FEC_LLEGA AS FECHA_LLEGADA
, HORA_LLEGA AS HORA_LLEGADA
, TMPO_ARRIBO AS TIEMPO_ARRIBO
, FEC_TERM AS FECHA_TERMINO
, HORA_TERM AS HORA_TERMINO
, TMPO_AJUST AS TIEMPO_AJUSTE
, TMPO_ATENCION AS TIEMPO_ATENCION
, OFIC_VTA AS OFICINA_VTA
, CAUSA 
, CABINISTA
, SUBR 
, TR_CARR
, CVE_AGENTE AS CLAVE_AGENTE
, REPORTE_OK 
, HORARIO
, LUGAR_ACC AS LUGAR_ACCIDENTE
, RANGO_ARRIBO 
, FEC_REG AS FECHA_REGISTRO
, CONT_STROS AS CONTROL_SINIESTROS
, FEC_HOR_REP AS FECHA_HORA_REPORTE
, FEC_HOR_ASI AS FECHA_HORA_ASIGNACION
, FEC_HOR_ARR AS FECHA_HORA_ARRIBO
, FEC_HOR_TER AS FECHA_HORA_TERMINO
, ASIGNACION AS ASIGNACION
, ARRIBO
, NRRep AS NUMERO_REPORTE
, POLIZA 
, CONDUCTOR
, COD_EDO_ACC AS CODIGO_ESTADO_ACCIDENTE
, REINGENIERIA 
, GEOLOC AS GEOLOCALIZACION
, GEOUBIC AS GEOUBICACION
, GEOASIG AS GEOASIGNACION
, COD_POB_ACC AS CODIGO_POBLACION_ACCIDENTE
, CVE_CAB AS CLAVE_CABINISTA
, TIPO_EVENTO 
, REIN
, HORA_INI_CAP AS HORA_INICIO_CAPTURA
, FEC_INI_CAP AS FECHA_INICIO_CAPTURA
, DATETIME(DATE('9999-12-31'),HORA_INICIO) AS HORA_INICIO
, DATETIME(DATE('9999-12-31'),HORA_TERMINO) AS HORA_TERMINO_2
, AJU_GA 
, GEOASIGR 
, TIPO_ROBO
, EVTO_ESP 
, NOMASEG AS NOMBRE_ASEGURADO
, CVENAGS AS CLAVE_NAGS
, SEGUROTERCERO AS SEGURO_TERCERO
, ASEGURADO AS ASEGURADO
, TIP_RESP_ORI
, INGRESO
, CRM
, TIPO_VEH AS TIPO_VEHICULO
, MODELO_VEH AS MODELO_VEHICULO
, PLACAS_VEH AS PLACAS_VEHICULO
, SERIE_VEH AS SERIE_VEHICULO
, ORGANISMO
, NUM_ECO AS NUMERO_ECO
, CALIDAD 
, COD_PRES AS CODIGO_PRES
, COD_RESP AS CODIGO_RESPUESTA
, LATITUD
, LONGITUD
, CVE_ABOGADO AS CLAVE_ABOGADO
, EXCLUIR
, RVAINICIAL AS RESERVA_INICIAL
, Today AS TODAY
, Colas AS COLAS
, DiaSemana AS DIA_SEMANA
, FEC_OCU AS FECHA_OCURRIDO
, NUMREC AS NUMERO_REC
, PROVREC AS PROVINCIA_REC
, ULTREC 
, CORREO
, LESIONADOS
, NOMLESIONADOS AS NUMERO_LESIONADOS
, CORREOVALIDO AS CORREO_VALIDO
, MARCA_ASEG AS MARCA_ASEG
, HORA_OCU AS HORA_OCURRIDO
, GRUA
, PASEM
, TIPO_POLIZA
, TMPO_PAGO_PT TIEMPO_PAGO_PT
, ETA
, EXTEMP
, COND_NOMBRE
, COND_PATERNO
, COND_MATERNO
, SINPOL
, CATEGORIA
, GEOTEL
, GEORAD
, TOKEN
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`;
