CREATE OR REPLACE TABLE `qlts-dev-mx-au-bro-verificacio.STG_PREVENCION_FRAUDES.EJECUTIVAS_SEG` AS 
  SELECT DISTINCT t1.CUENTA, 
  t1.CVE_AGENTE, 
  t1.EJECUTIVA
FROM `qlts-dev-mx-au-bro-verificacio.LAN_VERIFICACIONES.CLAVES_CTAS_ESPECIALES` t1;
