CREATE TABLE `qlts-dev-mx-au-bro-verificacio.DM_VERIFICACIONES.DM_ESTADOS`
(
  ID STRING,
  ESTADO_POBLACION STRING,
  ESTATUS STRING,
  CLAVE_INEGI STRING,
  REGION STRING,
  RADIO_PERFIL STRING,
  ESTADO_ESTANDAR STRING,
  ESTADO_POBLACION_2 STRING
);
