CREATE OR REPLACE TABLE `DM_FRAUDES.DM_OFICINAS`  AS
SELECT 
Z_ID AS ID,
OFICINA,
DIRECCION,
COLONIA,
POBLACION,
EDOPOB AS CODIGO_POBLACION,
CP AS CODIGO_POSTAL,
ZONA
FROM `qualitasfraude.sample_landing_siniestros_bsc.tsuc_bsc`