BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAW_INSUMOS.STG_AGENTES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE RAW_INSUMOS.STG_AGENTES (
  CODIGO_OFICINA VARCHAR2(16),
  CODIGO_GERENTE VARCHAR2(16),
  CODIGO_AGENTE VARCHAR2(16),
  AGENTE VARCHAR2(256)
);