BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAW_INSUMOS.STG_CERCO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE RAW_INSUMOS.STG_CERCO
(
    IDCERCO                 VARCHAR2(4000),
    NOMBRE                  VARCHAR2(4000),
    FECHAREGISTRO           DATE,
    FECHAACTUALIZACION      DATE,
    IDENTIDAD               VARCHAR2(4000),
    SUSPAUT                 VARCHAR2(4000),
    IDCATEGORIACERCO        VARCHAR2(4000),
    IDSEGMENTACION          VARCHAR2(4000)
);