BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAW_INSUMOS.STG_COBERTURAS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

-- Tabla DM_CAUSAS
CREATE TABLE RAW_INSUMOS.STG_COBERTURAS (
    ID VARCHAR2(50),
    COBERTURA VARCHAR2(255),
    COBERTURA_HOMOLOGADA VARCHAR2(255)
);