
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAW_INSUMOS.STG_ESTADO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE RAW_INSUMOS.STG_ESTADO
(
    IDESTADO                VARCHAR2(4000),
    NOMBRE                  VARCHAR2(4000),
    IDREGIONGEOGRAFICA      NUMBER,
    ACTIVO                  NUMBER
);
