BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAW_INSUMOS.STG_ANALISTA_CDR CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE RAW_INSUMOS.STG_ANALISTA_CDR
(
    IDANALISTACDR           VARCHAR2(4000) NOT NULL,
    CLAVEANALISTA           VARCHAR2(4000) NOT NULL,
    NOMBRENNALISTA          VARCHAR2(4000) NOT NULL,
    ESTATUS                 NUMBER NOT NULL,
    IDREGIONGEOGRAFICA      VARCHAR2(4000) NOT NULL,
    FECHAREGISTROANL        DATE NOT NULL,
    FECHAACTUALIZACIONANL   DATE,
    CORREO                  VARCHAR2(4000),
    TELEFONO                VARCHAR2(4000),
    CONSULTA                NUMBER
);