BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAW_INSUMOS.STG_CAUSA_CAMBIO_VALE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE RAW_INSUMOS.STG_CAUSA_CAMBIO_VALE
(
    IDCAUSACAMBIOVALE       VARCHAR2(4000) NOT NULL,
    DESCRIPCION             VARCHAR2(4000) NOT NULL,
    FECHAREGISTRO           DATE NOT NULL,
    FECHAACTUALIZACION      DATE NOT NULL,
    USUARIO                 VARCHAR2(4000) NOT NULL
);