BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAW_INSUMOS.STG_GERENTES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE RAW_INSUMOS.STG_GERENTES (
  CODIGO_OFICINA VARCHAR2(16),
  CODIGO_GERENTE VARCHAR2(16),
  GERENTE VARCHAR2(256)
);