BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAW_INSUMOS.STG_ESTADOS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE RAW_INSUMOS.STG_ESTADOS (
    ID VARCHAR2(4000),
    ESTADO_POBLACION VARCHAR2(4000),
    ESTATUS VARCHAR2(4000),
    CLAVE_INEGI VARCHAR2(4000),
    REGION VARCHAR2(4000),
    RADIO_PERFIL VARCHAR2(4000),
    ESTADO_ESTANDAR VARCHAR2(4000),
    ESTADO_POBLACION_2 VARCHAR2(4000),
    CODIGO_ESTADO VARCHAR2(2),
    ESTADO VARCHAR2(256)
);