BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAW_INSUMOS.STG_COLOR CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;

CREATE TABLE 	RAW_INSUMOS.STG_COLOR
(
    IDCOLOR                 VARCHAR2(4000),
    DESCRIPCION             VARCHAR2(4000),
    ALTA                    DATE,
    ACTUALIZACION           DATE,
    USUARIOACTUALIZA        VARCHAR2(4000)
);


