

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAW_INSUMOS.STG_VALUACION CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;


CREATE TABLE RAW_INSUMOS.STG_VALUACION
(
    IDVALUACION             VARCHAR2(4000) NOT NULL,
    DESCRIPCION             VARCHAR2(4000),
    ALTA                    DATE,
    ACTUALIZACION           DATE,
    USUARIOACTUALIZA        VARCHAR2(4000)
);
