
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE RAW_INSUMOS.STG_ENVIO_HISTORICO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
CREATE TABLE RAW_INSUMOS.STG_ENVIO_HISTORICO
(
    IDENVIOHISTORICO            VARCHAR2(4000),
    IDEXPEDIENTE                VARCHAR2(4000),
    FECHAENVIOTALLER            DATE,
    FECHAASIGNACIONVALUADOR     DATE,
    FECHAAUTORIZACIONVALUADOR   DATE,
    DATO                        VARCHAR2(4000),
    IDCAUSAASIGNARCOMPLEMENTO   VARCHAR2(4000),
    AUTORIZADOAUTOMATICO        NUMBER,
    CODVALUADORCOMPLEMENTO      VARCHAR2(4000)
);
