CREATE TABLE `qlts-dev-mx-au-bro-verificacio.STG_VERIFICACIONES.STG_ETIQUETA_SINIESTRO_3`
(
  Z_ID STRING,
  REPORTE STRING,
  SINIESTRO STRING,
  COD_STATUS STRING,
  FEC_INV DATETIME,
  TEXT_INVEST STRING,
  USUARIO_INV STRING,
  TEXT_LOC STRING,
  FEC_LOC DATETIME,
  FEC_CARGA DATETIME,
  BATCHDATE DATETIME,
  SYSUSERID STRING,
  CONSECUTIVO INT64
);
