CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  Z_ID STRING,
  REPORTE STRING,
  SINIESTRO STRING,
  COD_STATUS STRING,
  FEC_INV DATETIME,
  TEXT_INVEST STRING,
  USUARIO_INV STRING,
  TEXT_LOC STRING,
  FEC_LOC DATETIME,
  FEC_CARGA DATETIME,
  BATCHDATE DATETIME,
  SYSUSERID STRING
);
