CREATE TABLE `{{task.params.PROJECT_ID}}.{{task.params.DATASET_NAME}}.{{task.params.TABLE_NAME}}`
(
  ID_SINIESTRO STRING,
  ID_OFICINA STRING,
  DESCRIPCION_OFICINA STRING,
  USUARIO STRING,
  NOMBRE STRING,
  CORREO STRING,
  MOTIVO STRING,
  OBSERVACIONES STRING,
  DOCUMENTO_ADICIONAL STRING,
  SINIESTRO_ALERTADO STRING,
  ID_ANALISTA STRING,
  FECHA_ASIGNACION DATETIME,
  AREA STRING,
  PUESTO STRING,
  ID_MOTIVO STRING,
  MARCA STRING,
  MONTO_ESTIMADO NUMERIC,
  FECHA_LOTE DATETIME,
  ID_USUARIO_SISTEMA STRING,
  ROW_NUM INT64
);
