CREATE OR REPLACE TABLE `DM_FRAUDES.DM_PROVEEDORES` AS
SELECT 
ID, 
NOMBRE,
MARCA,
TIPO,
OFICINA,
SUSPENCION,
STATUS,
Fbaja AS FECHA_BAJA,
CodEstado AS CODIGO_ESTADO,
POBLACION,
DIRECCION,
Dir_Comer AS DIRECCION_COMER,
Col_Comer AS COLONIA_COMER,
Pob_Comer AS POBLACION_COMER,
Edo_Comer AS ESTADO_COMER,
Num_Docto AS NUMERO_DOCTO,
Nom_Comer AS NOMBRE_COMER,
GRUPO,
FEC_ALTA AS FECHA_ALTA,
CTA_ESP, ------------------
TIPO_AJUS AS TIPO_AJUSTE,
MARCA_TIPO AS TIPO_MARCA,
RFC,
CORREO_COMERCIAL,
CORREO_CONTACTO,
Correo_Comercial2 AS CORREO_COMERCIAL_2,
MARCA_MOTOS,
TEL_SIICA AS TELEFONO_SIICA,
AE, ------------------
LATITUD,
LONGITUD,
RECIBE24 AS RECIBE_24,
ZONAPROV AS ZONA_PROVEEDOR,
VED, -------------
TIPO_PERSONA,
CEXP, -----------------
TBODY, ----------------
NUM_EMPL AS NUMERO_EMPLEADO
FROM `qualitasfraude.sample_landing_siniestros_bsc.prestadores`