CREATE OR REPLACE TABLE `DM_FRAUDES.DM_CAUSA_COBERTURA` AS
SELECT 
  REGLA,
  CAUSAS,
  COBERTURA,
  COD_COBER AS CODIGO_COBERTURA,
  --CAST(BATCHDATE AS TIMESTAMP) AS FECHA_LOTE,
  SYSUSERID AS ID_USUARIO_SISTEMA
FROM `sample_landing_siniestros.causa_cobertura`