CREATE OR REPLACE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`  AS
SELECT 
  REGLA,
  CAUSAS,
  COBERTURA,
  COD_COBER AS CODIGO_COBERTURA,
  --CAST(BATCHDATE AS TIMESTAMP) AS FECHA_LOTE,
  SYSUSERID AS ID_USUARIO_SISTEMA
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`;