TRUNCATE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`;
INSERT INTO `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}`  
SELECT 
  Z_ID AS ID,
  CAUSA,
  CAUSA_HOMOLOGADA,
  BATCHDATE AS FECHA_LOTE,
  SYSUSERID AS ID_USUARIO_SISTEMA
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`
WHERE Z_ID IS NOT NULL AND Z_ID <> '*' AND Z_ID <> '9' AND Z_ID <> '2'
ORDER BY Z_ID;