CREATE OR REPLACE TABLE `DM_FRAUDES.DM_CAUSAS` AS
SELECT 
Z_ID AS ID,
CAUSA,
CAUSA_HOMOLOGADA,
BATCHDATE AS FECHA_LOTE,
SYSUSERID AS ID_USUARIO_SISTEMA
FROM `qualitasfraude.sample_landing_siniestros.DM_CAUSAS`