CREATE OR REPLACE TABLE `DM_FRAUDES.DM_CAUSA_COBERTURA` AS
SELECT 
REGLA,
CAUSAS,
COBERTURA,
COD_COBER AS CODIGO_COBERTURA,
BATCHDATE AS FECHA_LOTE,
SYSUSERID AS ID_USUARIO_SISTEMA
FROM `qualitasfraude.sample_landing_siniestros.causa_cobertura`