erDiagram

asegurados ||--|{ polizas_vigentes : manejan

polizas_vigentes ||--|{ vehiculos : contienen

polizas_vigentes ||--o{ pagos_polizas : realizan

proveedores ||--o{ siniestros : sirven

gerentes ||--o{ siniestros : gestionan

vehiculos ||--o{ siniestros : sufren

causas ||--o{ siniestros : originan

oficinas ||--o{ siniestros : gestionan

agentes ||--o{ siniestros : atienden

siniestros ||--o{ etiquetas_siniestros : descritos

siniestros ||--o{ coberturas : conllevan

siniestros ||--o{ pagos_siniestros : generan

proveedores {
    string ID PK
    string NOMBRE
    string MARCA
    string TIPO
    string OFICINA
    string SUSPENCION
    string STATUS
    datetime FECHA_BAJA
    string CODIGO_ESTADO
    string POBLACION
    string DIRECCION
    string DIRECCION_COMER
    string COLONIA_COMER
    string POBLACION_COMER
    string ESTADO_COMER
    string NUMERO_DOCTO
    string NOMBRE_COMER
    string GRUPO
    datetime FECHA_ALTA
    string CTA_ESP
    string TIPO_AJUSTE
    string TIPO_MARCA
    string RFC
    string CORREO_COMERCIAL
    string CORREO_CONTACTO
    string CORREO_COMERCIAL_2
    string MARCA_MOTOS
    string TELEFONO_SIICA
    int64 AE
    string LATITUD
    string LONGITUD
    string RECIBE_24
    string ZONA_PROVEEDOR
    string VED
    string TIPO_PERSONA
    int64 CEXP
    string TBODY
    string NUMERO_EMPLEADO
}

asegurados {
    string id PK
    string nombre
    string apellido_paterno
    string apellido_materno
    string fecha_alta
}

polizas_vigentes {
    string id PK
    string id_asegurado
    string poliza
    string ramo
    string endoso
    number prima_neta
    number prima_total
    number iva
    number subtotal
    date fecha_emision
    date vigente_desde
    date vigente_hasta
}

pagos_polizas {
    string id PK
    string id_poliza FK
    string seccion
    string endoso
    string poliza
    string numero_cobranza
    number prima_neta
    number iva
    number importe
    string remesa
    date fecha_vencimiento
    date fecha_aplicacion
    date fecha_carga
}

vehiculos {
    string id PK
    string seccion
    string poliza
    string endoso
    string inciso
    string marca_completa
    string marca_corta
    string subramo
    string modelo
    string origen
    string tipo_vehiculo
    string serie
    string placas
    string tipo_cobertura
    string categoria
    string valor_0km
    string suma_aseg
}

DM_CAT_CAUSA {
    string ID PK
    string CAUSA
    string CAUSA_HOMOLOGADA
    timestamp FECHA_LOTE
    string ID_USUARIO_SISTEMA FK
}

etiquetas_siniestros {
    string ID PK
    string ID_REPORTE FK
    string ID_SINIESTRO FK
    string CODIGO_ESTATUS
    timestamp FECHA_INVESTIGACION
    string TEXTO_INVESTIGACION
    string USUARIO_INVESTIGACION
    string TEXTO_LOCALIZADO
    timestamp FECHA_LOCALIZADO
    timestamp FECHA_CARGA
    timestamp FECHA_HORA_PROCESO
    timestamp FECHA_LOTE
    string ID_USUARIO_SISTEMA FK
    int64 CONSECUTIVO
    timestamp VALIDO_DESDE
    timestamp VALIDO_HASTA
    boolean VALIDO
    }

coberturas {
    string id PK
    string id_siniestro FK
    string codigo_cobertura
    string cobertura
    string tipo_movimiento
    string moneda
    number gasto
    number importe
    date fecha_registro
    date fecha_movimiento
}

causas {
    string REGLA
    string CAUSAS
    string COBERTURA
    string CODIGO_COBERTURA
    timestamp FECHA_LOTE
    string ID_USUARIO_SISTEMA FK
}

pagos_siniestros {
    string id PK
    string id_siniestro FK
    number importe
    date fecha_pago
}

gerentes {
    string id PK
    string nombre
}

oficinas {
    string ID PK
    string OFICINA
    string DIRECCION
    string COLONIA
    string POBLACION
    string CODIGO_POBLACION
    string CODIGO_POSTAL
    string ZONA
}

siniestros {
    string ID PK
    string REPORTE
    string POLIZA
    string ENDOSO
    string INCISO
    string ID_VEHICULO FK
    string ASEGURADO
    string ID_ASEGURADO FK
    string ID_CAUSA FK
    timestamp FECHA_OCURRIDO
    timestamp HORA_OCURRIDO
    timestamp FECHA_REPORTE
    timestamp HORA_REPORTE
    timestamp FECHA_REGISTRO
    timestamp HORA_REGISTRO
    timestamp FECHA_INICIO_VIGENCIA
    string MARCA
    string MODELO
    string SERIE
    numeric SEVERIDAD
    string STATUS
    numeric RESERVA
    string UBICACION
    string ENTIDAD
    string ID_OFICINA FK
    string LEIDO_SAS
    string ID_OFICINA_DE_ATENCION FK
    string ID_AJUSTADOR FK
    string LATITUD
    string LONGITUD
    string CONDUCTOR
    string CODIGO_USO
    string USO
    numeric SUMA_ASEGURADA
    string PLACA
    timestamp FECHA_EMISION
    string POLIZA_REHABILITADA
    timestamp FECHA_FIN_VIGENCIA
    string OBSERVACIONES
    timestamp FECHA_LOTE
    string ID_USUARIO_SISTEMA FK
}

agentes {
    string id PK
    string nombre
}