CREATE OR REPLACE TABLE `{{task.params.DEST_PROJECT_ID}}.{{task.params.DEST_DATASET_NAME}}.{{task.params.DEST_TABLE_NAME}}` AS
SELECT
  NAME_OF_THE_RULE,
  PARAMETER_NAME,
  PARAMETER_VALUE,
  SYSUSERID,
  PARSE_DATETIME('%d%b%Y:%H:%M:%S', BATCHDATE) AS BATCHDATE
FROM `{{task.params.SOURCE_PROJECT_ID}}.{{task.params.SOURCE_DATASET_NAME}}.{{task.params.SOURCE_TABLE_NAME}}`;